# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_dealrecipient_deal_agreed_pickup_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rater_role', models.CharField(choices=[('sender', 'Sender rating the traveler'), ('traveler', 'Traveler rating the sender')], max_length=10)),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('tags', models.JSONField(blank=True, default=list)),
                ('comment', models.TextField(blank=True, default='', max_length=4000)),
                ('review_window_ends_at', models.DateTimeField()),
                ('revealed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings', to='deals.deal')),
                ('ratee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ratings_given', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ratings_rating',
                'ordering': ['deal_id', 'rater_role'],
                'indexes': [models.Index(fields=['ratee', '-created_at'], name='ratings_ratee_idx'), models.Index(fields=['revealed_at', 'review_window_ends_at'], name='ratings_reveal_idx')],
                'constraints': [models.UniqueConstraint(fields=('deal', 'rater_role'), name='ratings_one_per_side_per_deal'), models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='ratings_score_range'), models.CheckConstraint(condition=models.Q(('rater', models.F('ratee')), _negated=True), name='ratings_rater_neq_ratee')],
            },
        ),
    ]
