from django.urls import path

from .views import (
    AdminAccountListView,
    AdminAccountRoleView,
    AdminAuditLogListView,
    AdminBoostListView,
    AdminDealDetailView,
    AdminDealListView,
    AdminDealNoShowView,
    AdminDisputeListView,
    AdminDisputeResolveView,
    AdminDisputeStatusView,
    AdminFlightProofListView,
    AdminFlightProofReviewView,
    AdminInvitationAcceptView,
    AdminInvitationListCreateView,
    AdminInvitationRevokeView,
    AdminJourneyListView,
    AdminKycListView,
    AdminKycReviewView,
    AdminMatchListView,
    AdminOfferListView,
    AdminPaymentAttemptListView,
    AdminPaymentOrderListView,
    AdminPayoutCompleteView,
    AdminPayoutListView,
    AdminProviderEventListView,
    AdminProviderHealthView,
    AdminRatingListView,
    AdminRefundListView,
    AdminRefundRequestView,
    AdminRefundSettleView,
    AdminRequestListView,
    AdminRoleMatrixView,
    AdminScheduledJobListView,
    AdminSettingsView,
    AdminUserDetailView,
    AdminUserListView,
    DashboardView,
)

urlpatterns = [
    path("admin/dashboard", DashboardView.as_view(), name="admin-dashboard"),
    path("admin/users", AdminUserListView.as_view(), name="admin-user-list"),
    path("admin/users/<int:pk>", AdminUserDetailView.as_view(), name="admin-user-detail"),
    path("admin/kyc", AdminKycListView.as_view(), name="admin-kyc-list"),
    path("admin/kyc/<int:pk>/review", AdminKycReviewView.as_view(), name="admin-kyc-review"),
    path("admin/flight-proofs", AdminFlightProofListView.as_view(), name="admin-flight-proof-list"),
    path("admin/flight-proofs/<int:pk>/review", AdminFlightProofReviewView.as_view(), name="admin-flight-proof-review"),
    path("admin/requests", AdminRequestListView.as_view(), name="admin-request-list"),
    path("admin/journeys", AdminJourneyListView.as_view(), name="admin-journey-list"),
    path("admin/matches", AdminMatchListView.as_view(), name="admin-match-list"),
    path("admin/offers", AdminOfferListView.as_view(), name="admin-offer-list"),
    path("admin/deals", AdminDealListView.as_view(), name="admin-deal-list"),
    path("admin/deals/<int:pk>", AdminDealDetailView.as_view(), name="admin-deal-detail"),
    path("admin/deals/<int:pk>/no-show", AdminDealNoShowView.as_view(), name="admin-deal-no-show"),
    path("admin/disputes", AdminDisputeListView.as_view(), name="admin-dispute-list"),
    path("admin/disputes/<int:pk>/status", AdminDisputeStatusView.as_view(), name="admin-dispute-status"),
    path("admin/disputes/<int:pk>/resolve", AdminDisputeResolveView.as_view(), name="admin-dispute-resolve"),
    path("admin/payment-orders", AdminPaymentOrderListView.as_view(), name="admin-payment-order-list"),
    path("admin/payment-attempts", AdminPaymentAttemptListView.as_view(), name="admin-payment-attempt-list"),
    path("admin/provider-events", AdminProviderEventListView.as_view(), name="admin-provider-event-list"),
    path("admin/refunds", AdminRefundListView.as_view(), name="admin-refund-list"),
    path("admin/refunds/request", AdminRefundRequestView.as_view(), name="admin-refund-request"),
    path("admin/refunds/<int:pk>/settle", AdminRefundSettleView.as_view(), name="admin-refund-settle"),
    path("admin/payouts", AdminPayoutListView.as_view(), name="admin-payout-list"),
    path("admin/payouts/<int:pk>/complete", AdminPayoutCompleteView.as_view(), name="admin-payout-complete"),
    path("admin/scheduled-jobs", AdminScheduledJobListView.as_view(), name="admin-scheduled-job-list"),
    path("admin/ratings", AdminRatingListView.as_view(), name="admin-rating-list"),
    path("admin/boosts", AdminBoostListView.as_view(), name="admin-boost-list"),
    path("admin/provider-health", AdminProviderHealthView.as_view(), name="admin-provider-health"),
    path("admin/settings", AdminSettingsView.as_view(), name="admin-settings"),
    path("admin/roles", AdminRoleMatrixView.as_view(), name="admin-role-matrix"),
    path("admin/accounts", AdminAccountListView.as_view(), name="admin-account-list"),
    path("admin/accounts/<int:pk>/role", AdminAccountRoleView.as_view(), name="admin-account-role"),
    path(
        "admin/invitations",
        AdminInvitationListCreateView.as_view(),
        name="admin-invitation-list-create",
    ),
    path(
        "admin/invitations/accept",
        AdminInvitationAcceptView.as_view(),
        name="admin-invitation-accept",
    ),
    path(
        "admin/invitations/<uuid:pk>/revoke",
        AdminInvitationRevokeView.as_view(),
        name="admin-invitation-revoke",
    ),
    path("admin/audit-log", AdminAuditLogListView.as_view(), name="admin-audit-log"),
]
