/// 58 Algerian wilayas. Mirror of `backend/monolith/apps/accounts/wilayas.py`.
class Wilaya {
  const Wilaya(this.code, this.name);
  final String code;
  final String name;
}

const List<Wilaya> kWilayas = [
  Wilaya('01', 'Adrar'),
  Wilaya('02', 'Chlef'),
  Wilaya('03', 'Laghouat'),
  Wilaya('04', 'Oum El Bouaghi'),
  Wilaya('05', 'Batna'),
  Wilaya('06', 'Bejaia'),
  Wilaya('07', 'Biskra'),
  Wilaya('08', 'Bechar'),
  Wilaya('09', 'Blida'),
  Wilaya('10', 'Bouira'),
  Wilaya('11', 'Tamanrasset'),
  Wilaya('12', 'Tebessa'),
  Wilaya('13', 'Tlemcen'),
  Wilaya('14', 'Tiaret'),
  Wilaya('15', 'Tizi Ouzou'),
  Wilaya('16', 'Algiers'),
  Wilaya('17', 'Djelfa'),
  Wilaya('18', 'Jijel'),
  Wilaya('19', 'Setif'),
  Wilaya('20', 'Saida'),
  Wilaya('21', 'Skikda'),
  Wilaya('22', 'Sidi Bel Abbes'),
  Wilaya('23', 'Annaba'),
  Wilaya('24', 'Guelma'),
  Wilaya('25', 'Constantine'),
  Wilaya('26', 'Medea'),
  Wilaya('27', 'Mostaganem'),
  Wilaya('28', "M'Sila"),
  Wilaya('29', 'Mascara'),
  Wilaya('30', 'Ouargla'),
  Wilaya('31', 'Oran'),
  Wilaya('32', 'El Bayadh'),
  Wilaya('33', 'Illizi'),
  Wilaya('34', 'Bordj Bou Arreridj'),
  Wilaya('35', 'Boumerdes'),
  Wilaya('36', 'El Tarf'),
  Wilaya('37', 'Tindouf'),
  Wilaya('38', 'Tissemsilt'),
  Wilaya('39', 'El Oued'),
  Wilaya('40', 'Khenchela'),
  Wilaya('41', 'Souk Ahras'),
  Wilaya('42', 'Tipaza'),
  Wilaya('43', 'Mila'),
  Wilaya('44', 'Ain Defla'),
  Wilaya('45', 'Naama'),
  Wilaya('46', 'Ain Temouchent'),
  Wilaya('47', 'Ghardaia'),
  Wilaya('48', 'Relizane'),
  Wilaya('49', 'Timimoun'),
  Wilaya('50', 'Bordj Badji Mokhtar'),
  Wilaya('51', 'Ouled Djellal'),
  Wilaya('52', 'Beni Abbes'),
  Wilaya('53', 'In Salah'),
  Wilaya('54', 'In Guezzam'),
  Wilaya('55', 'Touggourt'),
  Wilaya('56', 'Djanet'),
  Wilaya('57', "El M'Ghair"),
  Wilaya('58', 'El Meniaa'),
];
