--
-- PostgreSQL database dump
--

\restrict PDpJV1xjy0Hl8n5sdbPgYoQGcBhseGAmi1pLg1JrBkn3wkRaNrqcHngFE2SmGLh

-- Dumped from database version 16.13
-- Dumped by pg_dump version 16.13

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accounts_oauthidentity; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_oauthidentity (
    id bigint NOT NULL,
    provider character varying(16) NOT NULL,
    subject character varying(128) NOT NULL,
    email_at_link character varying(254) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: accounts_oauthidentity_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_oauthidentity ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_oauthidentity_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_passwordresetcode; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_passwordresetcode (
    id bigint NOT NULL,
    code_hash character varying(200) NOT NULL,
    attempts smallint NOT NULL,
    expires_at timestamp with time zone NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    CONSTRAINT accounts_passwordresetcode_attempts_check CHECK ((attempts >= 0))
);


--
-- Name: accounts_passwordresetcode_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_passwordresetcode ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_passwordresetcode_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user (
    id bigint NOT NULL,
    password character varying(128) NOT NULL,
    last_login timestamp with time zone,
    is_superuser boolean NOT NULL,
    username character varying(150) NOT NULL,
    first_name character varying(150) NOT NULL,
    last_name character varying(150) NOT NULL,
    is_staff boolean NOT NULL,
    is_active boolean NOT NULL,
    date_joined timestamp with time zone NOT NULL,
    email character varying(254) NOT NULL,
    full_name character varying(120) NOT NULL,
    phone character varying(32) NOT NULL,
    wilaya character varying(2) NOT NULL,
    role character varying(16) NOT NULL,
    is_phone_verified boolean NOT NULL,
    is_email_verified boolean NOT NULL,
    is_kyc_verified boolean NOT NULL,
    is_banned boolean NOT NULL
);


--
-- Name: accounts_user_groups; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_groups (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    group_id integer NOT NULL
);


--
-- Name: accounts_user_groups_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_groups ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_groups_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_user_user_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accounts_user_user_permissions (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: accounts_user_user_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.accounts_user_user_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.accounts_user_user_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: core_published_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.core_published_event (
    id uuid NOT NULL,
    channel character varying(128) NOT NULL,
    event_id character varying(64) NOT NULL,
    payload_hash character varying(64) NOT NULL,
    published_at timestamp with time zone NOT NULL,
    delivered_at timestamp with time zone
);


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: kyc_submission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.kyc_submission (
    id bigint NOT NULL,
    document_type character varying(24) NOT NULL,
    front_image_key character varying(512) NOT NULL,
    back_image_key character varying(512) NOT NULL,
    selfie_image_key character varying(512) NOT NULL,
    status character varying(16) NOT NULL,
    rejection_reason text NOT NULL,
    reviewed_by_id bigint,
    reviewed_at timestamp with time zone,
    expires_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    idempotency_key character varying(32) NOT NULL
);


--
-- Name: kyc_submission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.kyc_submission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kyc_submission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matching_event (
    id bigint NOT NULL,
    kind character varying(24) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    actor_id bigint,
    match_id bigint NOT NULL,
    offer_id bigint
);


--
-- Name: matching_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matching_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_match; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matching_match (
    id bigint NOT NULL,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    parcel_id bigint NOT NULL,
    sender_id bigint NOT NULL,
    traveler_id bigint NOT NULL,
    trip_id bigint NOT NULL
);


--
-- Name: matching_match_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matching_match ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_match_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: matching_offer; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.matching_offer (
    id bigint NOT NULL,
    proposed_by character varying(10) NOT NULL,
    base_amount_dzd integer NOT NULL,
    base_fee_dzd integer NOT NULL,
    commission_dzd integer NOT NULL,
    total_dzd integer NOT NULL,
    status character varying(12) NOT NULL,
    note text NOT NULL,
    expires_at timestamp with time zone,
    responded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    match_id bigint NOT NULL,
    parent_offer_id bigint,
    proposer_id bigint NOT NULL,
    CONSTRAINT matching_offer_base_amount_dzd_check CHECK ((base_amount_dzd >= 0)),
    CONSTRAINT matching_offer_base_fee_dzd_check CHECK ((base_fee_dzd >= 0)),
    CONSTRAINT matching_offer_commission_dzd_check CHECK ((commission_dzd >= 0)),
    CONSTRAINT matching_offer_total_dzd_check CHECK ((total_dzd >= 0))
);


--
-- Name: matching_offer_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.matching_offer ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.matching_offer_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parcels_delivery; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcels_delivery (
    parcelrequest_ptr_id bigint NOT NULL,
    base_amount_dzd integer NOT NULL,
    CONSTRAINT parcels_delivery_base_amount_dzd_check CHECK ((base_amount_dzd >= 0))
);


--
-- Name: parcels_media; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcels_media (
    id bigint NOT NULL,
    bucket character varying(64) NOT NULL,
    object_key character varying(255) NOT NULL,
    content_type character varying(64) NOT NULL,
    bytes integer NOT NULL,
    created_at timestamp with time zone NOT NULL,
    parcel_id bigint NOT NULL,
    CONSTRAINT parcels_media_bytes_check CHECK ((bytes >= 0))
);


--
-- Name: parcels_media_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parcels_media ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcels_media_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: parcels_product; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcels_product (
    parcelrequest_ptr_id bigint NOT NULL,
    product_url character varying(500) NOT NULL,
    store_name character varying(120) NOT NULL,
    product_price_dzd integer NOT NULL,
    CONSTRAINT parcels_product_product_price_dzd_check CHECK ((product_price_dzd >= 0))
);


--
-- Name: parcels_request; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.parcels_request (
    id bigint NOT NULL,
    kind character varying(12) NOT NULL,
    pickup_city character varying(80) NOT NULL,
    delivery_city character varying(80) NOT NULL,
    weight_kg smallint NOT NULL,
    item_type character varying(16) NOT NULL,
    description text NOT NULL,
    deadline_at timestamp with time zone,
    status character varying(16) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    destination_id character varying(3) NOT NULL,
    origin_id character varying(3) NOT NULL,
    sender_id bigint NOT NULL,
    CONSTRAINT parcels_origin_neq_destination CHECK ((NOT ((origin_id)::text = (destination_id)::text))),
    CONSTRAINT parcels_request_weight_kg_check CHECK ((weight_kg >= 0))
);


--
-- Name: parcels_request_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.parcels_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.parcels_request_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_event; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_event (
    id bigint NOT NULL,
    provider character varying(12) NOT NULL,
    provider_event_id character varying(128) NOT NULL,
    kind character varying(24) NOT NULL,
    payload jsonb NOT NULL,
    created_at timestamp with time zone NOT NULL,
    intent_id bigint NOT NULL
);


--
-- Name: payments_event_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_event ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_event_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_intent; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_intent (
    id bigint NOT NULL,
    provider character varying(12) NOT NULL,
    provider_intent_id character varying(128) NOT NULL,
    amount_minor integer NOT NULL,
    currency character varying(3) NOT NULL,
    status character varying(24) NOT NULL,
    client_idempotency_key character varying(64) NOT NULL,
    failure_code character varying(64) NOT NULL,
    failure_message character varying(255) NOT NULL,
    succeeded_at timestamp with time zone,
    refunded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    offer_id bigint NOT NULL,
    payer_id bigint NOT NULL,
    CONSTRAINT payments_intent_amount_minor_check CHECK ((amount_minor >= 0))
);


--
-- Name: payments_intent_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_intent ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_intent_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: payments_refund; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.payments_refund (
    id bigint NOT NULL,
    amount_minor integer NOT NULL,
    currency character varying(3) NOT NULL,
    provider character varying(12) NOT NULL,
    provider_refund_id character varying(128) NOT NULL,
    reason character varying(64) NOT NULL,
    status character varying(12) NOT NULL,
    succeeded_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    intent_id bigint NOT NULL,
    CONSTRAINT payments_refund_amount_minor_check CHECK ((amount_minor >= 0))
);


--
-- Name: payments_refund_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.payments_refund ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.payments_refund_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_blacklistedtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_blacklistedtoken (
    id bigint NOT NULL,
    blacklisted_at timestamp with time zone NOT NULL,
    token_id bigint NOT NULL
);


--
-- Name: token_blacklist_blacklistedtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_blacklistedtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_blacklistedtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: token_blacklist_outstandingtoken; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.token_blacklist_outstandingtoken (
    id bigint NOT NULL,
    token text NOT NULL,
    created_at timestamp with time zone,
    expires_at timestamp with time zone NOT NULL,
    user_id bigint,
    jti character varying(255) NOT NULL
);


--
-- Name: token_blacklist_outstandingtoken_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.token_blacklist_outstandingtoken ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.token_blacklist_outstandingtoken_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips_airport; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips_airport (
    iata character varying(3) NOT NULL,
    city character varying(80) NOT NULL,
    name character varying(120) NOT NULL,
    country character varying(2) NOT NULL
);


--
-- Name: trips_stopover; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips_stopover (
    id bigint NOT NULL,
    "position" smallint NOT NULL,
    arrives_at timestamp with time zone,
    departs_at timestamp with time zone,
    airport_id character varying(3) NOT NULL,
    trip_id bigint NOT NULL,
    CONSTRAINT trips_stopover_position_check CHECK (("position" >= 0))
);


--
-- Name: trips_stopover_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trips_stopover ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_stopover_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips_tracking_snapshot; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips_tracking_snapshot (
    id bigint NOT NULL,
    captured_at timestamp with time zone NOT NULL,
    status character varying(24) NOT NULL,
    latitude double precision,
    longitude double precision,
    altitude_m integer,
    speed_kph integer,
    raw jsonb NOT NULL,
    trip_id bigint NOT NULL
);


--
-- Name: trips_tracking_snapshot_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trips_tracking_snapshot ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_tracking_snapshot_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: trips_trip; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.trips_trip (
    id bigint NOT NULL,
    departure_at timestamp with time zone NOT NULL,
    capacity_kg smallint NOT NULL,
    notes text NOT NULL,
    status character varying(16) NOT NULL,
    flight_number character varying(12) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    destination_id character varying(3) NOT NULL,
    origin_id character varying(3) NOT NULL,
    traveler_id bigint NOT NULL,
    CONSTRAINT trips_origin_neq_destination CHECK ((NOT ((origin_id)::text = (destination_id)::text))),
    CONSTRAINT trips_trip_capacity_kg_check CHECK ((capacity_kg >= 0))
);


--
-- Name: trips_trip_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.trips_trip ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.trips_trip_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: verification_handover_code; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.verification_handover_code (
    id bigint NOT NULL,
    kind character varying(16) NOT NULL,
    code_hash character varying(255) NOT NULL,
    status character varying(16) NOT NULL,
    attempts smallint NOT NULL,
    used_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    issued_to_id bigint NOT NULL,
    match_id bigint NOT NULL,
    used_by_id bigint,
    CONSTRAINT verification_handover_code_attempts_check CHECK ((attempts >= 0))
);


--
-- Name: verification_handover_code_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.verification_handover_code ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.verification_handover_code_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_entry; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_entry (
    id bigint NOT NULL,
    kind character varying(12) NOT NULL,
    amount_minor bigint NOT NULL,
    currency character varying(3) NOT NULL,
    key character varying(128) NOT NULL,
    source character varying(24) NOT NULL,
    source_id bigint,
    note character varying(255) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    wallet_id bigint NOT NULL
);


--
-- Name: wallet_entry_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_entry ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_entry_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_hold; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_hold (
    id bigint NOT NULL,
    amount_minor bigint NOT NULL,
    currency character varying(3) NOT NULL,
    source character varying(24) NOT NULL,
    source_id bigint NOT NULL,
    status character varying(10) NOT NULL,
    opened_at timestamp with time zone NOT NULL,
    closed_at timestamp with time zone,
    wallet_id bigint NOT NULL,
    CONSTRAINT wallet_hold_amount_minor_check CHECK ((amount_minor >= 0))
);


--
-- Name: wallet_hold_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_hold ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_hold_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_wallet; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_wallet (
    id bigint NOT NULL,
    currency character varying(3) NOT NULL,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL
);


--
-- Name: wallet_wallet_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_wallet ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_wallet_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: wallet_withdrawal; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.wallet_withdrawal (
    id bigint NOT NULL,
    amount_minor bigint NOT NULL,
    currency character varying(3) NOT NULL,
    destination character varying(12) NOT NULL,
    destination_ref character varying(128) NOT NULL,
    status character varying(12) NOT NULL,
    sent_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL,
    updated_at timestamp with time zone NOT NULL,
    user_id bigint NOT NULL,
    wallet_id bigint NOT NULL,
    CONSTRAINT wallet_withdrawal_amount_minor_check CHECK ((amount_minor >= 0))
);


--
-- Name: wallet_withdrawal_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.wallet_withdrawal ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.wallet_withdrawal_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: accounts_oauthidentity accounts_oauthidentity_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_oauthidentity
    ADD CONSTRAINT accounts_oauthidentity_pkey PRIMARY KEY (id);


--
-- Name: accounts_passwordresetcode accounts_passwordresetcode_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_passwordresetcode
    ADD CONSTRAINT accounts_passwordresetcode_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_email_key UNIQUE (email);


--
-- Name: accounts_user_groups accounts_user_groups_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_groups accounts_user_groups_user_id_group_id_59c0b32f_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_group_id_59c0b32f_uniq UNIQUE (user_id, group_id);


--
-- Name: accounts_user accounts_user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_pkey PRIMARY KEY (id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permi_user_id_permission_id_2ab516c2_uniq UNIQUE (user_id, permission_id);


--
-- Name: accounts_user_user_permissions accounts_user_user_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_permissions_pkey PRIMARY KEY (id);


--
-- Name: accounts_user accounts_user_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user
    ADD CONSTRAINT accounts_user_username_key UNIQUE (username);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: core_published_event core_published_event_event_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_published_event
    ADD CONSTRAINT core_published_event_event_id_key UNIQUE (event_id);


--
-- Name: core_published_event core_published_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.core_published_event
    ADD CONSTRAINT core_published_event_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: kyc_submission kyc_submission_idempotency_key_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc_submission
    ADD CONSTRAINT kyc_submission_idempotency_key_key UNIQUE (idempotency_key);


--
-- Name: kyc_submission kyc_submission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc_submission
    ADD CONSTRAINT kyc_submission_pkey PRIMARY KEY (id);


--
-- Name: matching_event matching_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_event
    ADD CONSTRAINT matching_event_pkey PRIMARY KEY (id);


--
-- Name: matching_match matching_match_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_match
    ADD CONSTRAINT matching_match_pkey PRIMARY KEY (id);


--
-- Name: matching_offer matching_offer_parent_offer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_offer
    ADD CONSTRAINT matching_offer_parent_offer_id_key UNIQUE (parent_offer_id);


--
-- Name: matching_offer matching_offer_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_offer
    ADD CONSTRAINT matching_offer_pkey PRIMARY KEY (id);


--
-- Name: accounts_oauthidentity oauthidentity_provider_subject_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_oauthidentity
    ADD CONSTRAINT oauthidentity_provider_subject_unique UNIQUE (provider, subject);


--
-- Name: parcels_delivery parcels_delivery_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_delivery
    ADD CONSTRAINT parcels_delivery_pkey PRIMARY KEY (parcelrequest_ptr_id);


--
-- Name: parcels_media parcels_media_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_media
    ADD CONSTRAINT parcels_media_pkey PRIMARY KEY (id);


--
-- Name: parcels_media parcels_media_unique_object; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_media
    ADD CONSTRAINT parcels_media_unique_object UNIQUE (bucket, object_key);


--
-- Name: parcels_product parcels_product_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_product
    ADD CONSTRAINT parcels_product_pkey PRIMARY KEY (parcelrequest_ptr_id);


--
-- Name: parcels_request parcels_request_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_request
    ADD CONSTRAINT parcels_request_pkey PRIMARY KEY (id);


--
-- Name: payments_event payments_event_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_event
    ADD CONSTRAINT payments_event_pkey PRIMARY KEY (id);


--
-- Name: payments_event payments_event_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_event
    ADD CONSTRAINT payments_event_unique UNIQUE (provider, provider_event_id);


--
-- Name: payments_intent payments_intent_offer_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_intent
    ADD CONSTRAINT payments_intent_offer_id_key UNIQUE (offer_id);


--
-- Name: payments_intent payments_intent_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_intent
    ADD CONSTRAINT payments_intent_pkey PRIMARY KEY (id);


--
-- Name: payments_refund payments_refund_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_refund
    ADD CONSTRAINT payments_refund_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_pkey PRIMARY KEY (id);


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_key UNIQUE (token_id);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_uniq UNIQUE (jti);


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outstandingtoken_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outstandingtoken_pkey PRIMARY KEY (id);


--
-- Name: trips_airport trips_airport_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_airport
    ADD CONSTRAINT trips_airport_pkey PRIMARY KEY (iata);


--
-- Name: trips_stopover trips_stopover_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_stopover
    ADD CONSTRAINT trips_stopover_pkey PRIMARY KEY (id);


--
-- Name: trips_stopover trips_stopover_unique_position; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_stopover
    ADD CONSTRAINT trips_stopover_unique_position UNIQUE (trip_id, "position");


--
-- Name: trips_tracking_snapshot trips_tracking_snapshot_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_tracking_snapshot
    ADD CONSTRAINT trips_tracking_snapshot_pkey PRIMARY KEY (id);


--
-- Name: trips_trip trips_trip_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_trip
    ADD CONSTRAINT trips_trip_pkey PRIMARY KEY (id);


--
-- Name: verification_handover_code verification_handover_code_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_handover_code
    ADD CONSTRAINT verification_handover_code_pkey PRIMARY KEY (id);


--
-- Name: wallet_entry wallet_entry_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_entry
    ADD CONSTRAINT wallet_entry_pkey PRIMARY KEY (id);


--
-- Name: wallet_entry wallet_entry_unique_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_entry
    ADD CONSTRAINT wallet_entry_unique_key UNIQUE (wallet_id, key);


--
-- Name: wallet_hold wallet_hold_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_hold
    ADD CONSTRAINT wallet_hold_pkey PRIMARY KEY (id);


--
-- Name: wallet_hold wallet_hold_unique_source; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_hold
    ADD CONSTRAINT wallet_hold_unique_source UNIQUE (source, source_id);


--
-- Name: wallet_wallet wallet_unique_user_currency; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_unique_user_currency UNIQUE (user_id, currency);


--
-- Name: wallet_wallet wallet_wallet_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_pkey PRIMARY KEY (id);


--
-- Name: wallet_withdrawal wallet_withdrawal_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_withdrawal
    ADD CONSTRAINT wallet_withdrawal_pkey PRIMARY KEY (id);


--
-- Name: accounts_oa_user_id_170745_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_oa_user_id_170745_idx ON public.accounts_oauthidentity USING btree (user_id, provider);


--
-- Name: accounts_oauthidentity_user_id_906e1c75; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_oauthidentity_user_id_906e1c75 ON public.accounts_oauthidentity USING btree (user_id);


--
-- Name: accounts_pa_user_id_e7002a_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_pa_user_id_e7002a_idx ON public.accounts_passwordresetcode USING btree (user_id, used_at, expires_at);


--
-- Name: accounts_passwordresetcode_user_id_5331448e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_passwordresetcode_user_id_5331448e ON public.accounts_passwordresetcode USING btree (user_id);


--
-- Name: accounts_user_email_b2644a56_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_email_b2644a56_like ON public.accounts_user USING btree (email varchar_pattern_ops);


--
-- Name: accounts_user_groups_group_id_bd11a704; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_group_id_bd11a704 ON public.accounts_user_groups USING btree (group_id);


--
-- Name: accounts_user_groups_user_id_52b62117; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_groups_user_id_52b62117 ON public.accounts_user_groups USING btree (user_id);


--
-- Name: accounts_user_is_banned_7056432d; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_is_banned_7056432d ON public.accounts_user USING btree (is_banned);


--
-- Name: accounts_user_phone_c603acdd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_phone_c603acdd ON public.accounts_user USING btree (phone);


--
-- Name: accounts_user_phone_c603acdd_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_phone_c603acdd_like ON public.accounts_user USING btree (phone varchar_pattern_ops);


--
-- Name: accounts_user_user_permissions_permission_id_113bb443; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_permission_id_113bb443 ON public.accounts_user_user_permissions USING btree (permission_id);


--
-- Name: accounts_user_user_permissions_user_id_e4f0a161; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_user_permissions_user_id_e4f0a161 ON public.accounts_user_user_permissions USING btree (user_id);


--
-- Name: accounts_user_username_6088629e_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX accounts_user_username_6088629e_like ON public.accounts_user USING btree (username varchar_pattern_ops);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: core_pe_undelivered_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_pe_undelivered_idx ON public.core_published_event USING btree (delivered_at, published_at);


--
-- Name: core_published_event_channel_92dc2586; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_published_event_channel_92dc2586 ON public.core_published_event USING btree (channel);


--
-- Name: core_published_event_channel_92dc2586_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_published_event_channel_92dc2586_like ON public.core_published_event USING btree (channel varchar_pattern_ops);


--
-- Name: core_published_event_event_id_698b18a8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_published_event_event_id_698b18a8_like ON public.core_published_event USING btree (event_id varchar_pattern_ops);


--
-- Name: core_published_event_published_at_66c16e00; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX core_published_event_published_at_66c16e00 ON public.core_published_event USING btree (published_at);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: handover_one_active_per_match_kind; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX handover_one_active_per_match_kind ON public.verification_handover_code USING btree (match_id, kind) WHERE ((status)::text = 'active'::text);


--
-- Name: kyc_one_approved_per_user_doctype; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX kyc_one_approved_per_user_doctype ON public.kyc_submission USING btree (user_id, document_type) WHERE ((status)::text = 'approved'::text);


--
-- Name: kyc_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_status_idx ON public.kyc_submission USING btree (status);


--
-- Name: kyc_submission_idempotency_key_87ed0c3f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_submission_idempotency_key_87ed0c3f_like ON public.kyc_submission USING btree (idempotency_key varchar_pattern_ops);


--
-- Name: kyc_submission_status_166456ca; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_submission_status_166456ca ON public.kyc_submission USING btree (status);


--
-- Name: kyc_submission_status_166456ca_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_submission_status_166456ca_like ON public.kyc_submission USING btree (status varchar_pattern_ops);


--
-- Name: kyc_submission_user_id_88472018; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_submission_user_id_88472018 ON public.kyc_submission USING btree (user_id);


--
-- Name: kyc_user_latest_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX kyc_user_latest_idx ON public.kyc_submission USING btree (user_id, created_at DESC);


--
-- Name: match_event_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_event_idx ON public.matching_event USING btree (match_id, created_at DESC);


--
-- Name: match_parcel_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_parcel_status_idx ON public.matching_match USING btree (parcel_id, status);


--
-- Name: match_sender_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_sender_idx ON public.matching_match USING btree (sender_id, created_at DESC);


--
-- Name: match_traveler_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_traveler_idx ON public.matching_match USING btree (traveler_id, created_at DESC);


--
-- Name: match_trip_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX match_trip_status_idx ON public.matching_match USING btree (trip_id, status);


--
-- Name: match_unique_pending_pair; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX match_unique_pending_pair ON public.matching_match USING btree (parcel_id, trip_id) WHERE ((status)::text = 'pending'::text);


--
-- Name: matching_event_actor_id_4bbc578e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_event_actor_id_4bbc578e ON public.matching_event USING btree (actor_id);


--
-- Name: matching_event_match_id_9a46daed; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_event_match_id_9a46daed ON public.matching_event USING btree (match_id);


--
-- Name: matching_event_offer_id_0c174aa5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_event_offer_id_0c174aa5 ON public.matching_event USING btree (offer_id);


--
-- Name: matching_match_parcel_id_37bffd80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_parcel_id_37bffd80 ON public.matching_match USING btree (parcel_id);


--
-- Name: matching_match_sender_id_d5f8efbd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_sender_id_d5f8efbd ON public.matching_match USING btree (sender_id);


--
-- Name: matching_match_status_ce0f5571; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_status_ce0f5571 ON public.matching_match USING btree (status);


--
-- Name: matching_match_status_ce0f5571_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_status_ce0f5571_like ON public.matching_match USING btree (status varchar_pattern_ops);


--
-- Name: matching_match_traveler_id_efec247a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_traveler_id_efec247a ON public.matching_match USING btree (traveler_id);


--
-- Name: matching_match_trip_id_c9757271; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_match_trip_id_c9757271 ON public.matching_match USING btree (trip_id);


--
-- Name: matching_offer_match_id_e31edde3; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_offer_match_id_e31edde3 ON public.matching_offer USING btree (match_id);


--
-- Name: matching_offer_proposer_id_00bc9a80; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_offer_proposer_id_00bc9a80 ON public.matching_offer USING btree (proposer_id);


--
-- Name: matching_offer_status_50070c54; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_offer_status_50070c54 ON public.matching_offer USING btree (status);


--
-- Name: matching_offer_status_50070c54_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX matching_offer_status_50070c54_like ON public.matching_offer USING btree (status varchar_pattern_ops);


--
-- Name: offer_match_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX offer_match_idx ON public.matching_offer USING btree (match_id, created_at DESC);


--
-- Name: offer_one_accepted_per_match; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX offer_one_accepted_per_match ON public.matching_offer USING btree (match_id) WHERE ((status)::text = 'accepted'::text);


--
-- Name: offer_one_pending_per_match; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX offer_one_pending_per_match ON public.matching_offer USING btree (match_id) WHERE ((status)::text = 'pending'::text);


--
-- Name: offer_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX offer_status_idx ON public.matching_offer USING btree (status);


--
-- Name: parcels_corridor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_corridor_idx ON public.parcels_request USING btree (origin_id, destination_id, status);


--
-- Name: parcels_kind_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_kind_status_idx ON public.parcels_request USING btree (kind, status);


--
-- Name: parcels_media_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_media_idx ON public.parcels_media USING btree (parcel_id, created_at);


--
-- Name: parcels_media_parcel_id_4618cd58; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_media_parcel_id_4618cd58 ON public.parcels_media USING btree (parcel_id);


--
-- Name: parcels_request_destination_id_3759c9ba; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_destination_id_3759c9ba ON public.parcels_request USING btree (destination_id);


--
-- Name: parcels_request_destination_id_3759c9ba_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_destination_id_3759c9ba_like ON public.parcels_request USING btree (destination_id varchar_pattern_ops);


--
-- Name: parcels_request_kind_d2680e98; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_kind_d2680e98 ON public.parcels_request USING btree (kind);


--
-- Name: parcels_request_kind_d2680e98_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_kind_d2680e98_like ON public.parcels_request USING btree (kind varchar_pattern_ops);


--
-- Name: parcels_request_origin_id_ea79a227; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_origin_id_ea79a227 ON public.parcels_request USING btree (origin_id);


--
-- Name: parcels_request_origin_id_ea79a227_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_origin_id_ea79a227_like ON public.parcels_request USING btree (origin_id varchar_pattern_ops);


--
-- Name: parcels_request_sender_id_b6c24f22; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_sender_id_b6c24f22 ON public.parcels_request USING btree (sender_id);


--
-- Name: parcels_request_status_190c4686; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_status_190c4686 ON public.parcels_request USING btree (status);


--
-- Name: parcels_request_status_190c4686_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_request_status_190c4686_like ON public.parcels_request USING btree (status varchar_pattern_ops);


--
-- Name: parcels_sender_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX parcels_sender_idx ON public.parcels_request USING btree (sender_id, created_at DESC);


--
-- Name: payments_event_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_event_idx ON public.payments_event USING btree (intent_id, created_at DESC);


--
-- Name: payments_event_intent_id_ef557761; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_event_intent_id_ef557761 ON public.payments_event USING btree (intent_id);


--
-- Name: payments_intent_payer_id_58eeda3b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_intent_payer_id_58eeda3b ON public.payments_intent USING btree (payer_id);


--
-- Name: payments_intent_status_5f2168be; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_intent_status_5f2168be ON public.payments_intent USING btree (status);


--
-- Name: payments_intent_status_5f2168be_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_intent_status_5f2168be_like ON public.payments_intent USING btree (status varchar_pattern_ops);


--
-- Name: payments_one_open_per_offer; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX payments_one_open_per_offer ON public.payments_intent USING btree (offer_id) WHERE ((status)::text = ANY ((ARRAY['requires_payment_method'::character varying, 'processing'::character varying])::text[]));


--
-- Name: payments_payer_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_payer_idx ON public.payments_intent USING btree (payer_id, created_at DESC);


--
-- Name: payments_provider_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_provider_status_idx ON public.payments_intent USING btree (provider, status);


--
-- Name: payments_refund_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_refund_idx ON public.payments_refund USING btree (intent_id, created_at DESC);


--
-- Name: payments_refund_intent_id_0fcc71c9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_refund_intent_id_0fcc71c9 ON public.payments_refund USING btree (intent_id);


--
-- Name: payments_refund_unique_provider_id; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX payments_refund_unique_provider_id ON public.payments_refund USING btree (provider, provider_refund_id) WHERE (NOT ((provider_refund_id)::text = ''::text));


--
-- Name: payments_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX payments_status_idx ON public.payments_intent USING btree (status);


--
-- Name: payments_unique_client_key_per_payer; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX payments_unique_client_key_per_payer ON public.payments_intent USING btree (payer_id, client_idempotency_key) WHERE (NOT ((client_idempotency_key)::text = ''::text));


--
-- Name: payments_unique_provider_intent; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX payments_unique_provider_intent ON public.payments_intent USING btree (provider, provider_intent_id) WHERE (NOT ((provider_intent_id)::text = ''::text));


--
-- Name: token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_jti_hex_d9bdf6f7_like ON public.token_blacklist_outstandingtoken USING btree (jti varchar_pattern_ops);


--
-- Name: token_blacklist_outstandingtoken_user_id_83bc629a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX token_blacklist_outstandingtoken_user_id_83bc629a ON public.token_blacklist_outstandingtoken USING btree (user_id);


--
-- Name: trips_airport_country_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_airport_country_idx ON public.trips_airport USING btree (country);


--
-- Name: trips_airport_iata_e9932bf0_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_airport_iata_e9932bf0_like ON public.trips_airport USING btree (iata varchar_pattern_ops);


--
-- Name: trips_corridor_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_corridor_idx ON public.trips_trip USING btree (origin_id, destination_id, departure_at);


--
-- Name: trips_stopover_airport_id_0767c665; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_stopover_airport_id_0767c665 ON public.trips_stopover USING btree (airport_id);


--
-- Name: trips_stopover_airport_id_0767c665_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_stopover_airport_id_0767c665_like ON public.trips_stopover USING btree (airport_id varchar_pattern_ops);


--
-- Name: trips_stopover_trip_id_ff310d00; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_stopover_trip_id_ff310d00 ON public.trips_stopover USING btree (trip_id);


--
-- Name: trips_track_trip_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_track_trip_idx ON public.trips_tracking_snapshot USING btree (trip_id, captured_at DESC);


--
-- Name: trips_tracking_snapshot_trip_id_605cb5d5; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_tracking_snapshot_trip_id_605cb5d5 ON public.trips_tracking_snapshot USING btree (trip_id);


--
-- Name: trips_trip_destination_id_a03da6f8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_destination_id_a03da6f8 ON public.trips_trip USING btree (destination_id);


--
-- Name: trips_trip_destination_id_a03da6f8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_destination_id_a03da6f8_like ON public.trips_trip USING btree (destination_id varchar_pattern_ops);


--
-- Name: trips_trip_origin_id_043ab555; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_origin_id_043ab555 ON public.trips_trip USING btree (origin_id);


--
-- Name: trips_trip_origin_id_043ab555_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_origin_id_043ab555_like ON public.trips_trip USING btree (origin_id varchar_pattern_ops);


--
-- Name: trips_trip_status_b4892f21; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_status_b4892f21 ON public.trips_trip USING btree (status);


--
-- Name: trips_trip_status_b4892f21_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_status_b4892f21_like ON public.trips_trip USING btree (status varchar_pattern_ops);


--
-- Name: trips_trip_traveler_id_78282829; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_trip_traveler_id_78282829 ON public.trips_trip USING btree (traveler_id);


--
-- Name: trips_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX trips_user_idx ON public.trips_trip USING btree (traveler_id, departure_at DESC);


--
-- Name: verification_handover_code_issued_to_id_14f1a0fd; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_issued_to_id_14f1a0fd ON public.verification_handover_code USING btree (issued_to_id);


--
-- Name: verification_handover_code_kind_28a9cb35; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_kind_28a9cb35 ON public.verification_handover_code USING btree (kind);


--
-- Name: verification_handover_code_kind_28a9cb35_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_kind_28a9cb35_like ON public.verification_handover_code USING btree (kind varchar_pattern_ops);


--
-- Name: verification_handover_code_match_id_de694667; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_match_id_de694667 ON public.verification_handover_code USING btree (match_id);


--
-- Name: verification_handover_code_status_799e9e47; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_status_799e9e47 ON public.verification_handover_code USING btree (status);


--
-- Name: verification_handover_code_status_799e9e47_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_status_799e9e47_like ON public.verification_handover_code USING btree (status varchar_pattern_ops);


--
-- Name: verification_handover_code_used_by_id_3599beae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX verification_handover_code_used_by_id_3599beae ON public.verification_handover_code USING btree (used_by_id);


--
-- Name: wallet_entry_source_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_entry_source_idx ON public.wallet_entry USING btree (source, source_id);


--
-- Name: wallet_entry_wallet_id_008ca9ae; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_entry_wallet_id_008ca9ae ON public.wallet_entry USING btree (wallet_id);


--
-- Name: wallet_entry_wallet_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_entry_wallet_idx ON public.wallet_entry USING btree (wallet_id, created_at DESC);


--
-- Name: wallet_hold_source_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_hold_source_idx ON public.wallet_hold USING btree (source, source_id);


--
-- Name: wallet_hold_status_58298504; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_hold_status_58298504 ON public.wallet_hold USING btree (status);


--
-- Name: wallet_hold_status_58298504_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_hold_status_58298504_like ON public.wallet_hold USING btree (status varchar_pattern_ops);


--
-- Name: wallet_hold_wallet_id_b20de9ff; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_hold_wallet_id_b20de9ff ON public.wallet_hold USING btree (wallet_id);


--
-- Name: wallet_hold_wallet_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_hold_wallet_idx ON public.wallet_hold USING btree (wallet_id, status);


--
-- Name: wallet_wallet_user_id_8c75caaa; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_wallet_user_id_8c75caaa ON public.wallet_wallet USING btree (user_id);


--
-- Name: wallet_wd_status_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_wd_status_idx ON public.wallet_withdrawal USING btree (status);


--
-- Name: wallet_wd_user_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_wd_user_idx ON public.wallet_withdrawal USING btree (user_id, created_at DESC);


--
-- Name: wallet_withdrawal_status_372e26a8; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_withdrawal_status_372e26a8 ON public.wallet_withdrawal USING btree (status);


--
-- Name: wallet_withdrawal_status_372e26a8_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_withdrawal_status_372e26a8_like ON public.wallet_withdrawal USING btree (status varchar_pattern_ops);


--
-- Name: wallet_withdrawal_user_id_4fd05cda; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_withdrawal_user_id_4fd05cda ON public.wallet_withdrawal USING btree (user_id);


--
-- Name: wallet_withdrawal_wallet_id_4825123a; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX wallet_withdrawal_wallet_id_4825123a ON public.wallet_withdrawal USING btree (wallet_id);


--
-- Name: accounts_oauthidentity accounts_oauthidentity_user_id_906e1c75_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_oauthidentity
    ADD CONSTRAINT accounts_oauthidentity_user_id_906e1c75_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_passwordresetcode accounts_passwordresetcode_user_id_5331448e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_passwordresetcode
    ADD CONSTRAINT accounts_passwordresetcode_user_id_5331448e_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_group_id_bd11a704_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_group_id_bd11a704_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_groups accounts_user_groups_user_id_52b62117_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_groups
    ADD CONSTRAINT accounts_user_groups_user_id_52b62117_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_permission_id_113bb443_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_permission_id_113bb443_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: accounts_user_user_permissions accounts_user_user_p_user_id_e4f0a161_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accounts_user_user_permissions
    ADD CONSTRAINT accounts_user_user_p_user_id_e4f0a161_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: kyc_submission kyc_submission_user_id_88472018_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.kyc_submission
    ADD CONSTRAINT kyc_submission_user_id_88472018_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_event matching_event_actor_id_4bbc578e_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_event
    ADD CONSTRAINT matching_event_actor_id_4bbc578e_fk_accounts_user_id FOREIGN KEY (actor_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_event matching_event_match_id_9a46daed_fk_matching_match_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_event
    ADD CONSTRAINT matching_event_match_id_9a46daed_fk_matching_match_id FOREIGN KEY (match_id) REFERENCES public.matching_match(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_event matching_event_offer_id_0c174aa5_fk_matching_offer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_event
    ADD CONSTRAINT matching_event_offer_id_0c174aa5_fk_matching_offer_id FOREIGN KEY (offer_id) REFERENCES public.matching_offer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_match matching_match_parcel_id_37bffd80_fk_parcels_request_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_match
    ADD CONSTRAINT matching_match_parcel_id_37bffd80_fk_parcels_request_id FOREIGN KEY (parcel_id) REFERENCES public.parcels_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_match matching_match_sender_id_d5f8efbd_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_match
    ADD CONSTRAINT matching_match_sender_id_d5f8efbd_fk_accounts_user_id FOREIGN KEY (sender_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_match matching_match_traveler_id_efec247a_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_match
    ADD CONSTRAINT matching_match_traveler_id_efec247a_fk_accounts_user_id FOREIGN KEY (traveler_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_match matching_match_trip_id_c9757271_fk_trips_trip_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_match
    ADD CONSTRAINT matching_match_trip_id_c9757271_fk_trips_trip_id FOREIGN KEY (trip_id) REFERENCES public.trips_trip(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offer matching_offer_match_id_e31edde3_fk_matching_match_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_offer
    ADD CONSTRAINT matching_offer_match_id_e31edde3_fk_matching_match_id FOREIGN KEY (match_id) REFERENCES public.matching_match(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offer matching_offer_parent_offer_id_8439dc32_fk_matching_offer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_offer
    ADD CONSTRAINT matching_offer_parent_offer_id_8439dc32_fk_matching_offer_id FOREIGN KEY (parent_offer_id) REFERENCES public.matching_offer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: matching_offer matching_offer_proposer_id_00bc9a80_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.matching_offer
    ADD CONSTRAINT matching_offer_proposer_id_00bc9a80_fk_accounts_user_id FOREIGN KEY (proposer_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_delivery parcels_delivery_parcelrequest_ptr_id_fd65b55b_fk_parcels_r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_delivery
    ADD CONSTRAINT parcels_delivery_parcelrequest_ptr_id_fd65b55b_fk_parcels_r FOREIGN KEY (parcelrequest_ptr_id) REFERENCES public.parcels_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_media parcels_media_parcel_id_4618cd58_fk_parcels_request_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_media
    ADD CONSTRAINT parcels_media_parcel_id_4618cd58_fk_parcels_request_id FOREIGN KEY (parcel_id) REFERENCES public.parcels_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_product parcels_product_parcelrequest_ptr_id_cd16db97_fk_parcels_r; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_product
    ADD CONSTRAINT parcels_product_parcelrequest_ptr_id_cd16db97_fk_parcels_r FOREIGN KEY (parcelrequest_ptr_id) REFERENCES public.parcels_request(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_request parcels_request_destination_id_3759c9ba_fk_trips_airport_iata; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_request
    ADD CONSTRAINT parcels_request_destination_id_3759c9ba_fk_trips_airport_iata FOREIGN KEY (destination_id) REFERENCES public.trips_airport(iata) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_request parcels_request_origin_id_ea79a227_fk_trips_airport_iata; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_request
    ADD CONSTRAINT parcels_request_origin_id_ea79a227_fk_trips_airport_iata FOREIGN KEY (origin_id) REFERENCES public.trips_airport(iata) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: parcels_request parcels_request_sender_id_b6c24f22_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.parcels_request
    ADD CONSTRAINT parcels_request_sender_id_b6c24f22_fk_accounts_user_id FOREIGN KEY (sender_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_event payments_event_intent_id_ef557761_fk_payments_intent_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_event
    ADD CONSTRAINT payments_event_intent_id_ef557761_fk_payments_intent_id FOREIGN KEY (intent_id) REFERENCES public.payments_intent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_intent payments_intent_offer_id_3ebd08f9_fk_matching_offer_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_intent
    ADD CONSTRAINT payments_intent_offer_id_3ebd08f9_fk_matching_offer_id FOREIGN KEY (offer_id) REFERENCES public.matching_offer(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_intent payments_intent_payer_id_58eeda3b_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_intent
    ADD CONSTRAINT payments_intent_payer_id_58eeda3b_fk_accounts_user_id FOREIGN KEY (payer_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: payments_refund payments_refund_intent_id_0fcc71c9_fk_payments_intent_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.payments_refund
    ADD CONSTRAINT payments_refund_intent_id_0fcc71c9_fk_payments_intent_id FOREIGN KEY (intent_id) REFERENCES public.payments_intent(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_blacklistedtoken token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_blacklistedtoken
    ADD CONSTRAINT token_blacklist_blacklistedtoken_token_id_3cc7fe56_fk FOREIGN KEY (token_id) REFERENCES public.token_blacklist_outstandingtoken(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: token_blacklist_outstandingtoken token_blacklist_outs_user_id_83bc629a_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.token_blacklist_outstandingtoken
    ADD CONSTRAINT token_blacklist_outs_user_id_83bc629a_fk_accounts_ FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_stopover trips_stopover_airport_id_0767c665_fk_trips_airport_iata; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_stopover
    ADD CONSTRAINT trips_stopover_airport_id_0767c665_fk_trips_airport_iata FOREIGN KEY (airport_id) REFERENCES public.trips_airport(iata) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_stopover trips_stopover_trip_id_ff310d00_fk_trips_trip_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_stopover
    ADD CONSTRAINT trips_stopover_trip_id_ff310d00_fk_trips_trip_id FOREIGN KEY (trip_id) REFERENCES public.trips_trip(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_tracking_snapshot trips_tracking_snapshot_trip_id_605cb5d5_fk_trips_trip_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_tracking_snapshot
    ADD CONSTRAINT trips_tracking_snapshot_trip_id_605cb5d5_fk_trips_trip_id FOREIGN KEY (trip_id) REFERENCES public.trips_trip(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_trip trips_trip_destination_id_a03da6f8_fk_trips_airport_iata; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_trip
    ADD CONSTRAINT trips_trip_destination_id_a03da6f8_fk_trips_airport_iata FOREIGN KEY (destination_id) REFERENCES public.trips_airport(iata) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_trip trips_trip_origin_id_043ab555_fk_trips_airport_iata; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_trip
    ADD CONSTRAINT trips_trip_origin_id_043ab555_fk_trips_airport_iata FOREIGN KEY (origin_id) REFERENCES public.trips_airport(iata) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: trips_trip trips_trip_traveler_id_78282829_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.trips_trip
    ADD CONSTRAINT trips_trip_traveler_id_78282829_fk_accounts_user_id FOREIGN KEY (traveler_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: verification_handover_code verification_handove_issued_to_id_14f1a0fd_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_handover_code
    ADD CONSTRAINT verification_handove_issued_to_id_14f1a0fd_fk_accounts_ FOREIGN KEY (issued_to_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: verification_handover_code verification_handove_match_id_de694667_fk_matching_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_handover_code
    ADD CONSTRAINT verification_handove_match_id_de694667_fk_matching_ FOREIGN KEY (match_id) REFERENCES public.matching_match(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: verification_handover_code verification_handove_used_by_id_3599beae_fk_accounts_; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.verification_handover_code
    ADD CONSTRAINT verification_handove_used_by_id_3599beae_fk_accounts_ FOREIGN KEY (used_by_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_entry wallet_entry_wallet_id_008ca9ae_fk_wallet_wallet_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_entry
    ADD CONSTRAINT wallet_entry_wallet_id_008ca9ae_fk_wallet_wallet_id FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_hold wallet_hold_wallet_id_b20de9ff_fk_wallet_wallet_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_hold
    ADD CONSTRAINT wallet_hold_wallet_id_b20de9ff_fk_wallet_wallet_id FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_wallet wallet_wallet_user_id_8c75caaa_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_wallet
    ADD CONSTRAINT wallet_wallet_user_id_8c75caaa_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_withdrawal wallet_withdrawal_user_id_4fd05cda_fk_accounts_user_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_withdrawal
    ADD CONSTRAINT wallet_withdrawal_user_id_4fd05cda_fk_accounts_user_id FOREIGN KEY (user_id) REFERENCES public.accounts_user(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: wallet_withdrawal wallet_withdrawal_wallet_id_4825123a_fk_wallet_wallet_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.wallet_withdrawal
    ADD CONSTRAINT wallet_withdrawal_wallet_id_4825123a_fk_wallet_wallet_id FOREIGN KEY (wallet_id) REFERENCES public.wallet_wallet(id) DEFERRABLE INITIALLY DEFERRED;


--
-- PostgreSQL database dump complete
--

\unrestrict PDpJV1xjy0Hl8n5sdbPgYoQGcBhseGAmi1pLg1JrBkn3wkRaNrqcHngFE2SmGLh

