# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_dealrecipient_deal_agreed_pickup_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('opened_by_role', models.CharField(choices=[('sender', 'Sender'), ('traveler', 'Traveler'), ('admin', 'Admin')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('awaiting_evidence', 'Awaiting evidence'), ('under_review', 'Under review'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=20)),
                ('category', models.CharField(choices=[('not_delivered', 'Parcel not delivered'), ('damaged', 'Parcel damaged'), ('wrong_item', 'Wrong or missing contents'), ('late', 'Delivered far too late'), ('no_show', 'Counterparty did not show up'), ('payment', 'Payment or amount problem'), ('other', 'Other')], max_length=20)),
                ('reason_text', models.TextField(max_length=4000)),
                ('evidence_bundle', models.JSONField(blank=True, default=dict)),
                ('protection_ends_at', models.DateTimeField(blank=True, null=True)),
                ('opened_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolution', models.CharField(blank=True, choices=[('full_sender_refund', 'Full sender refund'), ('full_traveler_payout', 'Full traveler payout'), ('partial_split', 'Partial split')], default='', max_length=24)),
                ('sender_refund_eur_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('traveler_payout_eur_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('platform_fee_eur_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('collected_total_eur_cents', models.PositiveBigIntegerField(blank=True, null=True)),
                ('resolution_note', models.TextField(blank=True, default='', max_length=4000)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('payout_frozen', models.BooleanField(default=False)),
                ('payout_already_settled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes', to='deals.deal')),
                ('opened_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disputes_opened', to=settings.AUTH_USER_MODEL)),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes_dispute',
                'ordering': ['-opened_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('opened', 'Opened'), ('status_changed', 'Status changed'), ('evidence_added', 'Evidence added'), ('bundle_captured', 'Evidence bundle captured'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('payout_frozen', 'Payout frozen'), ('note', 'Administrative note')], max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dispute_events', to=settings.AUTH_USER_MODEL)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='disputes.dispute')),
            ],
            options={
                'db_table': 'disputes_event',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DisputeEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Text'), ('photo', 'Photo'), ('video', 'Video')], max_length=10)),
                ('text', models.TextField(blank=True, default='', max_length=4000)),
                ('storage_bucket', models.CharField(blank=True, default='', max_length=64)),
                ('storage_key', models.CharField(blank=True, default='', max_length=255)),
                ('content_type', models.CharField(blank=True, default='', max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(blank=True, null=True)),
                ('content_sha256', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='evidence', to='disputes.dispute')),
                ('submitted_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispute_evidence', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'disputes_evidence',
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['status', '-opened_at'], name='disputes_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='dispute',
            index=models.Index(fields=['deal', '-opened_at'], name='disputes_deal_idx'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['open', 'awaiting_evidence', 'under_review'])), fields=('deal',), name='disputes_one_active_per_deal'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'resolved'), _negated=True), models.Q(models.Q(('resolution', ''), _negated=True), ('resolved_at__isnull', False), ('resolved_by__isnull', False)), _connector='OR'), name='disputes_resolved_requires_evidence'),
        ),
        migrations.AddConstraint(
            model_name='dispute',
            constraint=models.CheckConstraint(condition=models.Q(('collected_total_eur_cents__isnull', True), ('collected_total_eur_cents', django.db.models.expressions.CombinedExpression(django.db.models.expressions.CombinedExpression(models.F('sender_refund_eur_cents'), '+', models.F('traveler_payout_eur_cents')), '+', models.F('platform_fee_eur_cents'))), _connector='OR'), name='disputes_resolution_reconciles'),
        ),
        migrations.AddIndex(
            model_name='disputeevent',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_event_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeevidence',
            index=models.Index(fields=['dispute', 'created_at'], name='disputes_evidence_idx'),
        ),
        migrations.AddConstraint(
            model_name='disputeevidence',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'text'), ('storage_key', ''), models.Q(('text', ''), _negated=True)), models.Q(models.Q(('kind', 'text'), _negated=True), models.Q(('storage_key', ''), _negated=True)), _connector='OR'), name='disputes_evidence_payload_matches_kind'),
        ),
    ]
