# Generated by Django 5.1.4 on 2026-08-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dispute',
            options={'ordering': ['-opened_at', '-id'], 'permissions': [('resolve_dispute', 'Can resolve a dispute and settle its money'), ('view_dispute_evidence', 'Can view dispute evidence files')]},
        ),
    ]
