# Generated by Django 5.1.4 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_emailverificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='', help_text='Durable communication preference. Blank is a legacy/unselected value and resolves to English when an outbound message is queued.', max_length=2),
        ),
    ]
