# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: kyc.proto
# Protobuf Python Version: 5.28.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    1,
    '',
    'kyc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tkyc.proto\x12\x0fshiptrip.kyc.v1\"\xc4\x01\n\x17RecordSubmissionRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\x03\x12\x34\n\rdocument_type\x18\x02 \x01(\x0e\x32\x1d.shiptrip.kyc.v1.DocumentType\x12\x17\n\x0fidempotency_key\x18\x03 \x01(\t\x12\x17\n\x0f\x66ront_image_key\x18\x04 \x01(\t\x12\x16\n\x0e\x62\x61\x63k_image_key\x18\x05 \x01(\t\x12\x18\n\x10selfie_image_key\x18\x06 \x01(\t\"k\n\x18RecordSubmissionResponse\x12\x15\n\rsubmission_id\x18\x01 \x01(\x03\x12\x0f\n\x07\x63reated\x18\x02 \x01(\x08\x12\'\n\x06status\x18\x03 \x01(\x0e\x32\x17.shiptrip.kyc.v1.Status*\x87\x01\n\x0c\x44ocumentType\x12\x1d\n\x19\x44OCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n\x15\x44OCUMENT_TYPE_ID_CARD\x10\x01\x12\x1a\n\x16\x44OCUMENT_TYPE_PASSPORT\x10\x02\x12!\n\x1d\x44OCUMENT_TYPE_DRIVING_LICENSE\x10\x03*r\n\x06Status\x12\x16\n\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n\x0eSTATUS_PENDING\x10\x01\x12\x13\n\x0fSTATUS_APPROVED\x10\x02\x12\x13\n\x0fSTATUS_REJECTED\x10\x03\x12\x12\n\x0eSTATUS_EXPIRED\x10\x04\x32\x7f\n\x14KYCSubmissionService\x12g\n\x10RecordSubmission\x12(.shiptrip.kyc.v1.RecordSubmissionRequest\x1a).shiptrip.kyc.v1.RecordSubmissionResponseB#Z!shiptrip/internal/kyc/kycpb;kycpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kyc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z!shiptrip/internal/kyc/kycpb;kycpb'
  _globals['_DOCUMENTTYPE']._serialized_start=339
  _globals['_DOCUMENTTYPE']._serialized_end=474
  _globals['_STATUS']._serialized_start=476
  _globals['_STATUS']._serialized_end=590
  _globals['_RECORDSUBMISSIONREQUEST']._serialized_start=31
  _globals['_RECORDSUBMISSIONREQUEST']._serialized_end=227
  _globals['_RECORDSUBMISSIONRESPONSE']._serialized_start=229
  _globals['_RECORDSUBMISSIONRESPONSE']._serialized_end=336
  _globals['_KYCSUBMISSIONSERVICE']._serialized_start=592
  _globals['_KYCSUBMISSIONSERVICE']._serialized_end=719
# @@protoc_insertion_point(module_scope)
