# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import kyc_pb2 as kyc__pb2  # patched: grpc_tools emits absolute import

GRPC_GENERATED_VERSION = '1.68.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in kyc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class KYCSubmissionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RecordSubmission = channel.unary_unary(
                '/shiptrip.kyc.v1.KYCSubmissionService/RecordSubmission',
                request_serializer=kyc__pb2.RecordSubmissionRequest.SerializeToString,
                response_deserializer=kyc__pb2.RecordSubmissionResponse.FromString,
                _registered_method=True)


class KYCSubmissionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def RecordSubmission(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KYCSubmissionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RecordSubmission': grpc.unary_unary_rpc_method_handler(
                    servicer.RecordSubmission,
                    request_deserializer=kyc__pb2.RecordSubmissionRequest.FromString,
                    response_serializer=kyc__pb2.RecordSubmissionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'shiptrip.kyc.v1.KYCSubmissionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('shiptrip.kyc.v1.KYCSubmissionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class KYCSubmissionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def RecordSubmission(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/shiptrip.kyc.v1.KYCSubmissionService/RecordSubmission',
            kyc__pb2.RecordSubmissionRequest.SerializeToString,
            kyc__pb2.RecordSubmissionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
