# Generated by Django 5.1.4 on 2026-05-09 01:13

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trips', '0002_seed_airports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParcelRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('delivery', 'Delivery'), ('product', 'Product')], db_index=True, max_length=12)),
                ('pickup_city', models.CharField(blank=True, default='', max_length=80)),
                ('delivery_city', models.CharField(blank=True, default='', max_length=80)),
                ('weight_kg', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('item_type', models.CharField(choices=[('documents', 'Documents'), ('small_box', 'Small box'), ('electronics', 'Electronics'), ('clothing', 'Clothing'), ('other', 'Other')], default='other', max_length=16)),
                ('description', models.TextField(blank=True, default='', max_length=2000)),
                ('deadline_at', models.DateTimeField(blank=True, help_text='Latest acceptable delivery time. Used by matching.', null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('matched', 'Matched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_to', to='trips.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcels_from', to='trips.airport')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcel_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'parcels_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('parcelrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parcels.parcelrequest')),
                ('base_amount_dzd', models.PositiveIntegerField(help_text='Proposed payout to traveler in DZD (commission added on Offer).', validators=[django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'db_table': 'parcels_delivery',
            },
            bases=('parcels.parcelrequest',),
        ),
        migrations.CreateModel(
            name='ProductRequest',
            fields=[
                ('parcelrequest_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='parcels.parcelrequest')),
                ('product_url', models.URLField(blank=True, default='', max_length=500)),
                ('store_name', models.CharField(blank=True, default='', max_length=120)),
                ('product_price_dzd', models.PositiveIntegerField(help_text='Item price in DZD; pricing engine derives commission.', validators=[django.core.validators.MinValueValidator(100)])),
            ],
            options={
                'db_table': 'parcels_product',
            },
            bases=('parcels.parcelrequest',),
        ),
        migrations.CreateModel(
            name='ParcelMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64)),
                ('object_key', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='image/jpeg', max_length=64)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='parcels.parcelrequest')),
            ],
            options={
                'db_table': 'parcels_media',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='parcelrequest',
            index=models.Index(fields=['origin', 'destination', 'status'], name='parcels_corridor_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelrequest',
            index=models.Index(fields=['sender', '-created_at'], name='parcels_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='parcelrequest',
            index=models.Index(fields=['kind', 'status'], name='parcels_kind_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelrequest',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='parcels_origin_neq_destination'),
        ),
        migrations.AddIndex(
            model_name='parcelmedia',
            index=models.Index(fields=['parcel', 'created_at'], name='parcels_media_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelmedia',
            constraint=models.UniqueConstraint(fields=('bucket', 'object_key'), name='parcels_media_unique_object'),
        ),
    ]
