# Generated by Django 5.1.4 on 2026-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_remove_location_locations_provider_place_uniq_and_more'),
        ('parcels', '0003_delivery_request_v1'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='deliveryrequest',
            constraint=models.CheckConstraint(condition=models.Q(('schema_version', 1), ('base_amount_dzd__isnull', True), _connector='OR'), name='parcels_delivery_v1_no_dzd'),
        ),
    ]
