# Generated by Django 5.1.4 on 2026-08-25 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0006_clarify_sender_proposed_reward'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelrequest',
            name='status',
            field=models.CharField(choices=[('awaiting_deposit', 'Awaiting posting deposit'), ('open', 'Open'), ('matched', 'Matched'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='open', max_length=16),
        ),
    ]
