# Generated by Django 5.1.4 on 2026-09-01 12:09

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_location_canonical_place"),
        ("parcels", "0007_alter_parcelrequest_status"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliveryrequest",
            name="parcels_delivery_schema_ver",
        ),
        migrations.RemoveConstraint(
            model_name="deliveryrequest",
            name="parcels_delivery_v1_required",
        ),
        migrations.RemoveConstraint(
            model_name="deliveryrequest",
            name="parcels_delivery_v1_safety",
        ),
        migrations.RemoveConstraint(
            model_name="deliveryrequest",
            name="parcels_delivery_v1_no_dzd",
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="delivery_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_requests_delivery",
                to="locations.place",
            ),
        ),
        migrations.AddField(
            model_name="deliveryrequest",
            name="pickup_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="delivery_requests_pickup",
                to="locations.place",
            ),
        ),
        migrations.AlterField(
            model_name="deliveryrequest",
            name="schema_version",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="1 is legacy airport/DZD, 2 is legacy V1 pins, 3 is canonical geography V1.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="deliveryrequest",
            index=models.Index(
                fields=["schema_version", "pickup_place", "delivery_place"],
                name="parcels_v1_place_route_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version__in", (1, 2, 3))),
                name="parcels_delivery_schema_ver",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("schema_version__in", (1, 2)),
                    models.Q(
                        ("schema_version", 3),
                        ("pickup_place__isnull", False),
                        ("delivery_place__isnull", False),
                        ("ready_window_start__isnull", False),
                        ("ready_window_end__isnull", False),
                        ("actual_weight_kg__isnull", False),
                        ("declared_value_eur_cents__isnull", False),
                        ("traveler_reward_eur_cents__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="parcels_delivery_v1_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("schema_version__in", (1, 2)),
                    models.Q(
                        ("schema_version", 3),
                        ("description_is_accurate", True),
                        ("item_is_legal", True),
                        ("no_prohibited_goods", True),
                        ("declared_value_is_accurate", True),
                        ("customs_responsibilities_understood", True),
                    ),
                    _connector="OR",
                ),
                name="parcels_delivery_v1_safety",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryrequest",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("schema_version", 1),
                    ("base_amount_dzd__isnull", True),
                    _connector="OR",
                ),
                name="parcels_delivery_v1_no_dzd",
            ),
        ),
    ]
