# Generated by Django 5.1.4 on 2026-09-03 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0008_remove_deliveryrequest_parcels_delivery_schema_ver_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelmedia',
            name='idempotency_key',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='parcelmedia',
            name='purpose',
            field=models.CharField(choices=[('item_photo', 'Item photo'), ('attachment', 'Attachment')], db_index=True, default='item_photo', max_length=16),
        ),
        migrations.AddField(
            model_name='parcelmedia',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, help_text='Who uploaded it. Required while the row is still unattached.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parcel_media', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='parcelmedia',
            name='parcel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media', to='parcels.parcelrequest'),
        ),
        migrations.AddIndex(
            model_name='parcelmedia',
            index=models.Index(fields=['uploaded_by', 'parcel'], name='parcels_media_staged_idx'),
        ),
        migrations.AddConstraint(
            model_name='parcelmedia',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('uploaded_by', 'idempotency_key'), name='parcels_media_unique_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='parcelmedia',
            constraint=models.CheckConstraint(condition=models.Q(('parcel__isnull', False), ('uploaded_by__isnull', False), _connector='OR'), name='parcels_media_owned'),
        ),
    ]
