# Generated by Django 5.1.4 on 2026-09-15 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parcels', '0009_phase8fb_staged_parcel_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryrequest',
            name='boost_eur_cents',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
