# Generated by Django 5.1.4 on 2026-05-07 23:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('iata', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=80)),
                ('name', models.CharField(max_length=120)),
                ('country', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'trips_airport',
                'ordering': ['country', 'city'],
                'indexes': [models.Index(fields=['country'], name='trips_airport_country_idx')],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_at', models.DateTimeField()),
                ('capacity_kg', models.PositiveSmallIntegerField(help_text='Total kg the traveler can carry for parcels.', validators=[django.core.validators.MinValueValidator(1)])),
                ('notes', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='active', max_length=16)),
                ('flight_number', models.CharField(blank=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_to', to='trips.airport')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips_from', to='trips.airport')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'trips_trip',
                'ordering': ['departure_at'],
            },
        ),
        migrations.CreateModel(
            name='FlightTrackingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captured_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(max_length=24)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude_m', models.IntegerField(blank=True, null=True)),
                ('speed_kph', models.IntegerField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_snapshots', to='trips.trip')),
            ],
            options={
                'db_table': 'trips_tracking_snapshot',
                'ordering': ['-captured_at'],
            },
        ),
        migrations.CreateModel(
            name='TripStopover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField()),
                ('arrives_at', models.DateTimeField(blank=True, null=True)),
                ('departs_at', models.DateTimeField(blank=True, null=True)),
                ('airport', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='trips.airport')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stopovers', to='trips.trip')),
            ],
            options={
                'db_table': 'trips_stopover',
                'ordering': ['trip', 'position'],
            },
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['origin', 'destination', 'departure_at'], name='trips_corridor_idx'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['traveler', '-departure_at'], name='trips_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='trip',
            constraint=models.CheckConstraint(condition=models.Q(('origin', models.F('destination')), _negated=True), name='trips_origin_neq_destination'),
        ),
        migrations.AddIndex(
            model_name='flighttrackingsnapshot',
            index=models.Index(fields=['trip', '-captured_at'], name='trips_track_trip_idx'),
        ),
        migrations.AddConstraint(
            model_name='tripstopover',
            constraint=models.UniqueConstraint(fields=('trip', 'position'), name='trips_stopover_unique_position'),
        ),
    ]
