# Generated by Django 5.1.4 on 2026-05-19 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_seed_airports'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bucket', models.CharField(max_length=64)),
                ('object_key', models.CharField(max_length=255)),
                ('content_type', models.CharField(default='image/jpeg', max_length=64)),
                ('bytes', models.PositiveIntegerField(default=0)),
                ('kind', models.CharField(default='ticket', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='trips.trip')),
            ],
            options={
                'db_table': 'trips_media',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['trip', 'created_at'], name='trips_media_idx')],
                'constraints': [models.UniqueConstraint(fields=('bucket', 'object_key'), name='trips_media_unique_object')],
            },
        ),
    ]
