# Generated by Django 5.1.4 on 2026-08-24

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0003_tripmedia"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Journey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_verification", "Pending verification"),
                            ("active", "Active"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "notes",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journeys_ending_here",
                        to="locations.location",
                    ),
                ),
                (
                    "legacy_trip",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="v1_journey",
                        to="trips.trip",
                    ),
                ),
                (
                    "start_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journeys_starting_here",
                        to="locations.location",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journeys",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trips_journey",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="JourneyLeg",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("position", models.PositiveSmallIntegerField()),
                (
                    "mode",
                    models.CharField(
                        choices=[("FLIGHT", "Flight"), ("DRIVE", "Drive")],
                        max_length=8,
                    ),
                ),
                ("depart_at", models.DateTimeField()),
                ("arrive_at", models.DateTimeField(blank=True, null=True)),
                (
                    "capacity_kg",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "distance_meters",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("route_polyline", models.TextField(blank=True, default="")),
                (
                    "allowed_detour_meters",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("route_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "flight_number",
                    models.CharField(blank=True, default="", max_length=16),
                ),
                (
                    "departure_airport_metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                (
                    "arrival_airport_metadata",
                    models.JSONField(blank=True, default=dict),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_legs_to",
                        to="locations.location",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="legs",
                        to="trips.journey",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="journey_legs_from",
                        to="locations.location",
                    ),
                ),
            ],
            options={
                "db_table": "trips_journey_leg",
                "ordering": ["journey", "position"],
            },
        ),
        migrations.CreateModel(
            name="JourneyLegProof",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bucket", models.CharField(max_length=64)),
                ("object_key", models.CharField(max_length=512)),
                (
                    "content_type",
                    models.CharField(default="image/jpeg", max_length=64),
                ),
                ("bytes", models.PositiveIntegerField(default=0)),
                ("kind", models.CharField(default="ticket", max_length=24)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "rejection_reason",
                    models.TextField(blank=True, default="", max_length=2000),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proofs",
                        to="trips.journeyleg",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reviewed_journey_leg_proofs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "trips_journey_leg_proof",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["traveler", "status", "-created_at"],
                name="journey_owner_status_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["start_location", "destination_location", "status"],
                name="journey_endpoints_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_location", models.F("destination_location")),
                    _negated=True,
                ),
                name="journey_distinct_endpoints",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyleg",
            index=models.Index(
                fields=["origin", "destination", "depart_at"],
                name="journey_leg_route_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="journeyleg",
            index=models.Index(
                fields=["mode", "depart_at"],
                name="journey_leg_mode_time_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.UniqueConstraint(
                fields=("journey", "position"),
                name="journey_leg_unique_position",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.CheckConstraint(
                condition=models.Q(("origin", models.F("destination")), _negated=True),
                name="journey_leg_distinct_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.CheckConstraint(
                condition=models.Q(("capacity_kg__gt", 0)),
                name="journey_leg_positive_capacity",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("arrive_at__isnull", True),
                    ("arrive_at__gt", models.F("depart_at")),
                    _connector="OR",
                ),
                name="journey_leg_arrival_after_departure",
            ),
        ),
        migrations.AddIndex(
            model_name="journeylegproof",
            index=models.Index(
                fields=["leg", "status", "-created_at"],
                name="journey_proof_review_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeylegproof",
            constraint=models.UniqueConstraint(
                fields=("bucket", "object_key"),
                name="journey_proof_unique_object",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeylegproof",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("rejection_reason", ""),
                        ("reviewed_at__isnull", True),
                        ("reviewer__isnull", True),
                        ("status", "pending"),
                    ),
                    models.Q(
                        ("rejection_reason", ""),
                        ("reviewed_at__isnull", False),
                        ("reviewer__isnull", False),
                        ("status", "approved"),
                    ),
                    models.Q(
                        ("reviewed_at__isnull", False),
                        ("reviewer__isnull", False),
                        ("status", "rejected"),
                        models.Q(("rejection_reason", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="journey_proof_review_consistent",
            ),
        ),
    ]
