# Generated by Django 5.1.4 on 2026-09-01 12:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0005_location_canonical_place"),
        ("trips", "0006_journey_status_published_index"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="journey",
            name="journey_distinct_endpoints",
        ),
        migrations.RemoveConstraint(
            model_name="journeyleg",
            name="journey_leg_distinct_endpoints",
        ),
        migrations.AddField(
            model_name="journey",
            name="destination_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_ending_at",
                to="locations.place",
            ),
        ),
        migrations.AddField(
            model_name="journey",
            name="schema_version",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="journey",
            name="start_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_starting_at",
                to="locations.place",
            ),
        ),
        migrations.AddField(
            model_name="journeyleg",
            name="destination_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_legs_ending",
                to="locations.place",
            ),
        ),
        migrations.AddField(
            model_name="journeyleg",
            name="origin_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_legs_originating",
                to="locations.place",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="destination_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_ending_here",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="journey",
            name="start_location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journeys_starting_here",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="journeyleg",
            name="destination",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_legs_to",
                to="locations.location",
            ),
        ),
        migrations.AlterField(
            model_name="journeyleg",
            name="origin",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="journey_legs_from",
                to="locations.location",
            ),
        ),
        migrations.AddIndex(
            model_name="journey",
            index=models.Index(
                fields=["start_place", "destination_place", "status"],
                name="journey_place_endpoints_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("start_location__isnull", True),
                        ("destination_location__isnull", True),
                        models.Q(
                            ("start_location", models.F("destination_location")),
                            _negated=True,
                        ),
                        _connector="OR",
                    ),
                    models.Q(
                        ("start_place__isnull", True),
                        ("destination_place__isnull", True),
                        models.Q(
                            ("start_place", models.F("destination_place")),
                            _negated=True,
                        ),
                        _connector="OR",
                    ),
                ),
                name="journey_distinct_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="journey",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destination_place__isnull", True),
                        ("schema_version", 1),
                        ("start_place__isnull", True),
                    ),
                    models.Q(
                        ("destination_place__isnull", False),
                        ("schema_version", 2),
                        ("start_place__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="journey_canonical_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("origin__isnull", True),
                        ("destination__isnull", True),
                        models.Q(("origin", models.F("destination")), _negated=True),
                        _connector="OR",
                    ),
                    models.Q(
                        ("origin_place__isnull", True),
                        ("destination_place__isnull", True),
                        models.Q(
                            ("origin_place", models.F("destination_place")),
                            _negated=True,
                        ),
                        _connector="OR",
                    ),
                ),
                name="journey_leg_distinct_endpoints",
            ),
        ),
        migrations.AddConstraint(
            model_name="journeyleg",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("destination_place__isnull", True),
                        ("origin_place__isnull", True),
                    ),
                    models.Q(
                        ("destination_place__isnull", False),
                        ("origin_place__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="journey_leg_canonical_endpoints",
            ),
        ),
    ]
