#!/usr/bin/env bash
# Generate a local CA plus per-service certificates for the KYC gRPC mTLS
# channel (CLAUDE.md §G5).
#
# WHY THIS EXISTS
# ---------------
# §G5 makes mTLS the production auth mode for Django <-> kyc-service gRPC, and
# `GRPC_AUTH_MODE=mtls` already fails the Go client's boot when the three cert
# paths are missing (internal/kyc/grpc_client.go:tlsCredentials). Until now
# there was no way to *produce* those certs, so mtls could not be exercised at
# all and dev stayed pinned to bearer.
#
# This script is the local/dev half of the pipeline. Production is meant to use
# cert-manager on K3s (§G5: "90-day cert lifetime; cert-manager auto-renews") —
# do NOT ship these files to a cluster. What they are for is proving the mTLS
# path works end to end before anyone wires cert-manager.
#
# WHAT IT PRODUCES (all under --out, default backend/certs/, git-ignored)
#   ca.pem / ca.key            the private CA both sides trust, and nothing else
#   server.pem / server.key    Django's gRPC server identity (runkycgrpc)
#   client.pem / client.key    kyc-service's client identity
#
# The CA is the only trust root: each side verifies its peer against ca.pem, so
# a certificate from any public CA is rejected. That is the point of §G5 —
# a static bearer token can be replayed by anything that reads it, whereas a
# client here must hold a key signed by this CA.
#
# USAGE
#   ./scripts/gen-mtls-certs.sh                    # writes backend/certs/
#   ./scripts/gen-mtls-certs.sh --out /tmp/certs   # elsewhere
#   ./scripts/gen-mtls-certs.sh --force            # overwrite existing certs
#
# Then in backend/.env:
#   GRPC_AUTH_MODE=mtls
#   GRPC_TLS_CA_CERT=/certs/ca.pem
#   GRPC_TLS_CLIENT_CERT=/certs/client.pem
#   GRPC_TLS_CLIENT_KEY=/certs/client.key
# (container paths — mount backend/certs/ into both services.)
#
# Requires only `openssl`. mkcert is the friendlier tool §G5 mentions, but it
# installs a CA into the system trust store, which is the wrong shape here:
# we want a CA trusted by exactly these two services and nothing else on the
# machine.
set -euo pipefail

OUT_DIR=""
FORCE=0
DAYS_CA=3650 # 10y — a dev CA you regenerate by deleting the directory
DAYS_LEAF=90 # matches the §G5 production lifetime, so expiry is exercised too

usage() {
	sed -n '2,45p' "$0" | sed 's|^# \{0,1\}||'
	exit "${1:-0}"
}

while [ $# -gt 0 ]; do
	case "$1" in
	--out)
		OUT_DIR="${2:?--out needs a path}"
		shift 2
		;;
	--force)
		FORCE=1
		shift
		;;
	-h | --help) usage 0 ;;
	*)
		echo "unknown argument: $1" >&2
		usage 1 >&2
		;;
	esac
done

cd "$(dirname "$0")/.."          # backend/services
REPO_BACKEND="$(cd .. && pwd)"   # backend/
OUT_DIR="${OUT_DIR:-$REPO_BACKEND/certs}"

if ! command -v openssl >/dev/null 2>&1; then
	echo "error: openssl is required but not on PATH" >&2
	exit 1
fi

# Refuse to silently clobber existing certs: overwriting the CA invalidates
# every cert already issued from it, which would break a running stack in a
# way that looks like an auth bug rather than a regenerated CA.
if [ -e "$OUT_DIR/ca.pem" ] && [ "$FORCE" -ne 1 ]; then
	echo "error: $OUT_DIR/ca.pem already exists."
	echo "Regenerating the CA invalidates every certificate issued from it."
	echo "Re-run with --force if that is what you want."
	exit 1
fi

mkdir -p "$OUT_DIR"
# Private keys live here. 0700 so a stray umask cannot make them world-readable.
chmod 700 "$OUT_DIR"

# Belt and braces on top of the root .gitignore's *.pem / *.key rules. Those
# cover the keys but NOT openssl's `ca.srl` serial file, and they only apply
# under this repo — a --out pointing elsewhere gets no protection at all.
# A self-ignoring directory travels with the certs wherever they are written.
cat >"$OUT_DIR/.gitignore" <<'IGNORE'
# Generated by services/scripts/gen-mtls-certs.sh — never commit any of it.
# A committed CA key is a committed backdoor: anyone holding it can mint a
# client cert this stack will trust.
*
IGNORE

echo "==> output: $OUT_DIR"

# ── CA ───────────────────────────────────────────────────────────────────────
echo "==> generating CA (${DAYS_CA}d)"
openssl req -x509 -newkey rsa:4096 -sha256 -nodes \
	-keyout "$OUT_DIR/ca.key" -out "$OUT_DIR/ca.pem" \
	-days "$DAYS_CA" \
	-subj "/CN=ShipTrip Dev gRPC CA/O=ShipTrip" \
	-addext "basicConstraints=critical,CA:TRUE" \
	-addext "keyUsage=critical,keyCertSign,cRLSign" \
	2>/dev/null

# issue <name> <cn> <extra-sans> <ext-key-usage>
#
# SANs matter more than CN here: Go's TLS stack ignores CN entirely and matches
# the dial name against the SAN list. The server cert therefore needs every name
# the client might dial it by — `django-grpc` inside compose, `localhost` from
# the host, `127.0.0.1` when dialling by IP. Miss one and the handshake fails
# with a certificate-name mismatch that reads like a config error.
issue() {
	local name="$1" cn="$2" sans="$3" eku="$4"
	echo "==> issuing $name (${DAYS_LEAF}d, EKU=$eku)"
	openssl req -newkey rsa:2048 -sha256 -nodes \
		-keyout "$OUT_DIR/$name.key" -out "$OUT_DIR/$name.csr" \
		-subj "/CN=$cn/O=ShipTrip" 2>/dev/null

	openssl x509 -req -sha256 \
		-in "$OUT_DIR/$name.csr" \
		-CA "$OUT_DIR/ca.pem" -CAkey "$OUT_DIR/ca.key" -CAcreateserial \
		-out "$OUT_DIR/$name.pem" -days "$DAYS_LEAF" \
		-extfile <(printf 'subjectAltName=%s\nextendedKeyUsage=%s\nkeyUsage=critical,digitalSignature,keyEncipherment\nbasicConstraints=critical,CA:FALSE\n' "$sans" "$eku") \
		2>/dev/null

	rm -f "$OUT_DIR/$name.csr"
	chmod 600 "$OUT_DIR/$name.key"
}

# Django's gRPC server. `django-grpc` is the compose service name the
# kyc-service dials (KYC_GRPC_TARGET=django-grpc:50051).
issue server django-grpc \
	"DNS:django-grpc,DNS:django,DNS:localhost,IP:127.0.0.1" \
	serverAuth

# kyc-service's client identity. clientAuth EKU is what lets Django's server
# verify it as a *client* rather than accepting any cert from the CA.
issue client kyc-service \
	"DNS:kyc-service,DNS:localhost,IP:127.0.0.1" \
	clientAuth

chmod 600 "$OUT_DIR/ca.key"

# ── verify, don't assume ─────────────────────────────────────────────────────
# A cert that exists is not a cert that validates. Check both leaves chain to
# the CA before claiming success — otherwise the first failure shows up as an
# opaque gRPC handshake error at service boot.
echo "==> verifying chain"
for leaf in server client; do
	if ! openssl verify -CAfile "$OUT_DIR/ca.pem" "$OUT_DIR/$leaf.pem" >/dev/null 2>&1; then
		echo "error: $leaf.pem does not verify against ca.pem" >&2
		exit 1
	fi
	echo "    $leaf.pem OK"
done

echo
echo "Done. Files in $OUT_DIR:"
ls -1 "$OUT_DIR"
cat <<EOF

Next steps
----------
1. These are DEV certs. *.pem and *.key are already git-ignored (root
   .gitignore) — keep it that way; a committed CA key is a committed backdoor.

2. Go client side is ready. In backend/.env:
     GRPC_AUTH_MODE=mtls
     GRPC_TLS_CA_CERT=/certs/ca.pem
     GRPC_TLS_CLIENT_CERT=/certs/client.pem
     GRPC_TLS_CLIENT_KEY=/certs/client.key
   and mount this directory into kyc-service (e.g. ./certs:/certs:ro).

3. BLOCKED on the Django side: runkycgrpc.py still has
     raise SystemExit("GRPC_AUTH_MODE=mtls is not yet wired (TODO §G5)")
   so there is nothing listening with TLS yet. Until that lands, keep dev on
   GRPC_AUTH_MODE=bearer. The server cert above is generated and waiting.
   Django needs: server.pem/server.key as its identity, ca.pem as the client
   trust root, and require-client-cert enabled.
EOF
