# Generated by Django 5.1.4 on 2026-05-11 22:06

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (V1)'), ('stripe', 'Stripe'), ('edahabia', 'Edahabia')], default='mock', max_length=12)),
                ('provider_intent_id', models.CharField(blank=True, default='', max_length=128)),
                ('amount_minor', models.PositiveIntegerField(help_text='Integer minor units. DZD: whole DZD. EUR: cents.', validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('status', models.CharField(choices=[('requires_payment_method', 'Requires payment method'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refund_pending', 'Refund pending'), ('refunded', 'Refunded')], db_index=True, default='requires_payment_method', max_length=24)),
                ('client_idempotency_key', models.CharField(blank=True, default='', max_length=64)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer', models.OneToOneField(help_text='Each accepted Offer has exactly one PaymentIntent.', on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='matching.offer')),
                ('payer', models.ForeignKey(help_text='The sender. Matches offer.match.sender_id.', on_delete=django.db.models.deletion.PROTECT, related_name='payments_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payments_intent',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('mock', 'Mock (V1)'), ('stripe', 'Stripe'), ('edahabia', 'Edahabia')], max_length=12)),
                ('provider_event_id', models.CharField(max_length=128)),
                ('kind', models.CharField(choices=[('intent_created', 'Intent created'), ('intent_processing', 'Intent processing'), ('intent_succeeded', 'Intent succeeded'), ('intent_failed', 'Intent failed'), ('intent_cancelled', 'Intent cancelled'), ('refund_created', 'Refund created'), ('refund_succeeded', 'Refund succeeded'), ('refund_failed', 'Refund failed')], max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'payments_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('provider', models.CharField(choices=[('mock', 'Mock (V1)'), ('stripe', 'Stripe'), ('edahabia', 'Edahabia')], max_length=12)),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=128)),
                ('reason', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='payments.paymentintent')),
            ],
            options={
                'db_table': 'payments_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['payer', '-created_at'], name='payments_payer_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['status'], name='payments_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentintent',
            index=models.Index(fields=['provider', 'status'], name='payments_provider_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_intent_id', ''), _negated=True), fields=('provider', 'provider_intent_id'), name='payments_unique_provider_intent'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['requires_payment_method', 'processing'])), fields=('offer',), name='payments_one_open_per_offer'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('client_idempotency_key', ''), _negated=True), fields=('payer', 'client_idempotency_key'), name='payments_unique_client_key_per_payer'),
        ),
        migrations.AddIndex(
            model_name='paymentevent',
            index=models.Index(fields=['intent', '-created_at'], name='payments_event_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='payments_event_unique'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['intent', '-created_at'], name='payments_refund_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id', ''), _negated=True), fields=('provider', 'provider_refund_id'), name='payments_refund_unique_provider_id'),
        ),
    ]
