# Generated by Django 5.1.4 on 2026-05-11 22:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('matching', '0002_alter_matchevent_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', 'Pickup (sender → traveler)'), ('delivery', 'Delivery (recipient → traveler)')], db_index=True, max_length=16)),
                ('code_hash', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('locked', 'Locked (too many wrong attempts)'), ('rotated', 'Rotated (replaced by a newer code)')], db_index=True, default='active', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('issued_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_codes_issued', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_codes', to='matching.match')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_codes_redeemed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'verification_handover_code',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('match', 'kind'), name='handover_one_active_per_match_kind')],
            },
        ),
    ]
