# Generated by Django 5.1.4 on 2026-09-14 12:09

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chat_message_cursor_index'),
        ('matching', '0007_offer_economics_version_required'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='client_message_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='chatmessage',
            constraint=models.UniqueConstraint(fields=('match', 'sender', 'client_message_id'), name='chat_sender_client_message_uniq'),
        ),
    ]
