# Generated by Django 5.1.4 on 2026-05-30 23:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(db_index=True, max_length=64)),
                ('event_id', models.CharField(db_index=True, max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification',
                'indexes': [models.Index(fields=['recipient', '-created_at'], name='notif_recipient_recent_idx'), models.Index(fields=['recipient', 'read_at'], name='notif_recipient_unread_idx')],
                'constraints': [models.UniqueConstraint(fields=('recipient', 'event_id'), name='notif_recipient_event_uniq')],
            },
        ),
    ]
