# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealrecipient_deal_agreed_pickup_at_and_more'),
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutboundMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('recipient_delivery_code', 'Delivery code for the recipient'), ('pickup_confirmed', 'Pickup confirmed'), ('delivery_code_released', 'Delivery code available to the sender'), ('delivery_confirmed', 'Delivery confirmed'), ('protection_ending', 'Protection window ending'), ('protection_ended', 'Protection window ended'), ('dispute_opened', 'Dispute opened'), ('dispute_resolved', 'Dispute resolved'), ('payout_status', 'Payout status'), ('deal_cancelled', 'Deal cancelled'), ('rating_available', 'Rating available')], db_index=True, max_length=32)),
                ('channel', models.CharField(default='email', max_length=16)),
                ('to_email', models.EmailField(max_length=254)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('secret_ref', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('dispatched', 'Dispatched to the transport'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=10)),
                ('next_attempt_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('transport_event_id', models.CharField(blank=True, default='', max_length=64)),
                ('dispatched_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to='deals.deal')),
                ('recipient_user', models.ForeignKey(blank=True, help_text='Null for a parcel recipient, who needs no ShipTrip account.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='outbound_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_outbound_message',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='outbound_due_idx'), models.Index(fields=['deal', 'kind'], name='outbound_deal_kind_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('status', 'pending'), ('status', 'cancelled'), ('dispatched_at__isnull', False), ('status', 'failed'), _connector='OR'), name='outbound_dispatched_requires_timestamp')],
            },
        ),
    ]
