# Generated by Django 5.1.4 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_outboundmessage_kind_outboundsecret'),
    ]

    operations = [
        migrations.AddField(
            model_name='outboundmessage',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], db_index=True, default='en', help_text='Locale snapshot captured when the logical email obligation is created; later profile changes do not alter queued mail.', max_length=2),
        ),
    ]
