# Generated by Django 5.1.4 on 2026-09-04 20:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_outboundmessage_language'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('messages_enabled', models.BooleanField(default=True)),
                ('marketplace_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preference', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_preference',
            },
        ),
        migrations.CreateModel(
            name='PushDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('fcm', 'Firebase Cloud Messaging')], default='fcm', max_length=8)),
                ('platform', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS')], max_length=8)),
                ('installation_id', models.UUIDField(unique=True)),
                ('token', models.TextField()),
                ('token_fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('last_seen_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_success_at', models.DateTimeField(blank=True, null=True)),
                ('last_failure_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'notification_push_device',
                'indexes': [models.Index(fields=['user', 'active'], name='push_device_user_active_idx')],
            },
        ),
    ]
