# Generated by Django 5.1.4 on 2026-08-25 08:14

import django.core.validators
import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0005_seed_phase3_payment_settings'),
        ('deals', '0003_allocation_expiry'),
        ('parcels', '0007_alter_parcelrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GuestPaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(help_text='SHA-256 hex digest of the token. The plaintext is never stored.', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, default='', help_text="Owner's own note, e.g. 'Dad'. Never shown to the guest.", max_length=80)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_payment_links_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_guest_payment_link',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('customer_payment', 'Customer payment'), ('deposit_credit', 'Posting-deposit credit'), ('deal_funding', 'Deal funding'), ('refund', 'Refund'), ('payout', 'Payout'), ('correction', 'Correction / reversal')], db_index=True, max_length=24)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reverses', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='finance.ledgertransaction')),
            ],
            options={
                'db_table': 'finance_ledger_transaction',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('purpose', models.CharField(choices=[('posting_deposit', 'Posting deposit'), ('deal_balance', 'Deal balance'), ('boost', 'Boost')], db_index=True, max_length=20)),
                ('currency', models.CharField(default='EUR', editable=False, help_text='Canonical marketplace currency. Always EUR.', max_length=3)),
                ('amount_eur_cents', models.PositiveBigIntegerField(help_text='The gross obligation in canonical EUR cents.', validators=[django.core.validators.MinValueValidator(1)])),
                ('credited_eur_cents', models.PositiveBigIntegerField(default=0, help_text='Discharged without new cash, e.g. a posting-deposit credit.')),
                ('paid_eur_cents', models.PositiveBigIntegerField(default=0, help_text='Captured through succeeded provider attempts.')),
                ('refunded_eur_cents', models.PositiveBigIntegerField(default=0, help_text='Refunded out of captured funds. Never exceeds paid_eur_cents.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('refund_pending', 'Refund pending'), ('partially_refunded', 'Partially refunded'), ('refunded', 'Refunded'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('boost_reference', models.CharField(blank=True, default='', max_length=64)),
                ('terms_snapshot', models.JSONField(blank=True, default=dict, help_text='Immutable policy/economics inputs used to compute this amount.')),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_settings_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='core.businesssettingsversion')),
                ('credit_source', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credited_into', to='finance.paymentorder')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='deals.deal')),
                ('delivery_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='parcels.deliveryrequest')),
                ('owner', models.ForeignKey(help_text='The user who owes this obligation. Always the sender in V1.', on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payment_order',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('chargily', 'Chargily'), ('mock', 'Mock (tests/local only)')], db_index=True, max_length=16)),
                ('guest_email', models.EmailField(blank=True, default='', help_text='Provider-reported guest payer email. Never a ShipTrip identity.', max_length=254)),
                ('amount_eur_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('payment_currency', models.CharField(max_length=3)),
                ('provider_amount_minor', models.PositiveBigIntegerField()),
                ('provider_amount_exponent', models.PositiveSmallIntegerField(default=2, help_text='Minor units per major unit as 10**exponent. EUR=2, DZD=0.')),
                ('fx_rate_micros', models.PositiveBigIntegerField(blank=True, help_text='Immutable EUR->payment-currency rate x 1_000_000. Null for an EUR-native attempt.', null=True)),
                ('fx_source', models.CharField(blank=True, default='', max_length=64)),
                ('fx_snapshot_at', models.DateTimeField(blank=True, null=True)),
                ('provider_session_id', models.CharField(blank=True, default='', max_length=255)),
                ('provider_payment_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(help_text='What we sent the provider. Stable across our own retries.', max_length=128)),
                ('checkout_url', models.URLField(blank=True, default='', max_length=1024)),
                ('status', models.CharField(choices=[('created', 'Created'), ('checkout_pending', 'Checkout pending'), ('processing', 'Processing'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], db_index=True, default='created', max_length=20)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('is_unapplied', models.BooleanField(default=False, help_text='Succeeded but not applied to the order; awaiting refund.')),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fx_settings_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='core.businesssettingsversion')),
                ('guest_link', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='finance.guestpaymentlink')),
                ('payer', models.ForeignKey(blank=True, help_text="Null when a guest paid on the owner's behalf.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='finance.paymentorder')),
            ],
            options={
                'db_table': 'finance_payment_attempt',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='guestpaymentlink',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='guest_links', to='finance.paymentorder'),
        ),
        migrations.CreateModel(
            name='PaymentProviderEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('chargily', 'Chargily'), ('mock', 'Mock (tests/local only)')], max_length=16)),
                ('provider_event_id', models.CharField(max_length=255)),
                ('event_type', models.CharField(blank=True, default='', max_length=128)),
                ('signature_verified', models.BooleanField(default=False)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processing_result', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('ignored', 'Ignored'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('processing_note', models.CharField(blank=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='finance.paymentattempt')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='provider_events', to='finance.paymentorder')),
            ],
            options={
                'db_table': 'finance_provider_event',
                'ordering': ['-received_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentRefund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eur_cents', models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('provider', models.CharField(choices=[('stripe', 'Stripe'), ('chargily', 'Chargily'), ('mock', 'Mock (tests/local only)')], max_length=16)),
                ('provider_refund_id', models.CharField(blank=True, default='', max_length=255)),
                ('idempotency_key', models.CharField(max_length=128, unique=True)),
                ('reason', models.CharField(choices=[('deposit_expiry', 'Request expired unmatched'), ('sender_cancelled', 'Sender cancelled before acceptance'), ('unapplied_payment', 'Payment could not be applied'), ('deal_cancelled', 'Deal cancelled before funding'), ('admin', 'Administrative refund')], max_length=24)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, default='pending', max_length=12)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('failure_message', models.CharField(blank=True, default='', max_length=255)),
                ('succeeded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.paymentattempt')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='finance.paymentorder')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Null when the platform raised the refund automatically.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payment_refund',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eur_cents', models.PositiveBigIntegerField(help_text='Canonical traveler obligation in EUR cents.', validators=[django.core.validators.MinValueValidator(1)])),
                ('method', models.CharField(choices=[('undecided', 'Undecided'), ('stripe_transfer', 'Stripe transfer'), ('manual', 'Manual settlement')], default='undecided', max_length=20)),
                ('status', models.CharField(choices=[('not_eligible', 'Not eligible (awaiting Phase 4 gate)'), ('eligible', 'Eligible'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='not_eligible', max_length=16)),
                ('eligible_at', models.DateTimeField(blank=True, null=True)),
                ('scheduled_for', models.DateTimeField(blank=True, null=True)),
                ('payout_currency', models.CharField(blank=True, default='', max_length=3)),
                ('payout_amount_minor', models.PositiveBigIntegerField(blank=True, null=True)),
                ('payout_amount_exponent', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fx_rate_micros', models.PositiveBigIntegerField(blank=True, null=True)),
                ('provider_payout_id', models.CharField(blank=True, default='', max_length=255)),
                ('reference', models.CharField(blank=True, default='', help_text='Bank/transfer reference for a manual settlement.', max_length=128)),
                ('receipt_url', models.URLField(blank=True, default='', max_length=1024)),
                ('notes', models.TextField(blank=True, default='', max_length=2000)),
                ('failure_code', models.CharField(blank=True, default='', max_length=64)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payouts_settled', to=settings.AUTH_USER_MODEL)),
                ('deal', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='payout', to='deals.deal')),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_payout',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(choices=[('provider_clearing', 'Provider clearing (asset)'), ('sender_deposit', 'Posting deposit held (liability)'), ('deal_funds', 'Deal funds held (liability)'), ('traveler_payable', 'Traveler payable (liability)'), ('platform_commission', 'Platform commission (revenue)')], max_length=24)),
                ('amount_eur_cents', models.BigIntegerField(help_text='Signed. + increases an asset, - increases a liability/revenue.')),
                ('currency', models.CharField(default='EUR', editable=False, max_length=3)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='deals.deal')),
                ('user', models.ForeignKey(blank=True, help_text='Whose sub-ledger this leg belongs to, when it is per-user.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='finance.ledgertransaction')),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.paymentattempt')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.paymentorder')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.paymentrefund')),
                ('payout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='finance.payout')),
            ],
            options={
                'db_table': 'finance_ledger_entry',
                'ordering': ['transaction_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ScheduledJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=160, unique=True)),
                ('kind', models.CharField(choices=[('deposit_expiry_refund', 'Deposit expiry refund'), ('payment_grace_release', 'Payment grace release'), ('attempt_expiry', 'Checkout attempt expiry'), ('provider_reconcile', 'Provider reconciliation'), ('payout_release_check', 'Payout release check')], db_index=True, max_length=32)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('run_at', models.DateTimeField(db_index=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=12)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=8)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('locked_by', models.CharField(blank=True, default='', max_length=64)),
                ('last_error', models.CharField(blank=True, default='', max_length=500)),
                ('last_result', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'finance_scheduled_job',
                'ordering': ['run_at', 'id'],
                'indexes': [models.Index(fields=['status', 'run_at'], name='fin_job_due_idx'), models.Index(fields=['kind', 'status'], name='fin_job_kind_idx')],
            },
        ),
        migrations.CreateModel(
            name='TravelerPayoutMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('stripe_connect', 'Stripe connected account'), ('manual', 'Manual settlement')], max_length=20)),
                ('provider_account_id', models.CharField(blank=True, default='', max_length=255)),
                ('country_code', models.CharField(blank=True, default='', max_length=2)),
                ('payouts_enabled', models.BooleanField(default=False)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('capability_checked_at', models.DateTimeField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_methods', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'finance_traveler_payout_method',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ledgertransaction',
            index=models.Index(fields=['kind', '-created_at'], name='fin_ltx_kind_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['owner', '-created_at'], name='fin_order_owner_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['status', 'purpose'], name='fin_order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['delivery_request', 'purpose'], name='fin_order_request_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentorder',
            index=models.Index(fields=['deal', 'purpose'], name='fin_order_deal_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'EUR')), name='fin_order_currency_eur'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gt', 0)), name='fin_order_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gte', django.db.models.expressions.CombinedExpression(models.F('credited_eur_cents'), '+', models.F('paid_eur_cents')))), name='fin_order_no_overcollection'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(('refunded_eur_cents__lte', models.F('paid_eur_cents'))), name='fin_order_refund_within_capture'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('delivery_request__isnull', False), ('purpose', 'posting_deposit')), models.Q(('deal__isnull', False), ('purpose', 'deal_balance')), models.Q(('delivery_request__isnull', False), ('purpose', 'boost')), _connector='OR'), name='fin_order_reference_required'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('purpose', 'posting_deposit'), models.Q(('status', 'cancelled'), _negated=True)), fields=('delivery_request',), name='fin_order_one_live_deposit_per_request'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('purpose', 'deal_balance'), models.Q(('status', 'cancelled'), _negated=True)), fields=('deal',), name='fin_order_one_live_balance_per_deal'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['order', '-created_at'], name='fin_attempt_order_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['provider', 'status'], name='fin_attempt_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentattempt',
            index=models.Index(fields=['status', 'expires_at'], name='fin_attempt_expiry_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_session_id', ''), _negated=True), fields=('provider', 'provider_session_id'), name='fin_attempt_unique_provider_session'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payment_id', ''), _negated=True), fields=('provider', 'provider_payment_id'), name='fin_attempt_unique_provider_payment'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(fields=('provider', 'idempotency_key'), name='fin_attempt_unique_idempotency'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['created', 'checkout_pending', 'processing'])), fields=('order',), name='fin_attempt_one_open_per_order'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gt', 0)), name='fin_attempt_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='paymentattempt',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('fx_rate_micros__isnull', True), ('payment_currency', 'EUR')), models.Q(models.Q(('payment_currency', 'EUR'), _negated=True), ('fx_rate_micros__isnull', False)), _connector='OR'), name='fin_attempt_fx_required_for_conversion'),
        ),
        migrations.AddIndex(
            model_name='guestpaymentlink',
            index=models.Index(fields=['order', '-created_at'], name='fin_guest_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='guestpaymentlink',
            constraint=models.UniqueConstraint(condition=models.Q(('revoked_at__isnull', True), ('consumed_at__isnull', True)), fields=('order',), name='fin_guest_one_live_link_per_order'),
        ),
        migrations.AddIndex(
            model_name='paymentproviderevent',
            index=models.Index(fields=['provider', '-received_at'], name='fin_event_provider_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentproviderevent',
            index=models.Index(fields=['attempt', '-received_at'], name='fin_event_att_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentproviderevent',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_event_id'), name='fin_event_unique_provider_event'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['order', '-created_at'], name='fin_refund_order_idx'),
        ),
        migrations.AddIndex(
            model_name='paymentrefund',
            index=models.Index(fields=['status'], name='fin_refund_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_refund_id', ''), _negated=True), fields=('provider', 'provider_refund_id'), name='fin_refund_unique_provider_refund'),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gt', 0)), name='fin_refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['traveler', '-created_at'], name='fin_payout_trav_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['status', 'scheduled_for'], name='fin_payout_queue_idx'),
        ),
        migrations.AddIndex(
            model_name='payout',
            index=models.Index(fields=['method', 'status'], name='fin_payout_method_idx'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gt', 0)), name='fin_payout_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), models.Q(('provider_payout_id', ''), _negated=True), models.Q(('admin_actor__isnull', False), models.Q(('reference', ''), _negated=True)), _connector='OR'), name='fin_payout_paid_requires_evidence'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='fin_payout_paid_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='payout',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status__in', ['eligible', 'scheduled', 'processing', 'paid']), _negated=True), ('eligible_at__isnull', False), _connector='OR'), name='fin_payout_release_requires_eligibility'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['account', 'user'], name='fin_ledger_acct_user_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['deal', 'account'], name='fin_ledger_deal_idx'),
        ),
        migrations.AddIndex(
            model_name='ledgerentry',
            index=models.Index(fields=['order'], name='fin_ledger_order_idx'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'EUR')), name='fin_ledger_currency_eur'),
        ),
        migrations.AddConstraint(
            model_name='ledgerentry',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents', 0), _negated=True), name='fin_ledger_amount_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='travelerpayoutmethod',
            constraint=models.UniqueConstraint(fields=('traveler', 'method'), name='fin_payout_method_unique_per_traveler'),
        ),
        migrations.AddConstraint(
            model_name='travelerpayoutmethod',
            constraint=models.UniqueConstraint(condition=models.Q(('is_default', True)), fields=('traveler',), name='fin_payout_method_one_default'),
        ),
    ]
