# Generated by Django 5.1.4 on 2026-08-25 12:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentrefund',
            name='settled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_refunds_settled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='settlement_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='paymentrefund',
            name='settlement_reference',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddConstraint(
            model_name='paymentrefund',
            constraint=models.CheckConstraint(condition=models.Q(('settled_by__isnull', True), models.Q(('settlement_reference', ''), _negated=True), _connector='OR'), name='fin_refund_manual_requires_reference'),
        ),
    ]
