# Generated by Django 5.1.4 on 2026-08-25 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_financial_recovery_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentrefund',
            name='reason',
            field=models.CharField(choices=[('deposit_expiry', 'Request expired unmatched'), ('sender_cancelled', 'Sender cancelled before acceptance'), ('unapplied_payment', 'Payment could not be applied'), ('deal_cancelled', 'Deal cancelled before funding'), ('admin', 'Administrative refund'), ('deal_cancelled_funded', 'Deal cancelled after funding'), ('dispute_resolution', 'Dispute resolution'), ('no_show', 'Verified no-show'), ('boost_unusable', 'Boost paid but no longer usable')], max_length=24),
        ),
        migrations.AlterField(
            model_name='payout',
            name='status',
            field=models.CharField(choices=[('not_eligible', 'Not eligible (protection window open)'), ('eligible', 'Eligible'), ('scheduled', 'Scheduled'), ('processing', 'Processing'), ('paid', 'Paid'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('frozen', 'Frozen by a dispute')], db_index=True, default='not_eligible', max_length=16),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='kind',
            field=models.CharField(choices=[('deposit_expiry_refund', 'Deposit expiry refund'), ('payment_grace_release', 'Payment grace release'), ('attempt_expiry', 'Checkout attempt expiry'), ('provider_reconcile', 'Provider reconciliation'), ('provider_event_process', 'Provider event processing'), ('refund_reconcile', 'Refund reconciliation'), ('payout_release_check', 'Payout release check'), ('delivery_code_release', 'Delivery code release'), ('protection_expiry', 'Protection window expiry'), ('rating_reveal', 'Rating reveal'), ('boost_expiry', 'Boost expiry'), ('outbound_message', 'Outbound message dispatch')], db_index=True, max_length=32),
        ),
    ]
