# Generated by Django 5.1.4 on 2026-08-26 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_alter_paymentrefund_reason_alter_payout_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='payout',
            options={'ordering': ['-created_at'], 'permissions': [('settle_payout', 'Can record that a traveler has actually been paid')]},
        ),
    ]
