# Generated by Django 5.1.4 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_payout_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpaymentlink',
            name='communication_language',
            field=models.CharField(choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='en', help_text='Language snapshotted when the owner creates the guest payment link.', max_length=2),
        ),
    ]
