# Generated by Django 5.1.4 on 2026-09-05 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0006_guestpaymentlink_communication_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ledgertransaction",
            name="kind",
            field=models.CharField(
                choices=[
                    ("customer_payment", "Customer payment"),
                    ("deposit_credit", "Posting-deposit credit"),
                    ("deal_funding", "Deal funding"),
                    ("boost_binding", "Boost funds binding"),
                    ("boost_allocation", "Boost allocation"),
                    ("refund", "Refund"),
                    ("payout", "Payout"),
                    ("correction", "Correction / reversal"),
                ],
                db_index=True,
                max_length=24,
            ),
        ),
    ]
