# Generated by Django 5.1.4 on 2026-09-07 12:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


def classify_existing_jobs(apps, schema_editor):
    """Classify the exhaustions proven by the Phase 8F-G1 live inventory.

    Synthetic QA recipients are cancelled, not deleted, so enabling email later
    cannot send stale test traffic.  Any real recipient keeps its durable
    obligation and is re-armed under the new non-burning deferred semantics.
    """

    del schema_editor
    ScheduledJob = apps.get_model("finance", "ScheduledJob")
    OutboundMessage = apps.get_model("notifications", "OutboundMessage")
    AdminAuditLog = apps.get_model("admin_panel", "AdminAuditLog")
    ScheduledJob.objects.filter(attempts__gt=0, last_attempt_at__isnull=True).update(
        last_attempt_at=models.F("updated_at")
    )
    # Phase 8F-G1's production inventory proved every matching failed outbound
    # job had exhausted solely because intentional email disablement was
    # misclassified as retryable.  Match the exact known signature; unrelated
    # SMTP/provider failures remain untouched for an operator to review.
    candidates = ScheduledJob.objects.filter(
        kind="outbound_message",
        status="failed",
        last_error__icontains="transactional email is disabled",
    ).order_by("pk")
    now = timezone.now()
    synthetic_addresses = {"send@t.com", "t@t.com"}
    for job in candidates.iterator():
        message_id = (job.payload or {}).get("message_id")
        message = OutboundMessage.objects.filter(pk=message_id).first()
        recipient = (message.to_email if message else "").strip().lower()
        is_synthetic = recipient in synthetic_addresses or recipient.endswith(
            ".invalid"
        )
        if message is not None and is_synthetic and message.status == "pending":
            OutboundMessage.objects.filter(pk=message.pk, status="pending").update(
                status="cancelled",
                next_attempt_at=None,
                last_error="Cancelled as synthetic QA traffic during Phase 8F-G1 cleanup.",
                updated_at=now,
            )
            ScheduledJob.objects.filter(pk=job.pk).update(
                last_error_code="email_disabled",
                resolution="dismissed",
                resolved_at=now,
                resolved_by=None,
                resolution_reason=(
                    "Phase 8F-G1 cleanup: synthetic QA recipient; durable message cancelled."
                ),
                updated_at=now,
            )
            AdminAuditLog.objects.create(
                actor=None,
                action="scheduled_job.migration_dismissed",
                target_type="finance.scheduledjob",
                target_id=str(job.pk),
                reason=(
                    "Phase 8F-G1 cleanup: synthetic QA recipient; durable message cancelled."
                ),
                reference="phase8fg1",
                before={"status": "failed", "resolution": ""},
                after={"status": "failed", "resolution": "dismissed"},
                metadata={"message_id": message.pk, "automated": True},
            )
            continue

        # Attempts are deliberately retained.  The next worker pass records a
        # deferred state without incrementing them while the kill switch stays
        # off, and the OutboundMessage remains the durable obligation.
        ScheduledJob.objects.filter(pk=job.pk).update(
            status="pending",
            run_at=now,
            locked_at=None,
            locked_by="",
            last_error_code="",
            last_error="",
            last_result="deferred:email_disabled",
            completed_at=None,
            resolution="",
            resolved_at=None,
            resolved_by=None,
            resolution_reason="",
            updated_at=now,
        )
        AdminAuditLog.objects.create(
            actor=None,
            action="scheduled_job.migration_rearmed",
            target_type="finance.scheduledjob",
            target_id=str(job.pk),
            reason=(
                "Phase 8F-G1 recovery: real durable message retained while email is disabled."
            ),
            reference="phase8fg1",
            before={"status": "failed", "attempts": job.attempts},
            after={"status": "pending", "attempts": job.attempts},
            metadata={"message_id": message_id, "automated": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_alter_adminauditlog_options"),
        ("finance", "0007_alter_ledgertransaction_kind"),
        ("notifications", "0005_notificationpreference_pushdevice"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentattempt",
            name="operational_resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="",
                help_text="Operator attention state only. It never changes the provider or financial outcome recorded above.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="operational_resolution_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="operational_resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="operational_resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_payment_attempt_alerts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="last_attempt_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="last_error_code",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="resolution",
            field=models.CharField(
                blank=True,
                choices=[
                    ("resolved", "Resolved"),
                    ("dismissed", "Dismissed"),
                    ("superseded", "Superseded"),
                ],
                db_index=True,
                default="",
                help_text="Operational resolution only; execution history is retained.",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="resolution_reason",
            field=models.CharField(blank=True, default="", max_length=500),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="resolved_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="scheduledjob",
            name="resolved_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="resolved_scheduled_jobs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.RunPython(classify_existing_jobs, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="paymentattempt",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        operational_resolution="",
                        operational_resolved_at__isnull=True,
                        operational_resolved_by__isnull=True,
                        operational_resolution_reason="",
                    )
                    | (
                        ~models.Q(operational_resolution="")
                        & models.Q(operational_resolved_at__isnull=False)
                        & ~models.Q(operational_resolution_reason="")
                    )
                ),
                name="fin_attempt_resolution_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="scheduledjob",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(
                        resolution="",
                        resolved_at__isnull=True,
                        resolved_by__isnull=True,
                        resolution_reason="",
                    )
                    | (
                        ~models.Q(resolution="")
                        & models.Q(resolved_at__isnull=False)
                        & ~models.Q(resolution_reason="")
                        & models.Q(status="failed")
                    )
                ),
                name="fin_job_resolution_complete",
            ),
        ),
    ]
