# Generated by Django 5.1.4 on 2026-09-07 19:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "__first__"),
        ("core", "0009_seed_boost_economics"),
        ("deals", "0007_dealtermssnapshot_boost_amount_minor_and_more"),
        ("finance", "0008_paymentattempt_operational_resolution_and_more"),
        ("kyc", "0002_add_idempotency_key"),
    ]

    operations = [
        migrations.CreateModel(
            name="DzdPayoutProfileRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("first_name_encrypted", models.TextField()),
                ("last_name_encrypted", models.TextField()),
                ("ccp_number_encrypted", models.TextField()),
                ("ccp_key_encrypted", models.TextField()),
                ("nip_encrypted", models.TextField()),
                ("ccp_last_four", models.CharField(max_length=4)),
                ("nip_last_four", models.CharField(max_length=4)),
                ("account_fingerprint", models.CharField(db_index=True, max_length=64)),
                ("status", models.CharField(default="pending_review", max_length=24)),
                (
                    "submitted_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "finance_dzd_profile_revision",
            },
        ),
        migrations.CreateModel(
            name="FinanceHold",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("dispute", "dispute"),
                            ("provider_dispute", "provider_dispute"),
                            ("fraud", "fraud"),
                            ("refund", "refund"),
                            ("compliance", "compliance"),
                            ("treasury", "treasury"),
                            ("manual", "manual"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("source_reference", models.CharField(max_length=160)),
                (
                    "amount_exposure_eur_cents",
                    models.PositiveBigIntegerField(null=True),
                ),
                ("opened_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("cleared_at", models.DateTimeField(null=True)),
                ("generation", models.PositiveBigIntegerField(default=1)),
            ],
            options={
                "db_table": "finance_hold",
            },
        ),
        migrations.CreateModel(
            name="PayoutAmountRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("revision", models.PositiveIntegerField()),
                ("previous_amount_eur_cents", models.PositiveBigIntegerField()),
                ("amount_eur_cents", models.PositiveBigIntegerField()),
                (
                    "previous_settlement_amount_minor",
                    models.PositiveBigIntegerField(null=True),
                ),
                ("settlement_amount_minor", models.PositiveBigIntegerField(null=True)),
                ("fx_rate_micros", models.PositiveBigIntegerField(null=True)),
                ("settlement_reference", models.CharField(max_length=160)),
                ("reason_code", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_amount_revision",
            },
        ),
        migrations.CreateModel(
            name="PayoutAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("amount_eur_cents", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                ("rail", models.CharField(max_length=20)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "Prepared"),
                            ("dispatch_committed", "Dispatch committed"),
                            ("unknown", "Unknown"),
                            ("accepted", "Accepted"),
                            ("sent", "Sent"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("returned", "Returned"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="prepared",
                        max_length=24,
                    ),
                ),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("fencing_generation", models.PositiveBigIntegerField(default=0)),
                ("committed_at", models.DateTimeField(null=True)),
                ("result_at", models.DateTimeField(null=True)),
                ("failure_code", models.CharField(blank=True, max_length=64)),
                ("provider_request_id", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_attempt",
            },
        ),
        migrations.CreateModel(
            name="PayoutEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                ("previous_state", models.CharField(blank=True, max_length=16)),
                ("new_state", models.CharField(max_length=16)),
                ("reason_code", models.CharField(max_length=64)),
                ("source", models.CharField(default="system", max_length=32)),
                (
                    "occurred_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("recorded_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_event",
            },
        ),
        migrations.CreateModel(
            name="PayoutEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "purpose",
                    models.CharField(
                        choices=[
                            ("account_document", "account_document"),
                            ("transfer_receipt", "transfer_receipt"),
                            ("return_evidence", "return_evidence"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "logical_store",
                    models.CharField(default="payout", editable=False, max_length=24),
                ),
                ("object_key", models.CharField(blank=True, max_length=512)),
                ("encryption_key_id", models.CharField(blank=True, max_length=64)),
                ("digest", models.CharField(blank=True, max_length=64)),
                ("mime_type", models.CharField(blank=True, max_length=64)),
                ("size_bytes", models.PositiveBigIntegerField(null=True)),
                (
                    "upload_state",
                    models.CharField(default="unconfigured", max_length=16),
                ),
                (
                    "retention_class",
                    models.CharField(default="payout_financial", max_length=32),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_evidence",
            },
        ),
        migrations.CreateModel(
            name="PayoutFundingAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("allocation_key", models.CharField(max_length=160, unique=True)),
                ("source_charge_id", models.CharField(blank=True, max_length=255)),
                ("provider", models.CharField(max_length=16)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("purpose", models.CharField(max_length=24)),
                ("currency", models.CharField(max_length=3)),
                ("amount_eur_cents", models.PositiveBigIntegerField()),
                ("unavailable_reason", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_funding_allocation",
            },
        ),
        migrations.CreateModel(
            name="PayoutIdentityAttestation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("given_name_encrypted", models.TextField()),
                ("family_name_encrypted", models.TextField()),
                ("aliases_encrypted", models.TextField()),
                ("script_metadata", models.CharField(blank=True, max_length=64)),
                ("policy_version", models.CharField(max_length=64)),
                (
                    "attested_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "db_table": "finance_payout_identity_attestation",
            },
        ),
        migrations.CreateModel(
            name="PayoutIdentityReviewAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(null=True)),
            ],
            options={
                "db_table": "finance_payout_identity_review_assignment",
            },
        ),
        migrations.CreateModel(
            name="PayoutIdentityRevocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_identity_revocation",
            },
        ),
        migrations.CreateModel(
            name="PayoutInstructionAmendment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("confirmed_at", models.DateTimeField()),
                ("reason_code", models.CharField(max_length=64)),
                ("expected_state", models.CharField(max_length=16)),
                ("expected_state_version", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_instruction_amendment",
            },
        ),
        migrations.CreateModel(
            name="PayoutMethodVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("rail", models.CharField(max_length=20)),
                ("currency", models.CharField(max_length=3)),
                ("country", models.CharField(blank=True, max_length=2)),
                ("policy_version", models.CharField(max_length=64)),
                ("consent_at", models.DateTimeField()),
                ("source", models.CharField(default="traveler", max_length=32)),
                ("content_hash", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_method_version",
            },
        ),
        migrations.CreateModel(
            name="PayoutProfileReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("approved", "approved"),
                            ("rejected", "rejected"),
                            ("needs_attention", "needs_attention"),
                        ],
                        max_length=24,
                    ),
                ),
                ("reason_code", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_profile_review",
            },
        ),
        migrations.CreateModel(
            name="PayoutProviderOperation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("account_create", "account_create"),
                            ("transfer_create", "transfer_create"),
                            ("bank_payout_create", "bank_payout_create"),
                            ("transfer_reverse", "transfer_reverse"),
                            ("bank_payout_cancel", "bank_payout_cancel"),
                        ],
                        max_length=24,
                    ),
                ),
                ("account_scope", models.CharField(max_length=255)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("sequence", models.PositiveIntegerField()),
                ("idempotency_key", models.CharField(max_length=160, unique=True)),
                ("request_fingerprint", models.CharField(max_length=64)),
                ("provider_object_id", models.CharField(blank=True, max_length=255)),
                ("provider_request_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("prepared", "prepared"),
                            ("committed", "committed"),
                            ("unknown", "unknown"),
                            ("accepted", "accepted"),
                            ("failed", "failed"),
                            ("reconciled", "reconciled"),
                        ],
                        default="prepared",
                        max_length=16,
                    ),
                ),
                ("amount_minor", models.PositiveBigIntegerField(null=True)),
                ("currency", models.CharField(blank=True, max_length=3)),
                ("retry_after", models.DateTimeField(null=True)),
                ("first_request_at", models.DateTimeField(null=True)),
                ("last_request_at", models.DateTimeField(null=True)),
                ("response_code", models.PositiveSmallIntegerField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_payout_provider_operation",
            },
        ),
        migrations.CreateModel(
            name="ProviderDispute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("provider", models.CharField(max_length=16)),
                ("platform_id", models.CharField(max_length=255)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("provider_object_id", models.CharField(max_length=255)),
                ("source_charge_id", models.CharField(blank=True, max_length=255)),
                ("amount_minor", models.PositiveBigIntegerField()),
                ("currency", models.CharField(max_length=3)),
                (
                    "canonical_amount_eur_cents",
                    models.PositiveBigIntegerField(null=True),
                ),
                ("status", models.CharField(max_length=32)),
                (
                    "funds_withdrawn_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "funds_reinstated_reference",
                    models.CharField(blank=True, max_length=255),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_provider_dispute",
            },
        ),
        migrations.CreateModel(
            name="StripePayoutAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("platform_id", models.CharField(max_length=255)),
                ("provider_account_id", models.CharField(max_length=255)),
                (
                    "provider_mode",
                    models.CharField(
                        choices=[
                            ("test", "Test"),
                            ("live", "Live"),
                            ("legacy_unknown", "Legacy unknown"),
                        ],
                        max_length=16,
                    ),
                ),
                ("declared_country", models.CharField(max_length=2)),
                ("verified_country", models.CharField(blank=True, max_length=2)),
                (
                    "creation_operation_key",
                    models.CharField(max_length=160, unique=True),
                ),
                ("status", models.CharField(default="setup_required", max_length=24)),
                ("active", models.BooleanField(default=True)),
                (
                    "transfers_status",
                    models.CharField(default="unrequested", max_length=24),
                ),
                ("payouts_enabled", models.BooleanField(default=False)),
                ("details_submitted", models.BooleanField(default=False)),
                ("requirement_codes", models.JSONField(default=list)),
                ("disabled_reason", models.CharField(blank=True, max_length=64)),
                ("external_account_id", models.CharField(blank=True, max_length=255)),
                ("eur_bank_present", models.BooleanField(default=False)),
                ("readiness_checked_at", models.DateTimeField(blank=True, null=True)),
                ("readiness_generation", models.PositiveBigIntegerField(default=0)),
                (
                    "payout_schedule_interval",
                    models.CharField(blank=True, max_length=16),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "finance_stripe_payout_account",
            },
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="mode_evidence",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="provider_charge_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentattempt",
            name="provider_mode",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("live", "Live"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="block_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payout",
            name="eligibility_basis",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payout",
            name="eligibility_decision_reference",
            field=models.CharField(blank=True, default="", max_length=160),
        ),
        migrations.AddField(
            model_name="payout",
            name="funded_amount_eur_cents",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="funding_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funded_payouts",
                to="finance.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="funding_provider_snapshot",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="payout",
            name="fx_settings_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.businesssettingsversion",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="fx_snapshot_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="fx_source",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payout",
            name="fx_source_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_fx_snapshots",
                to="finance.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="legacy_classification",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payout",
            name="next_action_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="original_settlement_amount_minor",
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="provider_mode",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("live", "Live"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="public_reference",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="rounding_policy",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="payout",
            name="routing_policy_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payout",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="settled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="settlement_basis",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="payout",
            name="snapshot_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payout",
            name="snapshot_version",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="payout",
            name="state_version",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="public_reference",
            field=models.UUIDField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="revision",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="status",
            field=models.CharField(
                choices=[
                    ("setup_required", "Setup required"),
                    ("pending_review", "Pending review"),
                    ("ready", "Ready"),
                    ("needs_attention", "Needs attention"),
                    ("unavailable", "Unavailable"),
                    ("disabled", "Disabled"),
                ],
                default="setup_required",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="status_reason",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AlterField(
            model_name="payout",
            name="amount_eur_cents",
            field=models.PositiveBigIntegerField(
                help_text="Canonical traveler obligation in EUR cents.",
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="payout",
            name="status",
            field=models.CharField(
                choices=[
                    ("not_eligible", "Not eligible (protection window open)"),
                    ("blocked", "Blocked"),
                    ("sent", "Sent"),
                    ("eligible", "Eligible"),
                    ("scheduled", "Scheduled"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("failed", "Failed"),
                    ("cancelled", "Cancelled"),
                    ("frozen", "Frozen by a dispute"),
                ],
                db_index=True,
                default="not_eligible",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="dzdpayoutprofilerevision",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="dzd_revisions",
                to="finance.travelerpayoutmethod",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="dzd_profile_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.dzdpayoutprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="cleared_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_holds_cleared",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_holds",
                to="deals.deal",
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="opened_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_holds_opened",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holds",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="source_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="finance_holds",
                to="finance.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="payoutamountrevision",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutamountrevision",
            name="fx_settings_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="core.businesssettingsversion",
            ),
        ),
        migrations.AddField(
            model_name="payoutamountrevision",
            name="ledger_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.ledgertransaction",
            ),
        ),
        migrations.AddField(
            model_name="payoutamountrevision",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amount_revisions",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="payoutattempt",
            name="amount_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutamountrevision",
            ),
        ),
        migrations.AddField(
            model_name="payoutattempt",
            name="operator",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutattempt",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attempts",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="payoutevent",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutevent",
            name="ledger_transaction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.ledgertransaction",
            ),
        ),
        migrations.AddField(
            model_name="payoutevent",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="payoutevidence",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payoutevent",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutevidence",
            ),
        ),
        migrations.AddField(
            model_name="dzdpayoutprofilerevision",
            name="evidence",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutevidence",
            ),
        ),
        migrations.AddField(
            model_name="payoutfundingallocation",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutattempt",
            ),
        ),
        migrations.AddField(
            model_name="payoutfundingallocation",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="funding_allocations",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="payoutfundingallocation",
            name="source_attempt",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_allocations",
                to="finance.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityattestation",
            name="attested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_attestations_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityattestation",
            name="kyc_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kyc.kycsubmission"
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityattestation",
            name="supersedes",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="successors",
                to="finance.payoutidentityattestation",
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityattestation",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_identity_attestations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="dzdpayoutprofilerevision",
            name="identity_attestation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutidentityattestation",
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityreviewassignment",
            name="assigned_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_identity_assignments_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityreviewassignment",
            name="kyc_submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="kyc.kycsubmission"
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityreviewassignment",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="assigned_payout_identity_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityreviewassignment",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_identity_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityrevocation",
            name="actor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payoutidentityrevocation",
            name="attestation",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="revocation",
                to="finance.payoutidentityattestation",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstructionamendment",
            name="payout",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instruction_amendments",
                to="finance.payout",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstructionamendment",
            name="reviewed_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_amendment_reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutinstructionamendment",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payout_confirmations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutmethodversion",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="payoutmethodversion",
            name="dzd_profile_revision",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.dzdpayoutprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="payoutmethodversion",
            name="method",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="versions",
                to="finance.travelerpayoutmethod",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstructionamendment",
            name="new_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amendments_to",
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="payoutinstructionamendment",
            name="old_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="amendments_from",
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="payoutattempt",
            name="instruction_version",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="active_instruction_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="active_payouts",
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="method_version",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="initial_payouts",
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="travelerpayoutmethod",
            name="current_version",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="current_for",
                to="finance.payoutmethodversion",
            ),
        ),
        migrations.AddField(
            model_name="payoutprofilereview",
            name="identity_attestation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutidentityattestation",
            ),
        ),
        migrations.AddField(
            model_name="payoutprofilereview",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviews",
                to="finance.dzdpayoutprofilerevision",
            ),
        ),
        migrations.AddField(
            model_name="payoutprofilereview",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payoutprovideroperation",
            name="attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="operations",
                to="finance.payoutattempt",
            ),
        ),
        migrations.AddField(
            model_name="payoutprovideroperation",
            name="method",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.travelerpayoutmethod",
            ),
        ),
        migrations.AddField(
            model_name="payoutevent",
            name="operation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.payoutprovideroperation",
            ),
        ),
        migrations.AddField(
            model_name="providerdispute",
            name="source_attempt",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.paymentattempt",
            ),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="traveler",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="payoutmethodversion",
            name="stripe_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.stripepayoutaccount",
            ),
        ),
        migrations.AddField(
            model_name="financehold",
            name="account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="holds",
                to="finance.stripepayoutaccount",
            ),
        ),
        migrations.AddField(
            model_name="payout",
            name="stripe_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="finance.stripepayoutaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="financehold",
            index=models.Index(
                fields=["payout", "cleared_at"], name="fin_hold_active_payout"
            ),
        ),
    ]
