# Generated by Django 5.1.4 on 2026-09-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0009_dzdpayoutprofilerevision_financehold_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ledgertransaction",
            name="provider_mode",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("live", "Live"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="paymentproviderevent",
            name="api_version",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="paymentproviderevent",
            name="endpoint_scope",
            field=models.CharField(default="platform", max_length=24),
        ),
        migrations.AddField(
            model_name="paymentproviderevent",
            name="provider_account_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentproviderevent",
            name="provider_mode",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("live", "Live"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                max_length=16,
            ),
        ),
    ]
