# Generated by Django 5.1.4 on 2026-09-07 19:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0010_ledgertransaction_provider_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentrefund",
            name="provider_mode",
            field=models.CharField(
                choices=[
                    ("test", "Test"),
                    ("live", "Live"),
                    ("legacy_unknown", "Legacy unknown"),
                ],
                default="legacy_unknown",
                max_length=16,
            ),
        ),
    ]
