# Generated by Django 5.1.4 on 2026-09-07 19:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0012_payout_legacy_classification"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payout",
            name="public_reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="travelerpayoutmethod",
            name="public_reference",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.RemoveConstraint(
            model_name="payout",
            name="fin_payout_amount_positive",
        ),
        migrations.RemoveConstraint(
            model_name="payout",
            name="fin_payout_release_requires_eligibility",
        ),
        migrations.AddConstraint(
            model_name="travelerpayoutmethod",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("currency", ""),
                        ("current_version__isnull", True),
                        ("enabled", False),
                    ),
                    models.Q(("currency", "DZD"), ("method", "manual")),
                    models.Q(("currency", "EUR"), ("method", "stripe_connect")),
                    _connector="OR",
                ),
                name="fin_payout_method_pairing",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_eur_cents__gt", 0),
                    models.Q(
                        ("amount_eur_cents", 0),
                        ("snapshot_version__gt", 0),
                        ("status", "cancelled"),
                        models.Q(("eligibility_decision_reference", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="fin_payout_amount_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_version", 0),
                    models.Q(
                        ("funded_amount_eur_cents__gt", 0),
                        ("funded_amount_eur_cents__isnull", False),
                        ("snapshot_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fin_payout_funded_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_version", 0),
                    models.Q(
                        ("method", "manual"),
                        ("payout_amount_exponent", 0),
                        ("payout_currency", "DZD"),
                        ("stripe_account__isnull", True),
                    ),
                    models.Q(
                        ("dzd_profile_revision__isnull", True),
                        ("fx_rate_micros__isnull", True),
                        ("fx_settings_version__isnull", True),
                        ("fx_source_attempt__isnull", True),
                        ("method", "stripe_transfer"),
                        ("payout_amount_exponent", 2),
                        ("payout_currency", "EUR"),
                    ),
                    models.Q(
                        ("block_reason", "payout_preference_required"),
                        ("method", "undecided"),
                        ("payout_currency", ""),
                    ),
                    _connector="OR",
                ),
                name="fin_payout_snapshot_pairing",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("snapshot_version", 0),
                    models.Q(("payout_currency", "DZD"), _negated=True),
                    models.Q(
                        ("fx_rate_micros__gt", 0),
                        ("fx_rate_micros__isnull", False),
                        ("fx_settings_version__isnull", False),
                        ("fx_snapshot_at__isnull", False),
                        ("payout_amount_minor__isnull", False),
                    ),
                    models.Q(
                        ("block_reason", "fx_snapshot_missing"),
                        ("fx_rate_micros__isnull", True),
                        ("payout_amount_minor__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="fin_payout_dzd_fx_snapshot",
            ),
        ),
        migrations.AddConstraint(
            model_name="payout",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        (
                            "status__in",
                            ["eligible", "scheduled", "processing", "sent", "paid"],
                        ),
                        _negated=True,
                    ),
                    ("eligible_at__isnull", False),
                    _connector="OR",
                ),
                name="fin_payout_release_requires_eligibility",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutamountrevision",
            constraint=models.UniqueConstraint(
                fields=("payout", "revision"), name="fin_amount_revision_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutamountrevision",
            constraint=models.UniqueConstraint(
                fields=("payout", "settlement_reference"),
                name="fin_amount_revision_decision",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutevidence",
            constraint=models.CheckConstraint(
                condition=models.Q(("logical_store", "payout")),
                name="fin_payout_evidence_store",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutfundingallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur_cents__gt", 0)),
                name="fin_payout_allocation_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="dzdpayoutprofilerevision",
            constraint=models.UniqueConstraint(
                fields=("method", "sequence"), name="fin_dzd_profile_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutinstructionamendment",
            constraint=models.UniqueConstraint(
                fields=("payout", "sequence"), name="fin_instruction_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.UniqueConstraint(
                fields=("payout", "sequence"), name="fin_payout_attempt_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["dispatch_committed", "unknown", "accepted", "sent"],
                    )
                ),
                fields=("payout",),
                name="fin_payout_one_committed_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur_cents__gt", 0)),
                name="fin_payout_attempt_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("currency", "DZD"), ("rail", "manual")),
                    models.Q(("currency", "EUR"), ("rail", "stripe_transfer")),
                    _connector="OR",
                ),
                name="fin_payout_attempt_pairing",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_mode__in", ["test", "live"])),
                name="fin_payout_attempt_known_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutprovideroperation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("attempt__isnull", False), ("method__isnull", True)),
                    models.Q(
                        ("attempt__isnull", True),
                        ("kind", "account_create"),
                        ("method__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fin_payout_operation_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutprovideroperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("provider_object_id", ""), _negated=True),
                fields=("kind", "account_scope", "provider_mode", "provider_object_id"),
                name="fin_payout_operation_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutprovideroperation",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_mode__in", ["test", "live"])),
                name="fin_payout_operation_known_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutevent",
            constraint=models.UniqueConstraint(
                fields=("payout", "sequence"), name="fin_payout_event_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="providerdispute",
            constraint=models.UniqueConstraint(
                fields=(
                    "provider",
                    "platform_id",
                    "provider_mode",
                    "provider_object_id",
                ),
                name="fin_provider_dispute_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripepayoutaccount",
            constraint=models.UniqueConstraint(
                fields=("platform_id", "provider_mode", "provider_account_id"),
                name="fin_stripe_account_identity",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripepayoutaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True)),
                fields=("traveler", "platform_id", "provider_mode"),
                name="fin_stripe_one_active_account",
            ),
        ),
        migrations.AddConstraint(
            model_name="stripepayoutaccount",
            constraint=models.CheckConstraint(
                condition=models.Q(("provider_mode__in", ["test", "live"])),
                name="fin_stripe_account_known_mode",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutmethodversion",
            constraint=models.UniqueConstraint(
                fields=("method", "sequence"), name="fin_method_version_sequence"
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutmethodversion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("currency", "DZD"),
                        ("rail", "manual"),
                        ("stripe_account__isnull", True),
                    ),
                    models.Q(
                        ("currency", "EUR"),
                        ("dzd_profile_revision__isnull", True),
                        ("rail", "stripe_transfer"),
                    ),
                    _connector="OR",
                ),
                name="fin_method_version_pairing",
            ),
        ),
        migrations.AddConstraint(
            model_name="financehold",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("account__isnull", True),
                        ("deal__isnull", False),
                        ("payout__isnull", True),
                        ("source_attempt__isnull", True),
                    ),
                    models.Q(
                        ("account__isnull", True),
                        ("deal__isnull", True),
                        ("payout__isnull", False),
                        ("source_attempt__isnull", True),
                    ),
                    models.Q(
                        ("account__isnull", False),
                        ("deal__isnull", True),
                        ("payout__isnull", True),
                        ("source_attempt__isnull", True),
                    ),
                    models.Q(
                        ("account__isnull", True),
                        ("deal__isnull", True),
                        ("payout__isnull", True),
                        ("source_attempt__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="fin_hold_exactly_one_scope",
            ),
        ),
    ]
