# Generated by Django 5.1.4 on 2026-09-07 19:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0014_payout_history_guards"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PayoutInstructionConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_reference",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("expected_state_version", models.PositiveBigIntegerField()),
                (
                    "confirmed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "new_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="finance.payoutmethodversion",
                    ),
                ),
                (
                    "payout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="instruction_confirmations",
                        to="finance.payout",
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "finance_payout_instruction_confirmation",
            },
        ),
    ]
