# Generated by Django 5.1.4 on 2026-09-07 19:29

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0015_payoutinstructionconfirmation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="payoutattempt",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "prepared")),
                fields=("payout",),
                name="fin_payout_one_prepared_attempt",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutprovideroperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("attempt__isnull", False)),
                fields=("attempt", "sequence"),
                name="fin_payout_operation_sequence",
            ),
        ),
        migrations.AddConstraint(
            model_name="payoutprovideroperation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("method__isnull", False)),
                fields=("method", "sequence"),
                name="fin_account_operation_sequence",
            ),
        ),
    ]
