# Generated by Django 5.1.4 on 2026-09-08 01:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0018_quarantine_unpaid_legacy_payouts"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentproviderevent",
            name="object_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="paymentproviderevent",
            name="object_type",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="controller_summary",
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="default_currency",
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="past_due_codes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="pending_verification_codes",
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="requirements_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stripepayoutaccount",
            name="status_reason",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddIndex(
            model_name="paymentproviderevent",
            index=models.Index(
                fields=["endpoint_scope", "provider_account_id", "-received_at"],
                name="fin_event_scope_idx",
            ),
        ),
    ]
