# Generated by Django 5.1.4 on 2026-09-08 23:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_phase8fh2_connect_projections'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='amount_reversed_minor',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='balance_transaction_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='destination_payment_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='failure_code',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='funding_allocation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.payoutfundingallocation'),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='last_observed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='observation_generation',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='provider_object_status',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='reconciled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ledgerentry',
            name='account',
            field=models.CharField(choices=[('provider_clearing', 'Provider clearing (asset)'), ('sender_deposit', 'Posting deposit held (liability)'), ('deal_funds', 'Deal funds held (liability)'), ('traveler_payable', 'Traveler payable (liability)'), ('platform_commission', 'Platform commission (revenue)'), ('connect_funds', 'Connected account funds (asset)'), ('payout_in_transit', 'Bank payout in transit (asset)')], max_length=24),
        ),
        migrations.AlterField(
            model_name='scheduledjob',
            name='kind',
            field=models.CharField(choices=[('deposit_expiry_refund', 'Deposit expiry refund'), ('payment_grace_release', 'Payment grace release'), ('attempt_expiry', 'Checkout attempt expiry'), ('provider_reconcile', 'Provider reconciliation'), ('provider_event_process', 'Provider event processing'), ('refund_reconcile', 'Refund reconciliation'), ('payout_release_check', 'Payout release check'), ('delivery_code_release', 'Delivery code release'), ('protection_expiry', 'Protection window expiry'), ('rating_reveal', 'Rating reveal'), ('boost_expiry', 'Boost expiry'), ('outbound_message', 'Outbound message dispatch'), ('payout_execute', 'Payout execution'), ('payout_reconcile', 'Payout reconciliation'), ('payout_account_refresh', 'Payout account refresh'), ('payout_sweep', 'Payout sweep')], db_index=True, max_length=32),
        ),
        migrations.CreateModel(
            name='PayoutFundingRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason_code', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('allocation', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='release', to='finance.payoutfundingallocation')),
            ],
            options={
                'db_table': 'finance_payout_funding_release',
            },
        ),
        migrations.CreateModel(
            name='StripeDisbursement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('provider_mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live'), ('legacy_unknown', 'Legacy unknown')], max_length=16)),
                ('currency', models.CharField(default='EUR', max_length=3)),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('method', models.CharField(default='standard', max_length=16)),
                ('external_account_id', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('committed', 'Dispatch committed'), ('unknown', 'Unknown'), ('pending', 'Pending at provider'), ('in_transit', 'In transit'), ('paid', 'Paid'), ('failed', 'Failed'), ('canceled', 'Canceled'), ('returned', 'Returned after paid')], default='planned', max_length=16)),
                ('provider_payout_id', models.CharField(blank=True, max_length=255)),
                ('balance_transaction_id', models.CharField(blank=True, max_length=255)),
                ('failure_balance_transaction_id', models.CharField(blank=True, max_length=255)),
                ('failure_code', models.CharField(blank=True, max_length=64)),
                ('arrival_estimate', models.DateTimeField(blank=True, null=True)),
                ('observation_generation', models.PositiveBigIntegerField(default=0)),
                ('last_observed_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('returned_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursements', to='finance.stripepayoutaccount')),
            ],
            options={
                'db_table': 'finance_stripe_disbursement',
            },
        ),
        migrations.AddField(
            model_name='payoutprovideroperation',
            name='disbursement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='operations', to='finance.stripedisbursement'),
        ),
        migrations.CreateModel(
            name='StripeDisbursementAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_eur_cents', models.PositiveBigIntegerField()),
                ('active', models.BooleanField(default=True)),
                ('released_reason', models.CharField(blank=True, max_length=64)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_allocations', to='finance.payoutattempt')),
                ('disbursement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='allocations', to='finance.stripedisbursement')),
                ('payout', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='disbursement_allocations', to='finance.payout')),
            ],
            options={
                'db_table': 'finance_stripe_disbursement_allocation',
            },
        ),
        migrations.AddIndex(
            model_name='stripedisbursement',
            index=models.Index(fields=['status', 'created_at'], name='fin_disb_status_idx'),
        ),
        migrations.AddIndex(
            model_name='stripedisbursement',
            index=models.Index(fields=['account', '-created_at'], name='fin_disb_account_idx'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursement',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_payout_id', ''), _negated=True), fields=('account', 'provider_mode', 'provider_payout_id'), name='fin_disbursement_provider_identity'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursement',
            constraint=models.CheckConstraint(condition=models.Q(('amount_minor__gt', 0)), name='fin_disbursement_positive'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursement',
            constraint=models.CheckConstraint(condition=models.Q(('currency', 'EUR'), ('method', 'standard')), name='fin_disbursement_rail'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursement',
            constraint=models.CheckConstraint(condition=models.Q(('provider_mode__in', ['test', 'live'])), name='fin_disbursement_known_mode'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'paid'), _negated=True), ('paid_at__isnull', False), _connector='OR'), name='fin_disbursement_paid_requires_timestamp'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursementallocation',
            constraint=models.UniqueConstraint(fields=('disbursement', 'payout'), name='fin_disbursement_allocation_unique'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursementallocation',
            constraint=models.UniqueConstraint(condition=models.Q(('active', True)), fields=('payout',), name='fin_payout_one_active_disbursement'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursementallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount_eur_cents__gt', 0)), name='fin_disbursement_allocation_positive'),
        ),
        migrations.AddConstraint(
            model_name='stripedisbursementallocation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active', True), ('released_at__isnull', True), ('released_reason', '')), models.Q(('active', False), ('released_at__isnull', False)), _connector='OR'), name='fin_disbursement_allocation_release_complete'),
        ),
    ]
