# Generated by Django 5.1.4 on 2026-09-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_phase8fh4_manual_guards'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledjob',
            name='kind',
            field=models.CharField(choices=[('deposit_expiry_refund', 'Deposit expiry refund'), ('payment_grace_release', 'Payment grace release'), ('attempt_expiry', 'Checkout attempt expiry'), ('provider_reconcile', 'Provider reconciliation'), ('provider_event_process', 'Provider event processing'), ('refund_reconcile', 'Refund reconciliation'), ('payout_release_check', 'Payout release check'), ('delivery_code_release', 'Delivery code release'), ('protection_expiry', 'Protection window expiry'), ('rating_reveal', 'Rating reveal'), ('boost_expiry', 'Boost expiry'), ('outbound_message', 'Outbound message dispatch'), ('notification_dispatch', 'Notification dispatch'), ('payout_execute', 'Payout execution'), ('payout_reconcile', 'Payout reconciliation'), ('payout_account_refresh', 'Payout account refresh'), ('payout_sweep', 'Payout sweep')], db_index=True, max_length=32),
        ),
    ]
