# Generated by Django 5.1.4 on 2026-09-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0025_alter_scheduledjob_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='guestpaymentlink',
            name='token_seed',
            field=models.CharField(blank=True, default='', help_text="Random input the owner's token is re-derived from with an application key. Useless without that key; empty on links issued before J7C, which cannot be shown again.", max_length=64),
        ),
    ]
