# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('deals', '0004_dealrecipient_deal_agreed_pickup_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealHandoverCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', 'Pickup (sender to traveler)'), ('delivery', 'Delivery (recipient to traveler)')], db_index=True, max_length=16)),
                ('status', models.CharField(choices=[('buffered', 'Buffered (safety window open)'), ('active', 'Active'), ('used', 'Used'), ('locked', 'Locked (attempt budget exhausted)'), ('superseded', 'Superseded by a rotation'), ('cancelled', 'Cancelled with the deal')], db_index=True, default='active', max_length=16)),
                ('code_hash', models.CharField(max_length=64)),
                ('sealed_code', models.TextField()),
                ('code_length', models.PositiveSmallIntegerField()),
                ('available_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('lockout_count', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('superseded_at', models.DateTimeField(blank=True, null=True)),
                ('rotation', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_codes', to='deals.deal')),
                ('issued_to', models.ForeignKey(help_text='Always the sender. The traveler is never issued a code.', on_delete=django.db.models.deletion.PROTECT, related_name='deal_handover_codes_issued', to=settings.AUTH_USER_MODEL)),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_handover_codes_redeemed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'handover_deal_code',
                'ordering': ['deal_id', 'kind', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pickup', 'Pickup (sender to traveler)'), ('delivery', 'Delivery (recipient to traveler)')], max_length=16)),
                ('result', models.CharField(choices=[('succeeded', 'Succeeded'), ('mismatch', 'Wrong code'), ('not_available', 'No submittable code'), ('locked', 'Locked out'), ('rate_limited', 'Rate limited'), ('not_authorized', 'Not authorized'), ('wrong_state', 'Deal not in a submittable state')], db_index=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_attempts', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='handover.dealhandovercode')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_attempts', to='deals.deal')),
            ],
            options={
                'db_table': 'handover_attempt',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='HandoverCodeAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('sender_reveal', 'Sender viewed the code'), ('recipient_notification', 'Rendered into the recipient notification')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the platform rendered a notification.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='handover_code_accesses', to=settings.AUTH_USER_MODEL)),
                ('code', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='accesses', to='handover.dealhandovercode')),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='handover_code_accesses', to='deals.deal')),
            ],
            options={
                'db_table': 'handover_code_access',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='dealhandovercode',
            index=models.Index(fields=['deal', 'kind', 'status'], name='handover_lookup_idx'),
        ),
        migrations.AddIndex(
            model_name='dealhandovercode',
            index=models.Index(fields=['status', 'available_at'], name='handover_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='dealhandovercode',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['buffered', 'active'])), fields=('deal', 'kind'), name='handover_one_live_code_per_kind'),
        ),
        migrations.AddConstraint(
            model_name='dealhandovercode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('code_hash', ''), _negated=True), models.Q(('sealed_code', ''), _negated=True)), name='handover_code_material_present'),
        ),
        migrations.AddConstraint(
            model_name='dealhandovercode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'used'), _negated=True), models.Q(('used_at__isnull', False), ('used_by__isnull', False)), _connector='OR'), name='handover_used_requires_actor'),
        ),
        migrations.AddConstraint(
            model_name='dealhandovercode',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'buffered'), _negated=True), ('available_at__isnull', False), _connector='OR'), name='handover_buffered_requires_available_at'),
        ),
        migrations.AddIndex(
            model_name='handoverattempt',
            index=models.Index(fields=['deal', 'kind', '-created_at'], name='handover_att_window_idx'),
        ),
        migrations.AddIndex(
            model_name='handoverattempt',
            index=models.Index(fields=['actor', '-created_at'], name='handover_att_actor_idx'),
        ),
        migrations.AddIndex(
            model_name='handovercodeaccess',
            index=models.Index(fields=['deal', '-created_at'], name='handover_access_idx'),
        ),
    ]
