# Generated by Django 5.1.4 on 2026-05-11 22:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KycSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], max_length=24)),
                ('front_image_key', models.CharField(max_length=512)),
                ('back_image_key', models.CharField(blank=True, default='', max_length=512)),
                ('selfie_image_key', models.CharField(blank=True, default='', max_length=512)),
                ('status', models.CharField(choices=[('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('rejection_reason', models.TextField(blank=True, default='', max_length=2000)),
                ('reviewed_by_id', models.BigIntegerField(blank=True, help_text='ID of the reviewer (operator user). Loose FK; no cascade.', null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kyc_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'kyc_submission',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='kyc_user_latest_idx'), models.Index(fields=['status'], name='kyc_status_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('user', 'document_type'), name='kyc_one_approved_per_user_doctype')],
            },
        ),
    ]
