# Generated by hand on 2026-05-16 for kyc idempotency_key.
#
# The Go kyc-service multipart endpoint takes a Flutter-generated
# idempotency_key (32-char UUIDv4 hex) and forwards it to Django via
# RecordSubmission gRPC. Without a UNIQUE column to hold it, retries
# would create duplicate kyc_submission rows on flaky mobile networks.
#
# Contract: backend/contracts/grpc/kyc.proto RecordSubmissionRequest.
#
# Reversible. No data migration: kyc_submission has no rows pre-MVP
# (the Go API isn't wired into the gateway yet). If you're applying
# this in an environment with existing rows, abort and write a
# data-backfill step first — every row needs a unique key and the
# only source of truth for that is the client that submitted it.

from django.db import migrations, models


def assert_empty(apps, schema_editor):
    KycSubmission = apps.get_model("kyc", "KycSubmission")
    count = KycSubmission.objects.count()
    if count:
        raise RuntimeError(
            f"kyc_submission has {count} rows; idempotency_key cannot be "
            "backfilled programmatically. Drop the rows or write a data "
            "migration that pulls the key from the originating client."
        )


class Migration(migrations.Migration):

    dependencies = [
        ("kyc", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(assert_empty, reverse_code=migrations.RunPython.noop),
        migrations.AddField(
            model_name="kycsubmission",
            name="idempotency_key",
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
