# Generated by Django 5.1.4 on 2026-05-11 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='wallets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'wallet_wallet',
                'ordering': ['user_id', 'currency'],
            },
        ),
        migrations.CreateModel(
            name='Hold',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('source', models.CharField(max_length=24)),
                ('source_id', models.BigIntegerField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('released', 'Released'), ('reversed', 'Reversed (refund)')], db_index=True, default='open', max_length=10)),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='holds', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_hold',
                'ordering': ['-opened_at'],
            },
        ),
        migrations.CreateModel(
            name='WalletEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('deposit', 'Deposit'), ('hold', 'Hold (escrow start)'), ('release', 'Hold release'), ('payout', 'Payout (to other wallet)'), ('refund', 'Refund (to provider)'), ('fee', 'Platform fee'), ('adjustment', 'Manual adjustment')], max_length=12)),
                ('amount_minor', models.BigIntegerField(help_text='Signed. + = credit, - = debit. Integer minor units.')),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('key', models.CharField(help_text='Idempotency key, unique per wallet: <source>:<id>:<purpose>.', max_length=128)),
                ('source', models.CharField(blank=True, default='', max_length=24)),
                ('source_id', models.BigIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_entry',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_minor', models.PositiveBigIntegerField()),
                ('currency', models.CharField(choices=[('DZD', 'Algerian Dinar'), ('EUR', 'Euro')], max_length=3)),
                ('destination', models.CharField(choices=[('bank', 'Bank transfer'), ('card', 'Card payout'), ('edahabia', 'Edahabia'), ('stripe', 'Stripe payout')], max_length=12)),
                ('destination_ref', models.CharField(blank=True, default='', help_text='IBAN / card last 4 / etc.', max_length=128)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], db_index=True, default='requested', max_length=12)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='withdrawals', to='wallet.wallet')),
            ],
            options={
                'db_table': 'wallet_withdrawal',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='wallet',
            constraint=models.UniqueConstraint(fields=('user', 'currency'), name='wallet_unique_user_currency'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['wallet', 'status'], name='wallet_hold_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='hold',
            index=models.Index(fields=['source', 'source_id'], name='wallet_hold_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='hold',
            constraint=models.UniqueConstraint(fields=('source', 'source_id'), name='wallet_hold_unique_source'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['wallet', '-created_at'], name='wallet_entry_wallet_idx'),
        ),
        migrations.AddIndex(
            model_name='walletentry',
            index=models.Index(fields=['source', 'source_id'], name='wallet_entry_source_idx'),
        ),
        migrations.AddConstraint(
            model_name='walletentry',
            constraint=models.UniqueConstraint(fields=('wallet', 'key'), name='wallet_entry_unique_key'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['user', '-created_at'], name='wallet_wd_user_idx'),
        ),
        migrations.AddIndex(
            model_name='withdrawal',
            index=models.Index(fields=['status'], name='wallet_wd_status_idx'),
        ),
    ]
