# Generated by Django 5.1.4 on 2026-08-24

import decimal
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trips", "0003_tripmedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("city", "City"),
                            ("exact_address", "Exact address"),
                            ("map_point", "Map point"),
                            ("airport", "Airport"),
                            ("public_meeting_point", "Public meeting point"),
                        ],
                        max_length=24,
                    ),
                ),
                ("normalized_label", models.CharField(max_length=500)),
                ("public_label", models.CharField(max_length=255)),
                ("private_label", models.CharField(max_length=500)),
                ("city", models.CharField(max_length=120)),
                ("region", models.CharField(blank=True, default="", max_length=120)),
                (
                    "country_code",
                    models.CharField(
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                message=(
                                    "Use an uppercase ISO 3166-1 alpha-2 country code."
                                ),
                                regex="^[A-Z]{2}$",
                            )
                        ],
                    ),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("-90")
                            ),
                            django.core.validators.MaxValueValidator(
                                decimal.Decimal("90")
                            ),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=9,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("-180")
                            ),
                            django.core.validators.MaxValueValidator(
                                decimal.Decimal("180")
                            ),
                        ],
                    ),
                ),
                (
                    "coarse_latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("-90")
                            ),
                            django.core.validators.MaxValueValidator(
                                decimal.Decimal("90")
                            ),
                        ],
                    ),
                ),
                (
                    "coarse_longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                decimal.Decimal("-180")
                            ),
                            django.core.validators.MaxValueValidator(
                                decimal.Decimal("180")
                            ),
                        ],
                    ),
                ),
                ("provider", models.CharField(blank=True, default="", max_length=64)),
                ("source", models.CharField(blank=True, default="", max_length=64)),
                (
                    "provider_place_id",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("provider_metadata", models.JSONField(blank=True, default=dict)),
                (
                    "precision",
                    models.CharField(
                        choices=[
                            ("exact", "Exact"),
                            ("rooftop", "Rooftop"),
                            ("building", "Building"),
                            ("street", "Street"),
                            ("neighborhood", "Neighborhood"),
                            ("city", "City"),
                            ("region", "Region"),
                            ("country", "Country"),
                            ("approximate", "Approximate"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "airport",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations",
                        to="trips.airport",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="locations_owned",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "locations_location",
                "ordering": ("-created_at", "-id"),
                "indexes": [
                    models.Index(
                        fields=["country_code", "city"],
                        name="locations_country_city_idx",
                    ),
                    models.Index(
                        fields=["kind", "country_code"],
                        name="locations_kind_country_idx",
                    ),
                    models.Index(
                        fields=["owner", "-created_at"],
                        name="locations_owner_created_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("latitude__gte", -90), ("latitude__lte", 90)
                        ),
                        name="locations_latitude_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("longitude__gte", -180), ("longitude__lte", 180)
                        ),
                        name="locations_longitude_range",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(
                                ("coarse_latitude__isnull", True),
                                ("coarse_longitude__isnull", True),
                            )
                            | models.Q(
                                ("coarse_latitude__isnull", False),
                                ("coarse_longitude__isnull", False),
                            )
                        ),
                        name="locations_coarse_coords_pair",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("coarse_latitude__isnull", True))
                            | models.Q(
                                ("coarse_latitude__gte", -90),
                                ("coarse_latitude__lte", 90),
                            )
                        ),
                        name="locations_coarse_lat_range",
                    ),
                    models.CheckConstraint(
                        condition=(
                            models.Q(("coarse_longitude__isnull", True))
                            | models.Q(
                                ("coarse_longitude__gte", -180),
                                ("coarse_longitude__lte", 180),
                            )
                        ),
                        name="locations_coarse_lon_range",
                    ),
                    models.UniqueConstraint(
                        condition=(
                            ~models.Q(("provider", ""))
                            & ~models.Q(("provider_place_id", ""))
                        ),
                        fields=("provider", "provider_place_id"),
                        name="locations_provider_place_uniq",
                    ),
                ],
            },
        ),
    ]
