# Generated by Django 5.1.4 on 2026-08-24 17:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0001_initial"),
        ("trips", "0004_journey_journeyleg_journeylegproof"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="locations_provider_place_uniq",
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", False),
                    models.Q(("provider", ""), _negated=True),
                    models.Q(("provider_place_id", ""), _negated=True),
                ),
                fields=("owner", "provider", "provider_place_id"),
                name="locations_owner_provider_place_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("owner__isnull", True),
                    models.Q(("provider", ""), _negated=True),
                    models.Q(("provider_place_id", ""), _negated=True),
                ),
                fields=("provider", "provider_place_id"),
                name="locations_shared_provider_place_uniq",
            ),
        ),
    ]
