# Generated by Django 5.1.4 on 2026-08-31 23:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def create_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute(
        "CREATE INDEX geo_place_norm_pattern_idx "
        "ON locations_place (normalized_name varchar_pattern_ops) "
        "WHERE active"
    )
    schema_editor.execute(
        "CREATE INDEX geo_alt_name_pattern_idx "
        "ON locations_place_alternate_name "
        "(normalized_name varchar_pattern_ops) WHERE active"
    )


def drop_postgres_search_indexes(apps, schema_editor):
    if schema_editor.connection.vendor != "postgresql":
        return
    schema_editor.execute("DROP INDEX IF EXISTS geo_alt_name_pattern_idx")
    schema_editor.execute("DROP INDEX IF EXISTS geo_place_norm_pattern_idx")


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0003_location_coordinate_trust"),
        ("trips", "0006_journey_status_published_index"),
    ]

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "code",
                    models.CharField(
                        max_length=2,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Use an uppercase ISO 3166-1 alpha-2 country code.",
                                regex="^[A-Z]{2}$",
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("normalized_name", models.CharField(editable=False, max_length=120)),
                ("source", models.CharField(max_length=96)),
                ("source_id", models.CharField(max_length=128)),
                ("source_version", models.CharField(max_length=96)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "locations_country",
                "ordering": ("name", "code"),
                "indexes": [
                    models.Index(
                        fields=["active", "name"], name="geo_country_active_name_idx"
                    ),
                    models.Index(
                        fields=["source", "source_id"], name="geo_country_source_id_idx"
                    ),
                    models.Index(
                        fields=["normalized_name"], name="geo_country_norm_name_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "source_id"),
                        name="geo_country_source_identity_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "place_type",
                    models.CharField(
                        choices=[
                            ("admin_region", "Administrative region"),
                            ("locality", "Locality / commune"),
                            ("airport", "Airport"),
                        ],
                        max_length=24,
                    ),
                ),
                ("source", models.CharField(max_length=96)),
                ("source_id", models.CharField(max_length=160)),
                ("source_version", models.CharField(max_length=96)),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(editable=False, max_length=255)),
                (
                    "admin_level",
                    models.CharField(blank=True, default="", max_length=48),
                ),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-90")),
                            django.core.validators.MaxValueValidator(Decimal("90")),
                        ],
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=9,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("-180")),
                            django.core.validators.MaxValueValidator(Decimal("180")),
                        ],
                    ),
                ),
                ("iata_code", models.CharField(blank=True, default="", max_length=3)),
                ("icao_code", models.CharField(blank=True, default="", max_length=4)),
                (
                    "airport_type",
                    models.CharField(blank=True, default="", max_length=40),
                ),
                ("passenger_use", models.BooleanField(default=False)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="places",
                        to="locations.country",
                    ),
                ),
                (
                    "legacy_airport",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="catalogue_place",
                        to="trips.airport",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="locations.place",
                    ),
                ),
            ],
            options={
                "db_table": "locations_place",
                "ordering": ("name", "id"),
            },
        ),
        migrations.CreateModel(
            name="AirportLocalityMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relationship_type",
                    models.CharField(
                        choices=[
                            ("served", "Commercially served locality"),
                            ("physical", "Physical locality"),
                        ],
                        default="served",
                        max_length=16,
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                ("source", models.CharField(max_length=96)),
                ("source_id", models.CharField(max_length=160)),
                ("source_version", models.CharField(max_length=96)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "airport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="airport_mappings",
                        to="locations.place",
                    ),
                ),
                (
                    "locality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="airport_contexts",
                        to="locations.place",
                    ),
                ),
            ],
            options={
                "db_table": "locations_airport_locality_mapping",
            },
        ),
        migrations.CreateModel(
            name="PlaceAlternateName",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("normalized_name", models.CharField(editable=False, max_length=255)),
                (
                    "language",
                    models.CharField(blank=True, default="und", max_length=16),
                ),
                ("source", models.CharField(max_length=96)),
                ("source_id", models.CharField(max_length=160)),
                ("source_version", models.CharField(max_length=96)),
                ("active", models.BooleanField(db_index=True, default=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "place",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alternate_name_records",
                        to="locations.place",
                    ),
                ),
            ],
            options={
                "db_table": "locations_place_alternate_name",
            },
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["country", "active", "place_type"],
                name="geo_place_ctry_act_type_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["source", "source_id"], name="geo_place_source_id_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["place_type", "active"], name="geo_place_type_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["parent", "active"], name="geo_place_parent_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["active", "normalized_name"],
                name="geo_place_active_norm_name_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="place",
            index=models.Index(
                fields=["country", "normalized_name"], name="geo_place_ctry_norm_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"), name="geo_place_source_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("latitude__isnull", True), ("longitude__isnull", True)),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="geo_place_coords_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("latitude__isnull", True),
                    models.Q(("latitude__gte", -90), ("latitude__lte", 90)),
                    _connector="OR",
                ),
                name="geo_place_latitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("longitude__isnull", True),
                    models.Q(("longitude__gte", -180), ("longitude__lte", 180)),
                    _connector="OR",
                ),
                name="geo_place_longitude_range",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("iata_code", ""), ("place_type", "airport"), _connector="OR"
                ),
                name="geo_place_iata_airport_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("icao_code", ""), ("place_type", "airport"), _connector="OR"
                ),
                name="geo_place_icao_airport_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("passenger_use", False), ("place_type", "airport"), _connector="OR"
                ),
                name="geo_place_passenger_airport_only",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("place_type", "airport"), _negated=True),
                    models.Q(("latitude__isnull", False), ("longitude__isnull", False)),
                    _connector="OR",
                ),
                name="geo_place_airport_coords_required",
            ),
        ),
        migrations.AddConstraint(
            model_name="place",
            constraint=models.UniqueConstraint(
                condition=models.Q(("iata_code__gt", "")),
                fields=("iata_code",),
                name="geo_place_iata_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="airportlocalitymapping",
            index=models.Index(
                fields=["airport", "active"], name="geo_map_airport_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airportlocalitymapping",
            index=models.Index(
                fields=["locality", "active"], name="geo_map_locality_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airportlocalitymapping",
            index=models.Index(
                fields=["source", "source_id"], name="geo_map_source_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="airportlocalitymapping",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"), name="geo_map_source_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="airportlocalitymapping",
            constraint=models.UniqueConstraint(
                fields=("airport", "relationship_type", "locality"),
                name="geo_map_airport_type_locality_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="airportlocalitymapping",
            constraint=models.UniqueConstraint(
                condition=models.Q(("active", True), ("is_primary", True)),
                fields=("airport", "relationship_type"),
                name="geo_map_one_primary_uniq",
            ),
        ),
        migrations.AddIndex(
            model_name="placealternatename",
            index=models.Index(
                fields=["normalized_name", "active"],
                name="geo_alt_name_norm_active_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="placealternatename",
            index=models.Index(
                fields=["source", "source_id"], name="geo_alt_name_source_id_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="placealternatename",
            constraint=models.UniqueConstraint(
                fields=("source", "source_id"), name="geo_alt_name_source_identity_uniq"
            ),
        ),
        migrations.AddConstraint(
            model_name="placealternatename",
            constraint=models.UniqueConstraint(
                fields=("place", "language", "normalized_name"),
                name="geo_alt_name_place_lang_norm_uniq",
            ),
        ),
        migrations.RunPython(
            create_postgres_search_indexes,
            drop_postgres_search_indexes,
        ),
    ]
