# Generated by Django 5.1.4 on 2026-09-01 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("locations", "0004_country_place_airportlocalitymapping_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="canonical_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="preferred_locations",
                to="locations.place",
            ),
        ),
    ]
