# Generated by Django 5.1.4 on 2026-09-02 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_location_canonical_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeographyCatalogueImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_sha256', models.CharField(max_length=64, unique=True)),
                ('counts', models.JSONField(blank=True, default=dict)),
                ('applied_by_release', models.CharField(blank=True, default='', max_length=128)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'geography catalogue import',
                'verbose_name_plural': 'geography catalogue imports',
                'db_table': 'locations_geography_catalogue_import',
                'ordering': ('-applied_at',),
            },
        ),
    ]
