# Generated by Django 5.1.4 on 2026-05-10 00:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parcels', '0001_initial'),
        ('trips', '0002_seed_airports'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_transit', 'In transit'), ('delivered', 'Delivered'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('expired', 'Expired')], db_index=True, default='pending', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='parcels.parcelrequest')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_sender', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches_as_traveler', to=settings.AUTH_USER_MODEL)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='trips.trip')),
            ],
            options={
                'db_table': 'matching_match',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposed_by', models.CharField(choices=[('traveler', 'Traveler'), ('sender', 'Sender')], max_length=10)),
                ('base_amount_dzd', models.PositiveIntegerField(default=0, help_text="Delivery: traveler's payout. Product: product price the traveler will pay at the store.", validators=[django.core.validators.MinValueValidator(0)])),
                ('base_fee_dzd', models.PositiveIntegerField(default=0, help_text='Platform base fee (product=2,500; delivery=0).', validators=[django.core.validators.MinValueValidator(0)])),
                ('commission_dzd', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_dzd', models.PositiveIntegerField(default=0, help_text='What the sender pays. Frozen at creation.', validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('countered', 'Countered'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('withdrawn', 'Withdrawn'), ('expired', 'Expired')], db_index=True, default='pending', max_length=12)),
                ('note', models.TextField(blank=True, default='', max_length=1000)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='matching.match')),
                ('parent_offer', models.OneToOneField(blank=True, help_text='Previous offer this one counters; null for the first offer.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='counter_child', to='matching.offer')),
                ('proposer', models.ForeignKey(help_text='The user who created this offer (matches `proposed_by` side).', on_delete=django.db.models.deletion.PROTECT, related_name='offers_proposed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'matching_offer',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MatchEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('match_created', 'Match created'), ('offer_created', 'Offer created'), ('offer_countered', 'Offer countered'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('offer_withdrawn', 'Offer withdrawn'), ('offer_expired', 'Offer expired'), ('match_cancelled', 'Match cancelled')], max_length=24)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='matching.match')),
                ('offer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='matching.offer')),
            ],
            options={
                'db_table': 'matching_event',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['parcel', 'status'], name='match_parcel_status_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['trip', 'status'], name='match_trip_status_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['sender', '-created_at'], name='match_sender_idx'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['traveler', '-created_at'], name='match_traveler_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('parcel', 'trip'), name='match_unique_pending_pair'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['match', '-created_at'], name='offer_match_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['status'], name='offer_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'accepted')), fields=('match',), name='offer_one_accepted_per_match'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('match',), name='offer_one_pending_per_match'),
        ),
        migrations.AddIndex(
            model_name='matchevent',
            index=models.Index(fields=['match', '-created_at'], name='match_event_idx'),
        ),
    ]
