# Generated by Django 5.1.4 on 2026-05-11 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchevent',
            name='kind',
            field=models.CharField(choices=[('match_created', 'Match created'), ('offer_created', 'Offer created'), ('offer_countered', 'Offer countered'), ('offer_accepted', 'Offer accepted'), ('offer_declined', 'Offer declined'), ('offer_withdrawn', 'Offer withdrawn'), ('offer_expired', 'Offer expired'), ('match_cancelled', 'Match cancelled'), ('match_in_transit', 'Match in transit'), ('match_completed', 'Match completed')], max_length=24),
        ),
    ]
