# Generated by Django 5.1.4 on 2026-08-24 16:57

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_v1_business_settings'),
        ('matching', '0002_alter_matchevent_kind'),
        ('parcels', '0003_delivery_request_v1'),
        ('trips', '0004_journey_journeyleg_journeylegproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='match_unique_pending_pair',
        ),
        migrations.AddField(
            model_name='match',
            name='end_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_ending_here', to='trips.journeyleg'),
        ),
        migrations.AddField(
            model_name='match',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='trips.journey'),
        ),
        migrations.AddField(
            model_name='match',
            name='start_leg',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches_starting_here', to='trips.journeyleg'),
        ),
        migrations.AddField(
            model_name='offer',
            name='business_settings_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offers', to='core.businesssettingsversion'),
        ),
        migrations.AddField(
            model_name='offer',
            name='commission_rate_bps',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='currency',
            field=models.CharField(choices=[('DZD', 'Legacy Algerian dinar'), ('EUR', 'Euro')], default='DZD', max_length=3),
        ),
        migrations.AddField(
            model_name='offer',
            name='economics_version',
            field=models.CharField(choices=[('legacy_dzd', 'Legacy DZD'), ('v1_eur', 'V1 EUR')], db_index=True, default='legacy_dzd', max_length=16),
        ),
        migrations.AddField(
            model_name='offer',
            name='platform_fee_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='pricing_version',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='offer',
            name='sender_total_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms_snapshot',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='offer',
            name='traveler_reward_minor',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='trip',
            field=models.ForeignKey(blank=True, help_text='Legacy Trip relation. New V1 matches use journey/leg fields.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matches', to='trips.trip'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['journey', 'status'], name='match_journey_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending'), ('trip__isnull', False)), fields=('parcel', 'trip'), name='match_unique_pending_pair'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(condition=models.Q(('journey__isnull', False), ('status', 'pending')), fields=('parcel', 'journey'), name='match_unique_pending_journey'),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_leg__isnull', True), ('journey__isnull', True), ('start_leg__isnull', True), ('trip__isnull', False)), models.Q(('end_leg__isnull', False), ('journey__isnull', False), ('start_leg__isnull', False)), _connector='OR'), name='match_legacy_or_v1_route'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', 'DZD'), ('economics_version', 'legacy_dzd')), models.Q(('business_settings_version__isnull', False), ('commission_rate_bps__gte', 0), ('commission_rate_bps__lte', 10000), ('currency', 'EUR'), ('economics_version', 'v1_eur'), ('platform_fee_minor__gte', 0), ('sender_total_minor', django.db.models.expressions.CombinedExpression(models.F('traveler_reward_minor'), '+', models.F('platform_fee_minor'))), ('traveler_reward_minor__gt', 0)), _connector='OR'), name='offer_economics_consistent'),
        ),
    ]
