# Generated by Django 5.1.4 on 2026-08-24 17:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_remove_match_match_unique_pending_pair_match_end_leg_and_more'),
        ('parcels', '0003_delivery_request_v1'),
        ('trips', '0004_journey_journeyleg_journeylegproof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='match',
            name='match_legacy_or_v1_route',
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_leg__isnull', True), ('journey__isnull', True), ('start_leg__isnull', True), ('trip__isnull', False)), models.Q(('end_leg__isnull', False), ('journey__isnull', False), ('start_leg__isnull', False), ('trip__isnull', True)), _connector='OR'), name='match_legacy_or_v1_route'),
        ),
    ]
