# Generated by Django 5.1.4 on 2026-08-24 17:54

import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_seed_v1_business_settings'),
        ('matching', '0004_remove_match_match_legacy_or_v1_route_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='offer',
            name='offer_economics_consistent',
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('currency', 'DZD'), ('economics_version', 'legacy_dzd')), models.Q(('base_amount_dzd', 0), ('base_fee_dzd', 0), ('business_settings_version__isnull', False), ('commission_dzd', 0), ('commission_rate_bps__gte', 0), ('commission_rate_bps__lte', 10000), ('currency', 'EUR'), ('economics_version', 'v1_eur'), ('platform_fee_minor__gte', 0), ('sender_total_minor', django.db.models.expressions.CombinedExpression(models.F('traveler_reward_minor'), '+', models.F('platform_fee_minor'))), ('total_dzd', 0), ('traveler_reward_minor__gt', 0)), _connector='OR'), name='offer_economics_consistent'),
        ),
    ]
