# Generated by Django 5.1 on 2026-08-28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminAuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "action",
                    models.CharField(db_index=True, max_length=128),
                ),
                (
                    "target_type",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "target_id",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=128
                    ),
                ),
                (
                    "reason",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                (
                    "reference",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("before", models.JSONField(blank=True, default=dict)),
                ("after", models.JSONField(blank=True, default=dict)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_audit_actions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_panel_audit_log",
                "ordering": ("-created_at", "-id"),
                "permissions": (
                    ("view_users", "Can view users"),
                    ("view_user_sensitive", "Can view user sensitive"),
                    ("manage_users", "Can manage users"),
                    ("view_requests", "Can view requests"),
                    ("manage_requests", "Can manage requests"),
                    ("view_journeys", "Can view journeys"),
                    ("manage_journeys", "Can manage journeys"),
                    ("view_matches", "Can view matches"),
                    ("manage_matches", "Can manage matches"),
                    ("view_deals", "Can view deals"),
                    ("manage_deals", "Can manage deals"),
                    ("manage_lifecycle", "Can manage lifecycle"),
                    ("view_operational_incidents", "Can view operational incidents"),
                    ("view_support_context", "Can view support context"),
                    ("manage_cancellations", "Can manage cancellations"),
                    ("view_kyc", "Can view kyc"),
                    ("review_kyc", "Can review kyc"),
                    ("view_flight_proofs", "Can view flight proofs"),
                    ("review_flight_proofs", "Can review flight proofs"),
                    ("view_evidence", "Can view evidence"),
                    ("review_safety", "Can review safety"),
                    ("record_no_show", "Can record no show"),
                    ("view_payment_orders", "Can view payment orders"),
                    ("view_payment_attempts", "Can view payment attempts"),
                    ("view_provider_events", "Can view provider events"),
                    ("issue_refunds", "Can issue refunds"),
                    ("settle_manual_refunds", "Can settle manual refunds"),
                    ("view_payouts", "Can view payouts"),
                    ("settle_payouts", "Can settle payouts"),
                    ("reconcile_finance", "Can reconcile finance"),
                    ("view_scheduled_jobs", "Can view scheduled jobs"),
                    ("view_ratings", "Can view ratings"),
                    ("view_boosts", "Can view boosts"),
                    ("view_provider_health", "Can view provider health"),
                    ("manage_settings", "Can manage settings"),
                    ("manage_admins", "Can manage admins"),
                    ("manage_permissions", "Can manage permissions"),
                    ("view_audit_log", "Can view audit log"),
                ),
            },
        ),
        migrations.CreateModel(
            name="AdminInvitation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(db_index=True, max_length=254)),
                (
                    "role",
                    models.CharField(
                        choices=(
                            ("ops", "Ops"),
                            ("support", "Support"),
                            ("finance", "Finance"),
                            ("trust_verification", "Trust / Verification"),
                            ("super_admin", "Super Admin"),
                        ),
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("token_hash", models.CharField(editable=False, max_length=64, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("used_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "accepted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="admin_invitations_accepted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="admin_invitations_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "admin_panel_invitation",
                "ordering": ("-created_at",),
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("email", ""), _negated=True),
                        name="admin_invite_email_nonempty",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("expires_at__gt", models.F("created_at"))
                        ),
                        name="admin_invite_expiry_after_created",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=("actor", "-created_at"), name="admin_audit_actor_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="adminauditlog",
            index=models.Index(
                fields=("target_type", "target_id", "-created_at"),
                name="admin_audit_target_time_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="admininvitation",
            index=models.Index(
                fields=("email", "expires_at"), name="admin_invite_email_exp_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="admininvitation",
            index=models.Index(
                fields=("used_at", "revoked_at", "expires_at"),
                name="admin_invite_active_idx",
            ),
        ),
    ]

