# Generated by Django 5.1.4 on 2026-09-07 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("admin_panel", "0003_alter_adminauditlog_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="adminauditlog",
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": (
                    ("view_dashboard", "Can view dashboard"),
                    ("view_users", "Can view users"),
                    ("view_user_sensitive", "Can view user sensitive"),
                    ("manage_users", "Can manage users"),
                    ("view_requests", "Can view requests"),
                    ("manage_requests", "Can manage requests"),
                    ("view_journeys", "Can view journeys"),
                    ("manage_journeys", "Can manage journeys"),
                    ("view_matches", "Can view matches"),
                    ("manage_matches", "Can manage matches"),
                    ("view_deals", "Can view deals"),
                    ("manage_deals", "Can manage deals"),
                    ("manage_lifecycle", "Can manage lifecycle"),
                    ("view_operational_incidents", "Can view operational incidents"),
                    ("view_support_context", "Can view support context"),
                    ("manage_cancellations", "Can manage cancellations"),
                    ("view_kyc", "Can view kyc"),
                    ("review_kyc", "Can review kyc"),
                    ("view_flight_proofs", "Can view flight proofs"),
                    ("review_flight_proofs", "Can review flight proofs"),
                    ("view_evidence", "Can view evidence"),
                    ("view_disputes", "Can view disputes"),
                    ("manage_disputes", "Can manage disputes"),
                    ("resolve_disputes", "Can resolve disputes"),
                    ("review_safety", "Can review safety"),
                    ("record_no_show", "Can record no show"),
                    ("view_payment_orders", "Can view payment orders"),
                    ("view_payment_attempts", "Can view payment attempts"),
                    ("view_provider_events", "Can view provider events"),
                    ("issue_refunds", "Can issue refunds"),
                    ("settle_manual_refunds", "Can settle manual refunds"),
                    ("view_payouts", "Can view payouts"),
                    ("settle_payouts", "Can settle payouts"),
                    ("reconcile_finance", "Can reconcile finance"),
                    ("view_scheduled_jobs", "Can view scheduled jobs"),
                    ("view_ratings", "Can view ratings"),
                    ("view_boosts", "Can view boosts"),
                    ("view_provider_health", "Can view provider health"),
                    ("view_settings", "Can view settings"),
                    ("manage_settings", "Can manage settings"),
                    ("manage_admins", "Can manage admins"),
                    ("manage_permissions", "Can manage permissions"),
                    ("view_audit_log", "Can view audit log"),
                    ("view_finance_summary", "Can view finance summary"),
                    ("view_payout_sensitive", "Can view payout sensitive"),
                    ("view_payout_evidence", "Can view payout evidence"),
                    ("review_payout_profiles", "Can review payout profiles"),
                    ("attest_payout_identity", "Can attest payout identity"),
                    ("manage_payout_holds", "Can manage payout holds"),
                    ("retry_payouts", "Can retry payouts"),
                ),
            },
        ),
    ]
