# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0006_seed_phase4_business_settings'),
        ('finance', '0004_alter_paymentrefund_reason_alter_payout_status_and_more'),
        ('parcels', '0007_alter_parcelrequest_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostPurchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_reference', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('package_code', models.CharField(db_index=True, max_length=32)),
                ('package_snapshot', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.PositiveIntegerField()),
                ('price_eur_cents', models.PositiveBigIntegerField()),
                ('ranking_weight', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('pending_payment', 'Pending payment'), ('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled before payment'), ('unusable', 'Paid but unusable'), ('refunded', 'Refunded')], db_index=True, default='pending_payment', max_length=20)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('disposition_reason', models.CharField(blank=True, default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_settings_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boost_purchases', to='core.businesssettingsversion')),
                ('buyer', models.ForeignKey(help_text="Always the delivery request's own sender.", on_delete=django.db.models.deletion.PROTECT, related_name='boost_purchases', to=settings.AUTH_USER_MODEL)),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boost_purchases', to='parcels.deliveryrequest')),
                ('payment_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost_purchase', to='finance.paymentorder')),
            ],
            options={
                'db_table': 'boosts_purchase',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['delivery_request', '-created_at'], name='boosts_request_idx'), models.Index(fields=['status', 'expires_at'], name='boosts_expiry_idx'), models.Index(fields=['buyer', '-created_at'], name='boosts_buyer_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('price_eur_cents__gt', 0)), name='boosts_price_positive'), models.CheckConstraint(condition=models.Q(('duration_seconds__gt', 0)), name='boosts_duration_positive'), models.CheckConstraint(condition=models.Q(('ranking_weight__gt', 0)), name='boosts_weight_positive'), models.CheckConstraint(condition=models.Q(models.Q(('status', 'active'), _negated=True), models.Q(('activated_at__isnull', False), ('expires_at__isnull', False)), _connector='OR'), name='boosts_active_requires_window')],
            },
        ),
    ]
