# Generated by Django 5.1.4 on 2026-09-05 16:02

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


def preserve_legacy_economics(apps, schema_editor):
    del schema_editor
    BoostPurchase = apps.get_model("boosts", "BoostPurchase")
    BoostPurchase.objects.update(economics_version="visibility_only")


def noop_reverse(apps, schema_editor):
    del apps, schema_editor


class Migration(migrations.Migration):
    dependencies = [
        ("boosts", "0001_initial"),
        ("core", "0009_seed_boost_economics"),
        ("deals", "0006_dealrecipient_communication_language"),
        ("finance", "0007_alter_ledgertransaction_kind"),
        ("parcels", "0009_phase8fb_staged_parcel_media"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="boostpurchase",
            name="boosts_price_positive",
        ),
        migrations.RenameField(
            model_name="boostpurchase",
            old_name="price_eur_cents",
            new_name="amount_eur_cents",
        ),
        migrations.AddField(
            model_name="boostpurchase",
            name="deal",
            field=models.ForeignKey(
                blank=True,
                help_text="The Deal whose Traveler earns this boost allocation.",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="boost_purchases",
                to="deals.deal",
            ),
        ),
        migrations.AddField(
            model_name="boostpurchase",
            name="economics_version",
            field=models.CharField(
                choices=[
                    ("visibility_only", "Legacy visibility only"),
                    ("traveler_split_v1", "Traveler split V1"),
                ],
                default="traveler_split_v1",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="boostpurchase",
            name="platform_boost_eur_cents",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boostpurchase",
            name="traveler_boost_eur_cents",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="boostpurchase",
            name="traveler_share_bps",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.RunPython(preserve_legacy_economics, noop_reverse),
        migrations.AddConstraint(
            model_name="boostpurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_eur_cents__gt", 0)),
                name="boosts_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="boostpurchase",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("economics_version", "visibility_only"),
                    models.Q(
                        ("traveler_share_bps__gte", 5001),
                        ("traveler_share_bps__lte", 9999),
                        (
                            "amount_eur_cents",
                            django.db.models.expressions.CombinedExpression(
                                models.F("traveler_boost_eur_cents"),
                                "+",
                                models.F("platform_boost_eur_cents"),
                            ),
                        ),
                    ),
                    _connector="OR",
                ),
                name="boosts_economic_split_consistent",
            ),
        ),
    ]
