# Generated by Django 5.1.4 on 2026-09-15 18:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boosts', '0002_remove_boostpurchase_boosts_price_positive_and_more'),
        ('core', '0010_seed_j2_boost_commission'),
        ('deals', '0008_phase_i1a_journey_timing'),
        ('parcels', '0010_j2_boost_reward'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BoostIntentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('sender_set', 'Sender set the boost'), ('sender_increased', 'Sender increased the boost'), ('sender_decreased', 'Sender decreased the boost'), ('sender_removed', 'Sender removed the boost'), ('frozen_into_deal', 'Frozen into a committed Deal'), ('consumed_by_funding', 'Consumed by Deal funding'), ('released_with_reservation', 'Revived with an unfunded reservation release'), ('request_closed', 'Request cancelled or expired')], max_length=32)),
                ('previous_eur_cents', models.PositiveBigIntegerField()),
                ('amount_eur_cents', models.PositiveBigIntegerField()),
                ('commission_rate_bps', models.PositiveSmallIntegerField(default=0)),
                ('ranking_weight', models.PositiveSmallIntegerField(default=0)),
                ('request_status', models.CharField(blank=True, default='', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null when the platform moved the amount, not a person.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost_intent_events', to=settings.AUTH_USER_MODEL)),
                ('business_settings_version', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost_intent_events', to='core.businesssettingsversion')),
                ('deal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='boost_intent_events', to='deals.deal')),
                ('delivery_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='boost_intent_events', to='parcels.deliveryrequest')),
            ],
            options={
                'db_table': 'boosts_intent_event',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['delivery_request', '-created_at'], name='boosts_intent_request_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('commission_rate_bps__lte', 10000)), name='boosts_intent_commission_bps')],
            },
        ),
    ]
