// ShipTrip KYC sync contract.
//
// Per CLAUDE.md §1 + ARCHITECTURE.md §6: KYC submission is a two-phase
// flow that the Go kyc-service drives and the Django monolith ratifies.
//
//   1. Flutter posts a multipart to the Go kyc-service.
//   2. kyc-service streams the document images to MinIO/S3 under
//      `kyc-docs/<user_id>/<uuid>.<ext>`.
//   3. kyc-service calls Django (this service) with the image keys plus
//      a Flutter-generated idempotency key, so retries on flaky mobile
//      networks are no-ops.
//   4. Django INSERTs (ON CONFLICT idempotency_key DO NOTHING) and
//      returns the submission id.
//
// The bytes never traverse this RPC; only metadata. That keeps message
// size well under the 16 MB grpc limit configured per ARCH §6.
//
// Channel security: mTLS in production (ARCH §6 "mTLS, not static
// bearer"). Static bearer is permitted only in docker-compose dev.
//
// File ownership: jointly owned. Either Claude regenerates stubs after
// changes — Go via the protoc target in backend/Taskfile.yml, Django via
// `python -m grpc_tools.protoc` (CLAUDE.md §1).

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: kyc.proto

package kycpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DocumentType mirrors apps/kyc/models.py KycSubmission.DocumentType.
// Adding a value here REQUIRES a matching Django enum change.
type DocumentType int32

const (
	DocumentType_DOCUMENT_TYPE_UNSPECIFIED     DocumentType = 0
	DocumentType_DOCUMENT_TYPE_ID_CARD         DocumentType = 1
	DocumentType_DOCUMENT_TYPE_PASSPORT        DocumentType = 2
	DocumentType_DOCUMENT_TYPE_DRIVING_LICENSE DocumentType = 3
)

// Enum value maps for DocumentType.
var (
	DocumentType_name = map[int32]string{
		0: "DOCUMENT_TYPE_UNSPECIFIED",
		1: "DOCUMENT_TYPE_ID_CARD",
		2: "DOCUMENT_TYPE_PASSPORT",
		3: "DOCUMENT_TYPE_DRIVING_LICENSE",
	}
	DocumentType_value = map[string]int32{
		"DOCUMENT_TYPE_UNSPECIFIED":     0,
		"DOCUMENT_TYPE_ID_CARD":         1,
		"DOCUMENT_TYPE_PASSPORT":        2,
		"DOCUMENT_TYPE_DRIVING_LICENSE": 3,
	}
)

func (x DocumentType) Enum() *DocumentType {
	p := new(DocumentType)
	*p = x
	return p
}

func (x DocumentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DocumentType) Descriptor() protoreflect.EnumDescriptor {
	return file_kyc_proto_enumTypes[0].Descriptor()
}

func (DocumentType) Type() protoreflect.EnumType {
	return &file_kyc_proto_enumTypes[0]
}

func (x DocumentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DocumentType.Descriptor instead.
func (DocumentType) EnumDescriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{0}
}

// Status mirrors apps/kyc/models.py KycSubmission.Status. Django is the
// only writer of status; kyc-service reads it for the /api/v1/kyc/me
// endpoint and via the kyc.status_changed Redis channel.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_PENDING     Status = 1
	Status_STATUS_APPROVED    Status = 2
	Status_STATUS_REJECTED    Status = 3
	Status_STATUS_EXPIRED     Status = 4
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_PENDING",
		2: "STATUS_APPROVED",
		3: "STATUS_REJECTED",
		4: "STATUS_EXPIRED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_PENDING":     1,
		"STATUS_APPROVED":    2,
		"STATUS_REJECTED":    3,
		"STATUS_EXPIRED":     4,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_kyc_proto_enumTypes[1].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_kyc_proto_enumTypes[1]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{1}
}

// RecordSubmissionRequest is the metadata Django needs to durably create
// (or reuse, via idempotency_key) a kyc_submission row.
//
// `idempotency_key` is generated by Flutter (UUID v4 hex). It MUST be
// stable across retries of the same logical submission — Flutter caches
// it locally until the request succeeds.
type RecordSubmissionRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DocumentType   DocumentType           `protobuf:"varint,2,opt,name=document_type,json=documentType,proto3,enum=shiptrip.kyc.v1.DocumentType" json:"document_type,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	// S3/MinIO object keys. The bytes are already uploaded; Django only
	// records references. back_image_key and selfie_image_key are optional
	// (passport submissions have no back side, etc.).
	FrontImageKey  string `protobuf:"bytes,4,opt,name=front_image_key,json=frontImageKey,proto3" json:"front_image_key,omitempty"`
	BackImageKey   string `protobuf:"bytes,5,opt,name=back_image_key,json=backImageKey,proto3" json:"back_image_key,omitempty"`
	SelfieImageKey string `protobuf:"bytes,6,opt,name=selfie_image_key,json=selfieImageKey,proto3" json:"selfie_image_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RecordSubmissionRequest) Reset() {
	*x = RecordSubmissionRequest{}
	mi := &file_kyc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSubmissionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSubmissionRequest) ProtoMessage() {}

func (x *RecordSubmissionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSubmissionRequest.ProtoReflect.Descriptor instead.
func (*RecordSubmissionRequest) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{0}
}

func (x *RecordSubmissionRequest) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *RecordSubmissionRequest) GetDocumentType() DocumentType {
	if x != nil {
		return x.DocumentType
	}
	return DocumentType_DOCUMENT_TYPE_UNSPECIFIED
}

func (x *RecordSubmissionRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *RecordSubmissionRequest) GetFrontImageKey() string {
	if x != nil {
		return x.FrontImageKey
	}
	return ""
}

func (x *RecordSubmissionRequest) GetBackImageKey() string {
	if x != nil {
		return x.BackImageKey
	}
	return ""
}

func (x *RecordSubmissionRequest) GetSelfieImageKey() string {
	if x != nil {
		return x.SelfieImageKey
	}
	return ""
}

// RecordSubmissionResponse always returns the submission id — either the
// freshly inserted row's id, or the existing row's id on idempotent
// retry. `created` distinguishes the two so kyc-service can surface a
// 201 vs 200 to the client.
type RecordSubmissionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId  int64                  `protobuf:"varint,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Created       bool                   `protobuf:"varint,2,opt,name=created,proto3" json:"created,omitempty"`
	Status        Status                 `protobuf:"varint,3,opt,name=status,proto3,enum=shiptrip.kyc.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordSubmissionResponse) Reset() {
	*x = RecordSubmissionResponse{}
	mi := &file_kyc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordSubmissionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordSubmissionResponse) ProtoMessage() {}

func (x *RecordSubmissionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kyc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordSubmissionResponse.ProtoReflect.Descriptor instead.
func (*RecordSubmissionResponse) Descriptor() ([]byte, []int) {
	return file_kyc_proto_rawDescGZIP(), []int{1}
}

func (x *RecordSubmissionResponse) GetSubmissionId() int64 {
	if x != nil {
		return x.SubmissionId
	}
	return 0
}

func (x *RecordSubmissionResponse) GetCreated() bool {
	if x != nil {
		return x.Created
	}
	return false
}

func (x *RecordSubmissionResponse) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

var File_kyc_proto protoreflect.FileDescriptor

const file_kyc_proto_rawDesc = "" +
	"\n" +
	"\tkyc.proto\x12\x0fshiptrip.kyc.v1\"\x97\x02\n" +
	"\x17RecordSubmissionRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12B\n" +
	"\rdocument_type\x18\x02 \x01(\x0e2\x1d.shiptrip.kyc.v1.DocumentTypeR\fdocumentType\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\x12&\n" +
	"\x0ffront_image_key\x18\x04 \x01(\tR\rfrontImageKey\x12$\n" +
	"\x0eback_image_key\x18\x05 \x01(\tR\fbackImageKey\x12(\n" +
	"\x10selfie_image_key\x18\x06 \x01(\tR\x0eselfieImageKey\"\x8a\x01\n" +
	"\x18RecordSubmissionResponse\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\x03R\fsubmissionId\x12\x18\n" +
	"\acreated\x18\x02 \x01(\bR\acreated\x12/\n" +
	"\x06status\x18\x03 \x01(\x0e2\x17.shiptrip.kyc.v1.StatusR\x06status*\x87\x01\n" +
	"\fDocumentType\x12\x1d\n" +
	"\x19DOCUMENT_TYPE_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15DOCUMENT_TYPE_ID_CARD\x10\x01\x12\x1a\n" +
	"\x16DOCUMENT_TYPE_PASSPORT\x10\x02\x12!\n" +
	"\x1dDOCUMENT_TYPE_DRIVING_LICENSE\x10\x03*r\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSTATUS_PENDING\x10\x01\x12\x13\n" +
	"\x0fSTATUS_APPROVED\x10\x02\x12\x13\n" +
	"\x0fSTATUS_REJECTED\x10\x03\x12\x12\n" +
	"\x0eSTATUS_EXPIRED\x10\x042\x7f\n" +
	"\x14KYCSubmissionService\x12g\n" +
	"\x10RecordSubmission\x12(.shiptrip.kyc.v1.RecordSubmissionRequest\x1a).shiptrip.kyc.v1.RecordSubmissionResponseB#Z!shiptrip/internal/kyc/kycpb;kycpbb\x06proto3"

var (
	file_kyc_proto_rawDescOnce sync.Once
	file_kyc_proto_rawDescData []byte
)

func file_kyc_proto_rawDescGZIP() []byte {
	file_kyc_proto_rawDescOnce.Do(func() {
		file_kyc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)))
	})
	return file_kyc_proto_rawDescData
}

var file_kyc_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kyc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kyc_proto_goTypes = []any{
	(DocumentType)(0),                // 0: shiptrip.kyc.v1.DocumentType
	(Status)(0),                      // 1: shiptrip.kyc.v1.Status
	(*RecordSubmissionRequest)(nil),  // 2: shiptrip.kyc.v1.RecordSubmissionRequest
	(*RecordSubmissionResponse)(nil), // 3: shiptrip.kyc.v1.RecordSubmissionResponse
}
var file_kyc_proto_depIdxs = []int32{
	0, // 0: shiptrip.kyc.v1.RecordSubmissionRequest.document_type:type_name -> shiptrip.kyc.v1.DocumentType
	1, // 1: shiptrip.kyc.v1.RecordSubmissionResponse.status:type_name -> shiptrip.kyc.v1.Status
	2, // 2: shiptrip.kyc.v1.KYCSubmissionService.RecordSubmission:input_type -> shiptrip.kyc.v1.RecordSubmissionRequest
	3, // 3: shiptrip.kyc.v1.KYCSubmissionService.RecordSubmission:output_type -> shiptrip.kyc.v1.RecordSubmissionResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kyc_proto_init() }
func file_kyc_proto_init() {
	if File_kyc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kyc_proto_rawDesc), len(file_kyc_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kyc_proto_goTypes,
		DependencyIndexes: file_kyc_proto_depIdxs,
		EnumInfos:         file_kyc_proto_enumTypes,
		MessageInfos:      file_kyc_proto_msgTypes,
	}.Build()
	File_kyc_proto = out.File
	file_kyc_proto_goTypes = nil
	file_kyc_proto_depIdxs = nil
}
