// ShipTrip KYC sync contract.
//
// Per CLAUDE.md §1 + ARCHITECTURE.md §6: KYC submission is a two-phase
// flow that the Go kyc-service drives and the Django monolith ratifies.
//
//   1. Flutter posts a multipart to the Go kyc-service.
//   2. kyc-service streams the document images to MinIO/S3 under
//      `kyc-docs/<user_id>/<uuid>.<ext>`.
//   3. kyc-service calls Django (this service) with the image keys plus
//      a Flutter-generated idempotency key, so retries on flaky mobile
//      networks are no-ops.
//   4. Django INSERTs (ON CONFLICT idempotency_key DO NOTHING) and
//      returns the submission id.
//
// The bytes never traverse this RPC; only metadata. That keeps message
// size well under the 16 MB grpc limit configured per ARCH §6.
//
// Channel security: mTLS in production (ARCH §6 "mTLS, not static
// bearer"). Static bearer is permitted only in docker-compose dev.
//
// File ownership: jointly owned. Either Claude regenerates stubs after
// changes — Go via the protoc target in backend/Taskfile.yml, Django via
// `python -m grpc_tools.protoc` (CLAUDE.md §1).

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.1
// source: kyc.proto

package kycpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KYCSubmissionService_RecordSubmission_FullMethodName = "/shiptrip.kyc.v1.KYCSubmissionService/RecordSubmission"
)

// KYCSubmissionServiceClient is the client API for KYCSubmissionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KYCSubmissionServiceClient interface {
	RecordSubmission(ctx context.Context, in *RecordSubmissionRequest, opts ...grpc.CallOption) (*RecordSubmissionResponse, error)
}

type kYCSubmissionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKYCSubmissionServiceClient(cc grpc.ClientConnInterface) KYCSubmissionServiceClient {
	return &kYCSubmissionServiceClient{cc}
}

func (c *kYCSubmissionServiceClient) RecordSubmission(ctx context.Context, in *RecordSubmissionRequest, opts ...grpc.CallOption) (*RecordSubmissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordSubmissionResponse)
	err := c.cc.Invoke(ctx, KYCSubmissionService_RecordSubmission_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KYCSubmissionServiceServer is the server API for KYCSubmissionService service.
// All implementations must embed UnimplementedKYCSubmissionServiceServer
// for forward compatibility.
type KYCSubmissionServiceServer interface {
	RecordSubmission(context.Context, *RecordSubmissionRequest) (*RecordSubmissionResponse, error)
	mustEmbedUnimplementedKYCSubmissionServiceServer()
}

// UnimplementedKYCSubmissionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKYCSubmissionServiceServer struct{}

func (UnimplementedKYCSubmissionServiceServer) RecordSubmission(context.Context, *RecordSubmissionRequest) (*RecordSubmissionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RecordSubmission not implemented")
}
func (UnimplementedKYCSubmissionServiceServer) mustEmbedUnimplementedKYCSubmissionServiceServer() {}
func (UnimplementedKYCSubmissionServiceServer) testEmbeddedByValue()                              {}

// UnsafeKYCSubmissionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KYCSubmissionServiceServer will
// result in compilation errors.
type UnsafeKYCSubmissionServiceServer interface {
	mustEmbedUnimplementedKYCSubmissionServiceServer()
}

func RegisterKYCSubmissionServiceServer(s grpc.ServiceRegistrar, srv KYCSubmissionServiceServer) {
	// If the following call panics, it indicates UnimplementedKYCSubmissionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KYCSubmissionService_ServiceDesc, srv)
}

func _KYCSubmissionService_RecordSubmission_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordSubmissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KYCSubmissionServiceServer).RecordSubmission(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KYCSubmissionService_RecordSubmission_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KYCSubmissionServiceServer).RecordSubmission(ctx, req.(*RecordSubmissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KYCSubmissionService_ServiceDesc is the grpc.ServiceDesc for KYCSubmissionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KYCSubmissionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "shiptrip.kyc.v1.KYCSubmissionService",
	HandlerType: (*KYCSubmissionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordSubmission",
			Handler:    _KYCSubmissionService_RecordSubmission_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "kyc.proto",
}
