"""The 58 Algerian wilayas (post-2019 reorganization).

Code is the official two-digit number used by ANEM/post/CNL. Names in EN/FR.
Order is by code, which is the canonical Algerian ordering.
"""

WILAYAS: list[tuple[str, str, str]] = [
    ("01", "Adrar", "Adrar"),
    ("02", "Chlef", "Chlef"),
    ("03", "Laghouat", "Laghouat"),
    ("04", "Oum El Bouaghi", "Oum El Bouaghi"),
    ("05", "Batna", "Batna"),
    ("06", "Bejaia", "B\u00e9ja\u00efa"),
    ("07", "Biskra", "Biskra"),
    ("08", "Bechar", "B\u00e9char"),
    ("09", "Blida", "Blida"),
    ("10", "Bouira", "Bouira"),
    ("11", "Tamanrasset", "Tamanrasset"),
    ("12", "Tebessa", "T\u00e9bessa"),
    ("13", "Tlemcen", "Tlemcen"),
    ("14", "Tiaret", "Tiaret"),
    ("15", "Tizi Ouzou", "Tizi Ouzou"),
    ("16", "Algiers", "Alger"),
    ("17", "Djelfa", "Djelfa"),
    ("18", "Jijel", "Jijel"),
    ("19", "Setif", "S\u00e9tif"),
    ("20", "Saida", "Sa\u00efda"),
    ("21", "Skikda", "Skikda"),
    ("22", "Sidi Bel Abbes", "Sidi Bel Abb\u00e8s"),
    ("23", "Annaba", "Annaba"),
    ("24", "Guelma", "Guelma"),
    ("25", "Constantine", "Constantine"),
    ("26", "Medea", "M\u00e9d\u00e9a"),
    ("27", "Mostaganem", "Mostaganem"),
    ("28", "M'Sila", "M'Sila"),
    ("29", "Mascara", "Mascara"),
    ("30", "Ouargla", "Ouargla"),
    ("31", "Oran", "Oran"),
    ("32", "El Bayadh", "El Bayadh"),
    ("33", "Illizi", "Illizi"),
    ("34", "Bordj Bou Arreridj", "Bordj Bou Arr\u00e9ridj"),
    ("35", "Boumerdes", "Boumerd\u00e8s"),
    ("36", "El Tarf", "El Tarf"),
    ("37", "Tindouf", "Tindouf"),
    ("38", "Tissemsilt", "Tissemsilt"),
    ("39", "El Oued", "El Oued"),
    ("40", "Khenchela", "Khenchela"),
    ("41", "Souk Ahras", "Souk Ahras"),
    ("42", "Tipaza", "Tipaza"),
    ("43", "Mila", "Mila"),
    ("44", "Ain Defla", "A\u00efn Defla"),
    ("45", "Naama", "Na\u00e2ma"),
    ("46", "Ain Temouchent", "A\u00efn T\u00e9mouchent"),
    ("47", "Ghardaia", "Ghard\u00e2\u00efa"),
    ("48", "Relizane", "Relizane"),
    ("49", "Timimoun", "Timimoun"),
    ("50", "Bordj Badji Mokhtar", "Bordj Badji Mokhtar"),
    ("51", "Ouled Djellal", "Ouled Djellal"),
    ("52", "Beni Abbes", "B\u00e9ni Abb\u00e8s"),
    ("53", "In Salah", "In Salah"),
    ("54", "In Guezzam", "In Guezzam"),
    ("55", "Touggourt", "Touggourt"),
    ("56", "Djanet", "Djanet"),
    ("57", "El M'Ghair", "El M'Ghair"),
    ("58", "El Meniaa", "El Meniaa"),
]

WILAYA_CHOICES: list[tuple[str, str]] = [(code, name_en) for code, name_en, _ in WILAYAS]
WILAYA_CODES: frozenset[str] = frozenset(code for code, _, _ in WILAYAS)
