# Generated by Django 5.1.4 on 2026-05-07 17:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublishedEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(db_index=True, max_length=128)),
                ('event_id', models.CharField(max_length=64, unique=True)),
                ('payload_hash', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'core_published_event',
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['delivered_at', 'published_at'], name='core_pe_undelivered_idx')],
            },
        ),
    ]
