# Generated by Django 5.1.4 on 2026-08-24 16:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessSettingsVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(unique=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('retired', 'Retired')], db_index=True, default='draft', max_length=12)),
                ('canonical_currency', models.CharField(default='EUR', editable=False, max_length=3)),
                ('commission_rate_bps', models.PositiveSmallIntegerField(default=2500)),
                ('pricing_version', models.CharField(default='v1', max_length=32)),
                ('policy', models.JSONField(blank=True, default=dict)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='business_settings_versions_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'core_business_settings_version',
                'ordering': ['-version'],
                'indexes': [models.Index(fields=['status', '-version'], name='core_settings_status_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('canonical_currency', 'EUR')), name='core_settings_currency_eur'), models.CheckConstraint(condition=models.Q(('commission_rate_bps__lte', 10000)), name='core_settings_commission_bps'), models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('status',), name='core_settings_one_active')],
            },
        ),
    ]
