# Generated by Django 5.1.4 on 2026-08-24 16:57

import django.db.models.deletion
import django.db.models.expressions
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("core", "0003_seed_v1_business_settings"),
        ("matching", "0002_alter_matchevent_kind"),
        ("parcels", "0003_delivery_request_v1"),
        ("trips", "0004_journey_journeyleg_journeylegproof"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Deal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("offer_accepted", "Offer accepted"),
                            ("payment_required", "Payment required"),
                            ("funded", "Funded"),
                            ("pickup_ready", "Pickup ready"),
                            ("picked_up", "Picked up"),
                            ("in_transit", "In transit"),
                            ("delivery_ready", "Delivery ready"),
                            ("delivery_confirmed", "Delivery confirmed"),
                            ("protection_window", "Protection window"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                            ("payment_failed", "Payment failed"),
                            ("disputed", "Disputed"),
                            ("refunded", "Refunded"),
                            ("partially_refunded", "Partially refunded"),
                        ],
                        db_index=True,
                        default="payment_required",
                        max_length=24,
                    ),
                ),
                ("is_legacy", models.BooleanField(db_index=True, default=False)),
                ("funded_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "accepted_offer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal",
                        to="matching.offer",
                    ),
                ),
                (
                    "delivery_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="parcels.deliveryrequest",
                    ),
                ),
                (
                    "journey",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals",
                        to="trips.journey",
                    ),
                ),
                (
                    "match",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal",
                        to="matching.match",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals_as_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "traveler",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deals_as_traveler",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "deals_deal",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DealEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("status_changed", "Status changed"),
                            ("capacity_reserved", "Capacity reserved"),
                            ("capacity_released", "Capacity released"),
                        ],
                        max_length=32,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_events_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="events",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "db_table": "deals_event",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="DealLegAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "allocated_weight_kg",
                    models.DecimalField(decimal_places=3, max_digits=8),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_payment", "Pending payment"),
                            ("funded", "Funded"),
                            ("in_transit", "In transit"),
                            ("released", "Released"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="pending_payment",
                        max_length=20,
                    ),
                ),
                ("reserved_at", models.DateTimeField(auto_now_add=True)),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                (
                    "deal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="leg_allocations",
                        to="deals.deal",
                    ),
                ),
                (
                    "journey_leg",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_allocations",
                        to="trips.journeyleg",
                    ),
                ),
            ],
            options={
                "db_table": "deals_leg_allocation",
                "ordering": ["journey_leg__position", "id"],
            },
        ),
        migrations.CreateModel(
            name="DealTermsSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("DZD", "Legacy Algerian dinar")],
                        max_length=3,
                    ),
                ),
                ("traveler_reward_minor", models.PositiveBigIntegerField()),
                ("commission_rate_bps", models.PositiveSmallIntegerField()),
                ("platform_fee_minor", models.PositiveBigIntegerField()),
                ("sender_total_minor", models.PositiveBigIntegerField()),
                ("pricing_version", models.CharField(max_length=32)),
                ("policy_snapshot", models.JSONField(blank=True, default=dict)),
                ("is_legacy", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business_settings_version",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="deal_terms_snapshots",
                        to="core.businesssettingsversion",
                    ),
                ),
                (
                    "deal",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="terms",
                        to="deals.deal",
                    ),
                ),
            ],
            options={
                "db_table": "deals_terms_snapshot",
            },
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["sender", "-created_at"], name="deals_sender_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["traveler", "-created_at"], name="deals_traveler_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deal",
            index=models.Index(
                fields=["journey", "status"], name="deals_journey_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.CheckConstraint(
                condition=models.Q(("sender", models.F("traveler")), _negated=True),
                name="deals_sender_neq_traveler",
            ),
        ),
        migrations.AddConstraint(
            model_name="deal",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        [
                            "offer_accepted",
                            "payment_required",
                            "funded",
                            "pickup_ready",
                            "picked_up",
                            "in_transit",
                            "delivery_ready",
                            "delivery_confirmed",
                            "protection_window",
                            "disputed",
                        ],
                    )
                ),
                fields=("delivery_request",),
                name="deals_one_active_per_request",
            ),
        ),
        migrations.AddIndex(
            model_name="dealevent",
            index=models.Index(
                fields=["deal", "created_at"], name="deals_event_timeline_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="deallegallocation",
            index=models.Index(
                fields=["journey_leg", "status"], name="deals_leg_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="deallegallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(("allocated_weight_kg__gt", 0)),
                name="deals_allocation_positive_weight",
            ),
        ),
        migrations.AddConstraint(
            model_name="deallegallocation",
            constraint=models.UniqueConstraint(
                fields=("deal", "journey_leg"), name="deals_allocation_unique_leg"
            ),
        ),
        migrations.AddConstraint(
            model_name="dealtermssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(("commission_rate_bps__lte", 10000)),
                name="deals_terms_commission_bps",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealtermssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "sender_total_minor",
                        django.db.models.expressions.CombinedExpression(
                            models.F("traveler_reward_minor"),
                            "+",
                            models.F("platform_fee_minor"),
                        ),
                    )
                ),
                name="deals_terms_total_sum",
            ),
        ),
        migrations.AddConstraint(
            model_name="dealtermssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_legacy", True), ("currency", "EUR"), _connector="OR"
                ),
                name="deals_terms_new_currency_eur",
            ),
        ),
    ]
