# Generated by Django 5.1.4 on 2026-08-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_seed_v1_business_settings"),
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="dealtermssnapshot",
            name="deals_terms_new_currency_eur",
        ),
        migrations.AddConstraint(
            model_name="dealtermssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_legacy", True),
                    models.Q(
                        ("business_settings_version__isnull", False),
                        ("currency", "EUR"),
                    ),
                    _connector="OR",
                ),
                name="deals_terms_new_currency_eur",
            ),
        ),
    ]
