# Generated by Django 5.1.4 on 2026-08-25 20:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_allocation_expiry'),
        ('matching', '0007_offer_economics_version_required'),
        ('parcels', '0007_alter_parcelrequest_status'),
        ('trips', '0006_journey_status_published_index'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DealRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=32)),
                ('delivery_note', models.TextField(blank=True, default='', max_length=1000)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'deals_recipient',
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='agreed_pickup_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='cancellation_reason',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='deal',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deals_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_code_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_code_released_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='delivery_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='lifecycle_policy',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='deal',
            name='no_show_note',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='deal',
            name='no_show_party',
            field=models.CharField(blank=True, choices=[('sender', 'Sender'), ('traveler', 'Traveler')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='no_show_recorded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='no_show_recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_no_shows_recorded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='pickup_confirmed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='protection_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='rating_window_ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dealevent',
            name='kind',
            field=models.CharField(choices=[('created', 'Created'), ('status_changed', 'Status changed'), ('capacity_reserved', 'Capacity reserved'), ('capacity_released', 'Capacity released'), ('recipient_set', 'Recipient details set'), ('recipient_changed', 'Recipient details changed'), ('pickup_code_issued', 'Pickup code issued'), ('pickup_code_rotated', 'Pickup code rotated'), ('pickup_code_failed', 'Pickup code attempt failed'), ('pickup_code_locked', 'Pickup code locked'), ('pickup_confirmed', 'Pickup confirmed'), ('delivery_buffer_started', 'Delivery-code safety buffer started'), ('delivery_code_released', 'Delivery code released to the sender'), ('delivery_code_rotated', 'Delivery code rotated'), ('delivery_code_failed', 'Delivery code attempt failed'), ('delivery_code_locked', 'Delivery code locked'), ('recipient_notification_queued', 'Recipient delivery-code notification queued'), ('recipient_notification_sent', 'Recipient delivery-code notification dispatched'), ('delivery_confirmed', 'Delivery confirmed'), ('protection_started', 'Protection window started'), ('protection_expired', 'Protection window expired'), ('payout_eligible', 'Payout became eligible'), ('payout_status_changed', 'Payout status changed'), ('dispute_opened', 'Dispute opened'), ('dispute_evidence_added', 'Dispute evidence added'), ('dispute_status_changed', 'Dispute status changed'), ('dispute_resolved', 'Dispute resolved'), ('cancellation_requested', 'Cancellation requested'), ('cancelled_after_funding', 'Cancelled after funding'), ('compensation_applied', 'Cancellation compensation'), ('no_show_recorded', 'No-show recorded'), ('rating_submitted', 'Rating submitted'), ('rating_revealed', 'Ratings revealed')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', 'protection_ends_at'], name='deals_protection_idx'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['status', 'delivery_code_available_at'], name='deals_code_release_idx'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_code_available_at__isnull', True), ('pickup_confirmed_at__isnull', False), _connector='OR'), name='deals_delivery_code_after_pickup'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_code_released_at__isnull', True), ('delivery_code_available_at__isnull', False), _connector='OR'), name='deals_release_after_availability'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_confirmed_at__isnull', True), ('delivery_code_released_at__isnull', False), _connector='OR'), name='deals_delivery_after_code_release'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('protection_ends_at__isnull', True), ('delivery_confirmed_at__isnull', False), _connector='OR'), name='deals_protection_requires_delivery'),
        ),
        migrations.AddConstraint(
            model_name='deal',
            constraint=models.CheckConstraint(condition=models.Q(('no_show_party', ''), models.Q(('no_show_recorded_at__isnull', False), ('no_show_recorded_by__isnull', False)), _connector='OR'), name='deals_no_show_requires_actor'),
        ),
        migrations.AddField(
            model_name='dealrecipient',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deal_recipients_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dealrecipient',
            name='deal',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recipient', to='deals.deal'),
        ),
        migrations.AddField(
            model_name='dealrecipient',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='deal_recipients_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='dealrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('full_name', ''), _negated=True), name='deals_recipient_name_required'),
        ),
        migrations.AddConstraint(
            model_name='dealrecipient',
            constraint=models.CheckConstraint(condition=models.Q(('email', ''), _negated=True), name='deals_recipient_email_required'),
        ),
    ]
