# Generated by Django 5.1.4 on 2026-08-25 22:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_dealrecipient_deal_agreed_pickup_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deal',
            options={'ordering': ['-created_at'], 'permissions': [('record_no_show', 'Can record an admin-reviewed no-show decision')]},
        ),
    ]
