# Generated by Django 5.1.4 on 2026-08-29 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_alter_deal_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealrecipient',
            name='communication_language',
            field=models.CharField(blank=True, choices=[('en', 'English'), ('fr', 'French'), ('ar', 'Arabic')], default='', help_text='Language explicitly selected for recipient communication. Blank legacy rows resolve to English.', max_length=2),
        ),
    ]
