# Generated by Django 5.1.4 on 2026-09-05 16:02

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_seed_boost_economics"),
        ("deals", "0006_dealrecipient_communication_language"),
    ]

    operations = [
        migrations.AddField(
            model_name="dealtermssnapshot",
            name="boost_amount_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dealtermssnapshot",
            name="boost_platform_fee_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="dealtermssnapshot",
            name="boost_traveler_bonus_minor",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddConstraint(
            model_name="dealtermssnapshot",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "boost_amount_minor",
                        django.db.models.expressions.CombinedExpression(
                            models.F("boost_traveler_bonus_minor"),
                            "+",
                            models.F("boost_platform_fee_minor"),
                        ),
                    )
                ),
                name="deals_terms_boost_total_sum",
            ),
        ),
    ]
