# Generated by Django 5.1.4 on 2026-09-15 18:55

import django.db.models.expressions
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_seed_j2_boost_commission'),
        ('deals', '0008_phase_i1a_journey_timing'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='dealtermssnapshot',
            name='deals_terms_boost_total_sum',
        ),
        migrations.AddField(
            model_name='dealtermssnapshot',
            name='boost_commission_rate_bps',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dealtermssnapshot',
            name='boost_economics_version',
            field=models.CharField(choices=[('traveler_split_v1', 'Traveler split V1'), ('additive_commission_v2', 'Additive commission V2')], default='traveler_split_v1', max_length=24),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boost_economics_version', 'traveler_split_v1'), _negated=True), ('boost_amount_minor', django.db.models.expressions.CombinedExpression(models.F('boost_traveler_bonus_minor'), '+', models.F('boost_platform_fee_minor'))), _connector='OR'), name='deals_terms_boost_total_sum'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('boost_economics_version', 'additive_commission_v2'), _negated=True), ('boost_amount_minor', models.F('boost_traveler_bonus_minor')), _connector='OR'), name='deals_terms_boost_additive_bonus'),
        ),
        migrations.AddConstraint(
            model_name='dealtermssnapshot',
            constraint=models.CheckConstraint(condition=models.Q(('boost_commission_rate_bps__lte', 10000)), name='deals_terms_boost_commission_bps'),
        ),
    ]
